name: flutter_english_edioms_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/LogoIdioms.png"
  
flutter:

  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic