import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class B extends StatelessWidget {
  final List _name = [
    "Babe in arms",
    "Babe in the woods",
    "Back burner",
    "Back foot",
    "Back number",
    "Back the wrong horse",
    "Back to back",
    "Back to square one",
    "Back to the drawing board",
    "Back to the salt mine",
    "Back to the wall",
    "Backseat driver",
    "Bad Apple",
    "Bad blood",
    "Bad egg",
    "Bad hair day",
    "Bad mouth",
    "Bad shape",
    "Bad taste in your mouth",
    "Bad workers always blame their tools",
    "Bag of bones",
    "Bag of nerves",
    "Baker's dozen",
    "Bald as a coot",
    "Ball is in your court",
    "Balls to the walls",
    "Banana republic",
    "Banana skin",
    "Bandit territory",
    "Baptism of fire",
    "Bar fly",
    "Bare your heart",
    "Barefaced liar",
    "Bark is worse than their bite",
    "Barking up the wrong tree",
    "Barkus is willing",
    "Barrack-room lawyer",
    "Barrel of laughs",
    "Basket case",
    "Bat an eyelid",
    "Bated breath",
    "Bats in the belfry",
    "Batten down the hatches",
    "Battle of nerves",
    "Be all ears",
    "Be careful what you wish for",
    "Be on the pig's back",
    "Be out in force",
    "Be out in left field",
    "Be that as it may",
    "Be true blue",
    "Be up the spout",
    "Bean counter",
    "Bear fruit",
    "Bear market",
    "Bear the brunt",
    "Beard the lion in his own den",
    "Beat about the bush",
    "Beat someone to the draw",
    "Beat swords into ploughshares",
    "Beat the daylights out of someone",
    "Beat the rap",
    "Beat the tar out of",
    "Beat to the punch",
    "Beat your brains out",
    "Beating a dead horse",
    "Beauty is in the eye of the beholder",
    "Beauty is only skin deep",
    "Beck and call",
    "Bedroom eyes",
    "Bee in your bonnet",
    "Bee's Knees",
    "Beeline for",
    "Been in the wars",
    "Been there, done that",
    "Beer and skittles",
    "Before the ink is dry",
    "Before you can say Jack Robinson",
    "Beggars can't be choosers",
    "Behind bars",
    "Behind closed doors",
    "Behind someone's back",
    "Behind the eight ball",
    "Behind the times",
    "Believe in the hereafter",
    "Bell the cat",
    "Bells and whistles",
    "Bells on",
    "Belly up",
    "Below par",
    "Below the belt",
    "Belt and braces",
    "Belt and suspenders",
    "Bend over backwards",
    "Bend someone's ear",
    "Benjamin of the family",
    "Beside the point",
    "Beside themselves",
    "Beside yourself",
    "Best of a bad bunch",
    "Best of both worlds",
    "Best thing since sliced bread",
    "Bet your bottom dollar",
    "Better half",
    "Better late than never",
    "Better safe than sorry",
    "Better than a kick in the teeth",
    "Better than a stick in the eye",
    "Better the devil you know",
    "Between a rock and a hard place",
    "Between the devil and the deep blue sea",
    "Between you and me and the cat's whiskers",
    "Beyond a shadow of a doubt",
    "Beyond belief",
    "Beyond our ken",
    "Beyond the pale",
    "Big Apple",
    "Big bucks",
    "Big cheese",
    "Big Easy",
    "Big fish",
    "Big fish in a small pond",
    "Big girl's blouse",
    "Big hitter",
    "Big nose",
    "Big picture",
    "Big time",
    "Bigger fish to fry",
    "Bird in the hand is worth two in the bush",
    "Bird's eye view",
    "Bird-brain",
    "Birds and the bees",
    "Birds of a feather flock together",
    "Birthday suit",
    "Bit between your teeth",
    "Bit part",
    "Bit player",
    "Bite off more than you can chew",
    "Bite someone's head off",
    "Bite the bullet",
    "Bite the dust",
    "Bite your lip",
    "Bite your tongue",
    "Bits and bobs",
    "Bitter end",
    "Bitter pill to swallow",
    "Black and blue",
    "Black and white",
    "Black as New Gate's knocker",
    "Black hole",
    "Black sheep",
    "Blackball",
    "Blank cheque",
    "Bleeding heart",
    "Bless your pointy little head",
    "Blessing in disguise",
    "Blind acceptance",
    "Blind as a bat",
    "Blind leading the blind",
    "Blind-sided",
    "Blink of an eye",
    "Blood and thunder",
    "Blood from a turnip",
    "Blood is thicker than water",
    "Blood is worth bottling",
    "Blood out of a stone",
    "Blood, sweat and tears",
    "Blow a gasket",
    "Blow by blow",
    "Blow hot and cold",
    "Blow me down",
    "Blow off steam",
    "Blow out of the water",
    "Blow smoke",
    "Blow the cobwebs away",
    "Blow the whistle",
    "Blow your mind",
    "Blow your own horn",
    "Blow your own trumpet",
    "Blow your stack",
    "Blow your top",
    "Blue blood",
    "Blue-eyed boy",
    "Bob's your uncle",
    "Body politic",
    "Bold as brass",
    "Bolt from the blue",
    "Bone of contention",
    "Bone to pick",
    "Boot is on the other foot",
    "Born to the purple",
    "Born with a silver spoon in your mouth",
    "Both ends meet",
    "Bottom line",
    "Bounce ideas",
    "Bounce off the walls",
    "Bouquet of orchids",
    "Box and dice",
    "Box clever",
    "Boxing and coxing",
    "Boys in blue",
    "Brain surgery",
    "Brass neck",
    "Brass tacks",
    "Bread and butter",
    "Breadwinner",
    "Break a leg",
    "Break even",
    "Break ground",
    "Break the back of the beast",
    "Break the ice",
    "Break your duck",
    "Break your heart",
    "Breathe down your neck",
    "Breathe life into",
    "Breathe your last",
    "Bridge the gap",
    "Bright and breezy",
    "Bright as a button",
    "Bright-eyed and bushy-tailed",
    "Brighten up the day",
    "Bring a knife to a gunfight",
    "Bring home the bacon",
    "Bring on board",
    "Bring someone to book",
    "Bring someone to heel",
    "Bring the house down",
    "Bring to the table",
    "Broad church",
    "Broad strokes",
    "Broke as a joke and it ain't funny",
    "Broken record",
    "Broken reed",
    "Brown nose",
    "Browned off",
    "Brownie points",
    "Brush under the carpet",
    "Buggles' turn",
    "Bull in a China shop",
    "Bull market",
    "Bull session",
    "Bull-headed",
    "Bums on seats",
    "Bun in the oven",
    "Bundle of nerves",
    "Bur under my saddle",
    "Burn rubber",
    "Burn the candle at both ends",
    "Burn the midnight oil",
    "Burn your bridges",
    "Burn your fingers",
    "Burning question",
    "Burst at the seams",
    "Burst your bubble",
    "Bury the hatchet",
    "Bury your head in the sand",
    "Busman's holiday",
    "Bust my chops",
    "Busted flush",
    "Busy as a beaver",
    "Busy as a bee",
    "Butt naked",
    "Butt of a joke",
    "Butter wouldn't melt in their mouth",
    "Butterfingers",
    "Butterflies in your stomach",
    "Button your lip",
    "Buy the farm",
    "By a hair's breadth",
    "By a long chalk",
    "By a whisker",
    "By and large",
    "By dint of",
    "By heart",
    "By hook or by crook",
    "By leaps and bounds",
    "By the back door",
    "By the book",
    "By the by",
    "By the numbers",
    "By the same token",
    "By the seat of your pants",
    "By the skin of your teeth",
    "By word of mouth",
  ];
  final List _nameDescription = [
    "A babe in arms is a very young child, or a person who is very young to be holding a position.",
    "A babe in the woods is a naive, defenseless, young person.",
    "If an issue is on the back burner, it is being given low priority.",
    "(UK) If you are on your back foot, you are at a disadvantage and forced to be defensive of your position.",
    "Something that's a back number is dated or out of fashion.",
    "If you back the wrong horse, you give your support to the losing side in something.",
    "If things happen back to back, they are directly one after another.",
    "If you are back to square one, you have to start from the beginning again.",
    "If you have to go back to the drawing board, you have to go back to the beginning and start something again.",
    "If someone says they have to go back to the salt mine, they have to return to work.",
    "If you have your back to the wall, you are in a difficult situation with very little room for maneuver.",
    "A backseat driver is an annoying person who is fond of giving advice to the person performing a task or doing something, especially when the advice is either wrong or unwelcome.",
    "A person who is bad and makes other bad is a bad apple.",
    "If people feel hate because of things that happened in the past, there is bad blood between them.",
    "A person who cannot be trusted is a bad egg. Good egg is the opposite.",
    "If you're having a bad hair day, things are not going the way you would like or had planned.",
    "(UK) When you are bad mouthing, you are saying negative things about someone or something.('Bad-mouth' and 'badmouth' are also used)",
    "If something's in bad shape, it's in bad condition. If a person's in bad shape, they are unfit or unhealthy.",
    "If something leaves you with a bad taste in your mouth, you feel there is something wrong or bad about it.",
    "'A bad worker always blames their tools' - If somebody does a job badly or loses in a game and claims that they were let down by their equipment, you can use this to imply that this was not the case.",
    "If someone is a bag of bones, they are very underweight.",
    "If someone is a bag of nerves, they are very worried or nervous.",
    "A Baker's dozen is 13 rather than 12.",
    "A person who is completely bald is as bald as a coot.",
    "If the ball is in your court, it is up to you to make the next decision or step.",
    "(USA) If you do something balls to the wall, you apply full acceleration or exertion.",
    "Banana republic is a term used for small countries that are dependent on a single crop or resource and governed badly by a corrupt elite.",
    "(UK) A banana skin is something that is an embarrassment or causes problems.",
    "An area or an industry, profession, etc, where rules and laws are ignored or flouted is bandit territory.",
    "A baptism of fire was a soldier's first experience of shooting. Any unpleasant experience undergone, usually where it is also a learning experience is a baptism of fire.",
    "A bar fly is a person who spends a lot of time drinking in different bars and pubs.",
    "If you bare your heart to someone, you tell them your personal and private feelings. ('Bare your soul' is an alternative form of the idiom)",
    "A barefaced liar is one who displays no shame about lying even if they are exposed.",
    "Someone who's bark is worse than their bite may well get angry and shout, but doesn't take action.",
    "If you are barking up the wrong tree, it means that you have completely misunderstood something or are totally wrong.",
    "This idiom means that someone is willing to get married.",
    "(UK) A barrack-room lawyer is a person who gives opinions on things they are not qualified to speak about.",
    "If someone's a barrel of laughs, they are always joking and you find them funny.",
    "If something is a basket case, it is so bad that it cannot be helped.",
    "If someone doesn't bat an eyelid, they don't react or show any emotion when surprised, shocked, etc.",
    "If someone says they're waiting with bated breath, they're very excited and find it difficult to be patient.",
    "Someone with bats in the belfry is crazy or eccentric.",
    "If you batten down the hatches, you prepare for the worst that could happen to you.",
    "A battle of nerves is a situation where neither side in a conflict or dispute is willing to back down and is waiting for the other side to weaken. ('A war of nerves' is an alternative form)",
    "If you are all ears, you are very eager to hear what someone has to say.",
    "If you get things that you desire, there may be unforeseen and unpleasant consequences.('Be careful what you wish for, lest it come true.' and 'Be careful what you wish for; you may receive it.' are also used)",
    "If you're on the pig's back, you're happy / content / in fine form.",
    "If people are out in force, they are present somewhere in large numbers.",
    "(USA) To be out in left field is not to know what's going on. Taken from baseball, when youngsters assign less capable players to the outfield where the ball is less likely to be hit by a young player. In business, one might say, 'Don't ask the new manager; he's out in left field and doesn't know any answers yet.'",
    "Be that as it may is an expression which means that, while you are prepared to accept that there is some truth in what the other person has just said, it's not going to change your opinions in any significant manner.",
    "If a person/object/situation is considered to be 'true blue', it is considered genuine.",
    "(UK) If a woman is up the spout, she is pregnant.",
    "A bean counter is an accountant.",
    "If something bears fruit, it produces positive results.",
    "A bear market is a period when investors are pessimistic and expect financial losses so are more likely to sell than to buy shares.",
    "People who bear the brunt of something endure the worst of something bad.",
    "If you confront a powerful or dangerous rival on their territory, you are bearding the lion in his own den.",
    "If someone doesn't say clearly what they mean and try to make it hard to understand, they are beating about (around) the bush.",
    "(USA) If you beat someone to the draw, you do something before they do.",
    "If people beat swords into ploughshares, they spend money on humanitarian purposes rather than weapons. (The American English spelling is 'plowshares')",
    "If someone beats the daylights out of another person, they hit them repeatedly. ('Knock' can also be used and it can be made even stronger by saying 'the living daylights')",
    "If you beat the rap, you escape conviction and punishment for a crime or something you have done wrong.",
    "When you want to beat the tar out of someone, you want to beat them up badly.",
    "If you beat someone to the punch, you act before them and gain an advantage.",
    "If you beat your brains out, you think hard about something but cannot solve, understand or remember it.",
    "(USA) If someone is trying to convince people to do or feel something without any hope of succeeding, they're beating a dead horse. This is used when someone is trying to raise interest in an issue that no-one supports anymore; beating a dead horse will not make it do any more work.",
    "Beauty is in the eye of the beholder means that different people will find different things beautiful and that the differences of opinion don't matter greatly.",
    "This idiom means that appearances can be deceptive and something that seems or looks good may turn out to be bad.",
    "Someone who does everything for you, no matter when you ask, is at your beck and call.",
    "Someone with bedroom eyes has a sexy look in their eyes.",
    "If someone is very excited about something, they have a bee in their bonnet.",
    "If something is the bee's knees, it's outstanding or the best in its class.",
    "If you make a beeline for a place, you head there directly.",
    "(UK) If someone has been in the wars, they have been hurt or look as if they have been in a struggle.",
    "People say this when they have already experienced what is being discussed.",
    "(UK) People say that life is not all beer and skittles, meaning that it is not about self-indulgence and pleasure.",
    "If people make an agreement or contract and then the situation changes very quickly, it changes before the ink is dry.",
    "The term Jack Robinson represents 'a short amount of time'. When you do something before you can say Jack Robinson, you do it very quickly.",
    "This idiom means that people who are in great need must accept any help that is offered, even if it is not a complete solution to their problems.",
    "When someone is behind bars, they are in prison.",
    "If something happens away from the public eye, it happens behind closed doors.",
    "If you do something behind someone's back, you do it without telling them.",
    "A difficult position from which it is unlikely one can escape.",
    "Someone that is behind the times is old-fashioned and has ideas that are regarded as out-dated.",
    "A belief in the hereafter is a belief in the afterlife, or life after death.",
    "To bell the cat is to perform a difficult or impossible task.",
    "Bells and whistles are attractive features that things like computer programs have, though often a bit unnecessary.",
    "(USA) To be somewhere with bells on means to arrive there happy and delighted to attend.",
    "If things go belly up, they go badly wrong.",
    "If something isn't up to standard, or someone isn't feeling or doing very well, they are below par.",
    "If someone says something that is cruel or unfair, it is below the belt, like the illegal punches in boxing.",
    "(UK) Someone who wears belt and braces is very cautious and takes no risks.",
    "(USA) Someone who wears belt and suspenders is very cautious and takes no risks.",
    "If someone bends over backwards, they do everything they can to help someone.",
    "To bend someone's ear is to talk to someone about something for a long-enough period that it becomes tiresome for the listener.",
    "The Benjamin of the family is the youngest child.",
    "If something is beside the point, it's not relevant to the matter being discussed or considered.",
    "If people are beside themselves, they are very worried or emotional about something.",
    "If you are beside yourself, you are extremely angry.",
    "The best that could be obtained from a list of options that were not exactly what was required.",
    "If you have the best of both worlds, you benefit from different things that do not normally go together.",
    "If something is the best thing since sliced bread, it is excellent. ('The greatest thing since sliced bread' is also used)",
    "(USA) If you can bet your bottom dollar on something, you can be absolutely sure about it.",
    "Your better half is your husband or wife.",
    "This idiom suggests that doing something late is better than not doing it at all.",
    "This idiom is used to recommend being cautious rather than taking a risk.",
    "If something is better than a kick in the teeth, it isn't very good, but it is better than nothing.",
    "If something is better than a stick in the eye, it isn't very good, but it is better than nothing.",
    "This is the shortened form of the full idiom, 'better the devil you know than the devil you don't', and means that it is often better to deal with someone or something you are familiar with and know, even if they are not ideal, than take a risk with an unknown person or thing.",
    "If you are caught between a rock and a hard place, you are in a position where you have to choose between unpleasant alternatives, and your choice might cause you problems; you will not be able to satisfy everyone.",
    "If you are caught between the devil and the deep blue sea, you are in a dilemma; a difficult choice.",
    "This idiom is used when telling someone something that you want them to keep secret.",
    "If something's beyond a shadow of a doubt, then absolutely no doubts remain about it.",
    "If people behave in such a way that you find it almost impossible to accept that they actually did it, then you can say that their behavior was beyond belief.",
    "If something's beyond your ken, it is beyond your understanding.",
    "If something's beyond the pale, it is too extreme to be acceptable morally or socially.",
    "(USA) The Big Apple is New York.",
    "If someone is making big bucks, they are making a lot of money.",
    "The big cheese is the boss.",
    "(USA) The Big Easy is New Orleans, Louisiana.",
    "An important person in a company or an organization is a big fish.",
    "A big fish in a small pond is an important person in a small place or organization.",
    "A person who is very weak or fussy is a big girl's blouse.",
    "A big hitter is someone who commands a lot of respect and is very important in their field.",
    "If someone has a big nose, it means they are excessively interested in everyone else's business.",
    "The big picture of something is the overall perspective or objective, not the fine detail.",
    "This can be used to with the meaning 'very much'- if you like something big time, you like it a lot.",
    "If you aren't interested in something because it isn't important to you and there are more important things for you to do, you have bigger fish to fry.",
    "'A bird in the hand is worth two in the bush' is a proverb meaning that it is better to have something that is certain than take a risk to get more, where you might lose everything.",
    "If you have a bird's eye view of something, you can see it perfectly clearly.",
    "Someone who has a bird-brain, or is bird-brained, is stupid.",
    "If a child is taught about the birds and the bees, they are taught about sex.",
    "This idiom means that people with similar interests will stick together.",
    "If you are in your birthday suit, you are naked.",
    "If you take or have the bit between your teeth, you take or have control of a situation. (Bit = piece of metal in a horse's mouth)",
    "If someone has a small or unimportant role in something, they have a bit part.",
    "A bit player has a small or unimportant role in something.",
    "If you bite off more than you can chew, you take on more responsibilities than you can manage. 'Don't bite off more than you can chew' is often used to advise people against agreeing to more than they can handle.",
    "If you bite someone's head off, you criticize them angrily.",
    "If you have to bite the bullet, you have to accept or face something unpleasant because it cannot be avoided.",
    "This is a way of saying that somebody has died, especially if they are killed violently like a soldier in battle.",
    "If you have to bite your lip, you have to make a conscious effort not to react or to keep quiet about something that displeases you.",
    "If you bite your tongue, you refrain from speaking because it is socially or otherwise better not to.",
    "Bits and bobs are small, remnant articles and things- the same as 'odds and ends'.",
    "If you do something to the bitter end, you do it to the very end, no matter how unsuccessful you are.",
    "A bitter pill to swallow is something that is hard to accept.",
    "This means bruised, either physically or metaphorically.",
    "When it is very clear who or what is right and wrong, then the situation is black and white.",
    "(UK) If things are as black as New Gate's knocker, they are very bad. New Gate was an infamous prison in England, so its door knocker meant trouble.",
    "If there is a black hole in financial accounts, money has disappeared.",
    "Someone who is the black sheep doesn't fit into a group or family because their behavior or character is not good enough.",
    "If you vote against allowing someone to be a member of an organization or group, you are blackballing him or her.",
    "If you are given a blank cheque, you are allowed to use as much money as you need for a project.",
    "A bleeding heart is a person who is excessively sympathetic towards other people.",
    "This expression is used as to patronize someone, especially when they don't realize that they're not very clever. ('Bless your pointes little head' is also used)",
    "If some bad luck or misfortune ultimately results in something positive, it's a blessing in disguise.",
    "If people accept thing blindly, they accept them without questioning them at all.",
    "If you are in total darkness and can't see anything at all, you are as blind as a bat.",
    "When the blind are leading the blind, the people in charge of something don't know anything more than the people they are in charge of, when they should have greater knowledge.",
    "If you are blind-sided, an event with a negative impact takes you completely by surprise.",
    "If something happens in the blink of an eye, it happens so fast it is almost impossible to notice it.",
    "An emotional speech or performance is full of blood and thunder.",
    "It is impossible to get something from someone if they don't have it, just as you cannot get blood from a turnip.",
    "This idiom means that family relationships are stronger than others.",
    "(AU) If an Australian says to you 'Your blood is worth bottling', he/she is complimenting or praising you for doing something or being someone very special.",
    "If something is like getting blood out of a stone, it is very difficult indeed.",
    "If something will take blood, sweat and tears, it will be very difficult and will require a lot of effort and sacrifice.",
    "If you blow a gasket, you get very angry.",
    "A blow-by-blow description gives every detail in sequence.",
    "If you blow hot and cold on an idea, your attitude and opinion keeps changing; one minute you are for it, the next you are against.",
    "People say '(well,) blow me down' when you have just told them something surprising, shocking or unexpected. ('Blow me down with a feather' is also used) ",
    "(USA) If you blow off steam, you express your anger or frustration.",
    "If something, like an idea, is blown out of the water, it is destroyed or defeated comprehensively.",
    "(USA) If people blow smoke, they exaggerate or say things that are not true, usually to make themselves look better.",
    "If you blow the cobwebs away, you make sweeping changes to something to bring fresh views and ideas in.",
    "If somebody blows the whistle on a plan, they report it to the authorities.",
    "something that will blow your mind is something extraordinary that will amaze you beyond explanation.",
    "If you blow your own horn, you boast about your achievements and abilities. ('Blow your own trumpet' is an alternative form)",
    "If someone blows their own trumpet, they boast about their talents and achievements.  ('Blow your own horn' is an alternative form)",
    "If you blow your stack, you lose your temper.",
    "If someone blows their top, they lose their temper.",
    "someone with blue blood is royalty.",
    "Someone's blue-eyed boy is their favorite person.",
    "(UK) This idiom means that something will be successful: Just tell him that I gave you his name and Bob's your uncle- he'll help you.",
    "A group of people organized under a single government or authority (national or regional) is a body politi.",
    "Someone who is as bold as brass is very confident and not worried about how other people will respond or about being caught.",
    "If something happens unexpectedly and suddenly, it is a bolt from the blue.",
    "If there is an issue that always causes tension and arguments, it is a bone of contention.",
    "If you have a bone to pick with someone, you are annoyed about something they have done and want to tell them how you feel.",
    "When the boot's on the other foot, a person who was in a position of weakness is now in a position of strength.",
    "Someone who is born to the purple is born in a royal or aristocratic family. ('Born in the purple' is also used)",
    "If you are born with a silver spoon in your mouth, you are born into a rich family.",
    "If you make both ends meet, you live off the money you earn and don't go into debt.",
    "In accountancy, the bottom line is net income, and is used idiomatically to mean the conclusion.",
    "If you bounce ideas off someone, you share your ideas with them to know whether they think they would work.",
    "If someone's bouncing off the walls, they are very excited about something.",
    "Id someone deserves a bouquet of orchids, they have done something worthy of praise.",
    "Box and dice means everything.",
    "(UK) If you box clever, you use your intelligence to get what you want, even if you have to cheat a bit.",
    "If people are boxing and coxing, they are sharing responsibilities so that one of them is working while the other isn't. It can also be used when couples are sharing a house, but their relationship has broken down and when one is at home, the other stays out.",
    "The boys in blue are the police.",
    "If something is not brain surgery, it isn't very complicated or difficult to understand or master.",
    "(UK) Someone who has the brass neck to do something has no sense of shame about what they do.",
    "If you get down to brass tacks, you get down to the real business.",
    "Bread and butter issues are ones that affect people directly and in a very important way.",
    "Used to describe the person that earns the most money. For example - She's the breadwinner in the family.",
    "This idiom is a way of wishing someone good luck.",
    "If you break even, you don't make any money, but you don't lose any either.",
    "If you break ground, or break new ground, you make progress, taking things into a new area or going further than anyone has gone before. 'Ground-breaking' is used an adjective.",
    "If you break the back of the beast, you accomplish a challenge.",
    "When you break the ice, you get over any initial embarrassment or shyness when you meet someone for the first time and start conversing.",
    "(UK) If you break your duck, you do something for the first time.",
    "If someone upsets you greatly, they break your heart, especially if they end a relationship.",
    "If someone follows you or examines what you're doing very closely, they are breathing down your neck.",
    "If you breathe life into something, you give people involved more energy and enthusiasm again.  ('Breathe new life' is also used)",
    "When you breathe your last, you die.",
    "If you bridge the gap, you make a connection where there is a great difference.",
    "When someone is cheerful and full of energy, they are bright and breezy.",
    "A person who is as bright as a button is very intelligent or smart.",
    "If someone's bright-eyed and bushy-tailed, they are full of energy and enthusiasm.",
    "If something brightens up your day, something happens that makes you feel positive and happy all day long.",
    "If someone brings a knife to a gunfight, they are very badly prepared for something.",
    "A person who brings home the bacon earns the money that a family live on.",
    "To make people embrace the ideas intended by the leader or agree to join a team or project is to bring them on board.",
    "If somebody is brought to book, they are punished or made to account for something they have done wrong.",
    "If you bring someone to heel, you make them obey you.('Call someone to heel' is also used)",
    "Something that brings the house down is acclaimed and praised vigorously.",
    "If you bring something to the table, you make a contribution or an offer in a discussion or negotiation.",
    "If an organization is described as broad church, it is tolerant and accepting of different opinions and ideas.",
    "If something is described or defined with broad stokes, then only an outline is given, without fine details.",
    "it's not funny to be without a cent and just uses broke and joke as rhyming words that help explain this idiom a lot better.",
    "When someone sounds like a broken record, they keep on repeating the same things. ('Stuck record' is also used)",
    "If something or someone fails to give you the support you were hoping for, they are a broken reed.",
    "When someone tries to make themselves popular with somebody, usually in a position of authority, especially by flattering them, they are brown nosing.",
    "To be tired of or fed up with.",
    "If you try to earn Brownie points with someone, you do things you know will please them.",
    "If you brush something under the carpet, you are making an attempt to ignore it, or hide it from others.",
    "(UK) If it Buggles' turn, someone gets promotion through length of service rather than ability, especially in the British civil service.",
    "If someone behaves like a bull in a China shop, they are clumsy when they should be careful.",
    "A bull market is a period when investors are optimistic and there are expectations that good financial results will continue.",
    "If you have a bull session, you have an informal group discussion about something.",
    "If you're a bull-headed, you're stubborn or inflexible.",
    "The people who have paid to watch a performance are bums on seats.",
    "If a woman has a bun in the oven, she is pregnant.",
    "Someone who is a bundle of nerves is very worried or nervous.",
    "A bur under your saddle is something that annoys you or spurs you into action.('Burr' is an alternative spelling)",
    "If you burn rubber, you drive very fast to get somewhere.",
    "Someone who burns the candle at both ends lives life at a hectic pace, doing things which are likely to affect their health badly.",
    "If you stay up very late working or studying, you burn the midnight oil.",
    "If you burn your bridges, you do something that makes it impossible to go back from the position you have taken.",
    "If you burn your fingers, you suffer a loss or something unpleasant as the result of something you did, making you less likely to do it again.",
    "A burning question is something we all want to know about.",
    "To be filled to or beyond normal capacity: This room will be bursting at the seams when all the guests arrive.",
    "If you correct someone's ignorant or delusional belief, you burst their bubble. (Bust someone's bubble is also used)",
    "If you bury the hatchet, you make peace with someone and stop arguing or fighting.",
    "If someone buries their head in the sand, they ignore something that is obviously wrong.",
    "A busman's holiday is when you spend your free time doing the same sort of work as you do in your job.",
    "When someone says that they're not going to bust their chops, it means they are not going to work that hard or make much effort.",
    "Someone or something that had great potential but ended up a useless failure is a busted flush.",
    "If you're as busy as a beaver, you're very busy indeed.",
    "If you are as busy as a bee, you are very busy indeed.",
    "If someone is butt naked, they have no clothes on at all, often when they can be seen.",
    "If something or someone becomes the butt of a joke it or they are not taken seriously anymore.",
    "If someone looks as if butter wouldn't melt in their mouth, they look very innocent.",
    "Someone who has butterfingers is clumsy and drops things.",
    "The nervous feeling before something important or stressful is known as butterflies in your stomach.",
    "If you button your lip, you keep quiet and don't speak. It is also used as a way of telling someone to shut up.",
    "When somebody has bought the farm, they have died.",
    "If a person escapes from some danger by a hair's breadth, they only just managed to avoid it. The breadth is the thickness of a hair, so they probably feel somewhat lucky because the margin between success and what could easily have been failure was so close.",
    "(UK) If you beat somebody by a long chalk, you win easily and comfortably.",
    "If you do something by a whisker, you only just manage to do it and come very near indeed to failing.",
    "By and large means usually or generally.",
    "This means 'as a result of' or 'because of': It would be good to think he'd risen to position of Chief Executive by dint of hard work.",
    "If you learn something by heart, you learn it word for word.",
    "If you are prepared to do something by hook or by crook, you are willing to do anything, good or bad, to reach your goal.",
    "Something that happens by leaps and bounds happens very quickly in big steps.",
    "If something is started or introduced by the back door, then it is not done openly or by following the proper procedures.",
    "If you do something by the book, you do it exactly as you are supposed to.",
    "This is used as a way of introducing an incidental topic in a conversation or to say that something is irrelevant. ('By the bye' is also used)",
    "If something is done by the numbers, it is done in a mechanical manner without room for creativity.",
    "If someone applies the same rule to different situations, they judge them by the same token.",
    "If you do something by the seat of your pants, you achieve something, but only by a narrow margin or do something without advance preparation.",
    "If you do something by the skin of your teeth, you only just manage to do it and come very near indeed to failing.",
    "If something becomes known by word of mouth, it gets known by being talked about rather than through publicity or advertising, etc.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'B',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
