import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class C extends StatelessWidget {
  final List _name = [
    "Cake's not worth the candle",
    "Call a spade a spade",
    "Call it a day",
    "Call on the carpet",
    "Call the dogs off",
    "Call the shots",
    "Call the tune",
    "Calm before the storm",
    "Can of worms",
    "Can't dance and it's too wet to plow",
    "Can't do it for toffee",
    "Can't get a word in edgeways",
    "Can't hack it",
    "Can't hold a candle",
    "Can't see the forest for its trees",
    "Canary in a coal mine",
    "Card up your sleeve",
    "Carrot and stick",
    "Carry the can",
    "Carry the day",
    "Case by case",
    "Case in point",
    "Cash cow",
    "Cash in your chips",
    "Cast a long shadow",
    "Cast aspersion",
    "Cast doubt on",
    "Cast iron stomach",
    "Cast pearls before swine",
    "Cast sheep's eyes at",
    "Cast your mind back",
    "Cast your net widely",
    "Castles in the air",
    "Cat among the pigeons",
    "Cat and dog life",
    "Cat burglar",
    "Cat got your tongue?",
    "Cat nap",
    "Cat's lick",
    "Cat's pajamas",
    "Cat's whiskers",
    "Catch as catch can",
    "Catch hell",
    "Catch some z's",
    "Catch someone red-handed",
    "Caught with your hand in the cookie jar",
    "Chalk and cheese",
    "Champ at the bit",
    "Champagne taste on a beer budget",
    "Change horses in midstream",
    "Change of heart",
    "Change tack",
    "Change your tune",
    "Chapter and verse",
    "Charity begins at home",
    "Chase rainbows",
    "Chase your tail",
    "Cheap as chips",
    "Cheap at half the price",
    "Cheap shot",
    "Cheat death",
    "Cheek by jowl",
    "Cherry pick",
    "Chew on a bone",
    "Chew the cud",
    "Chew the fat",
    "Chickenfeed",
    "Child's play",
    "Chinese whispers",
    "Chip off the old block",
    "Chip on your shoulder",
    "Chop and change",
    "Cigarette paper",
    "Circle the wagons",
    "Circling the drain",
    "Class act",
    "Clean as a whistle",
    "Clean bill of health",
    "Clean break",
    "Clean hands",
    "Clean sheet",
    "Clean slate",
    "Clean sweep",
    "Clean your clock",
    "Clear as a bell",
    "Clear as mud",
    "Cliffhanger",
    "Climb on the bandwagon",
    "Climb the greasy pole",
    "Cling to hope",
    "Close at hand",
    "Close but no cigar",
    "Close call",
    "Close shave",
    "Close the stable door after the horse has bolted",
    "Close to your heart",
    "Closed book to me",
    "Cloth ears",
    "Cloud cuckoo land",
    "Cloud nine",
    "Cloud of suspicion",
    "Cloud on the horizon",
    "Clutch at straws",
    "Clutch play",
    "Coals to Newcastle",
    "Coast is clear",
    "Cock and bull story",
    "Cock in the henhouse",
    "Cock of the walk",
    "Cold day in hell",
    "Cold feet",
    "Cold fish",
    "Cold light of day",
    "Cold shoulder",
    "Cold sweat",
    "Cold turkey",
    "Colder than a witches tit",
    "Collateral damage",
    "Collect dust",
    "Color bar",
    "Come a cropper",
    "Come clean",
    "Come hell or high water",
    "Come of age",
    "Come on hard",
    "Come out in the wash",
    "Come out of the woodwork",
    "Come out of your shell",
    "Come rain or shine",
    "Come to a head",
    "Come to bear",
    "Come to call",
    "Come to grips",
    "Come to heel",
    "Come up roses",
    "Come up smelling of roses",
    "Come up trumps",
    "Come what may",
    "Come with the territory",
    "Comfort zone",
    "Connect the dots",
    "Constitution of an ox",
    "Cook someone's goose",
    "Cook the books",
    "Cooking with gas",
    "Cool as a cat",
    "Cool your heels",
    "Coon's age",
    "Corner a market",
    "Couch potato",
    "Could eat a horse",
    "Count your blessings",
    "Country mile",
    "Cover all the bases",
    "Crack a nut with a sledgehammer",
    "Crack of dawn",
    "Crash a party",
    "Cream of the crop",
    "Cream rises to the top",
    "Creature comforts",
    "Crème de la crème",
    "Crepe hanger",
    "Crocodile tears",
    "Crooked as a dog's hind leg",
    "Cross swords",
    "Cross that bridge when you come to it",
    "Cross to bear",
    "Crossing the Rubicon",
    "Crunch time",
    "Cry wolf",
    "Cry your eyes out",
    "Cry-baby",
    "Cuckoo in the nest",
    "Cupboard love",
    "Curiosity killed the cat",
    "Curry favor",
    "Curve ball",
    "Cut a long story short",
    "Cut a rug",
    "Cut above",
    "Cut and dried",
    "Cut and run",
    "Cut it fine",
    "Cut off your nose to spite your face",
    "Cut someone some slack",
    "Cut the Gordian knot",
    "Cut to the chase",
    "Cut to the quick",
    "Cut your coat according to your cloth",
    "Cut your losses",
    "Cut your teeth on",
    "Cute as a bug",
    "Cuts no ice",
    "Cutting edge",
  ];
  final List _nameDescription = [
    "If someone says that the cake's not worth the candle, they mean that the result will not be worth the effort put in to achieve it.",
    "A person who calls a spade a spade is one speaks frankly and makes little or no attempt to conceal their opinions or to spare the feelings of their audience.",
    "If you call it a day, you stop doing something for a while, normally at least until the following day.",
    "If you are called on the carpet, you are summoned for a reprimand by superiors or others in power.",
    "If someone calls off their dogs, they stop attacking or criticizing someone.",
    "If you call the shots, you are in charge and tell people what to do.",
    "The person who calls the tune makes the important decisions about something.",
    "A calm time immediately before period of violent activity or argument is the calm before the storm.",
    "If an action can create serious problems, it is opening a can of worms.",
    "(USA) When you can't dance and it's too wet to plow, you may as well do something because you can't or don't have the opportunity to do anything else.",
    "If you can't so something for toffee, you are incapable of doing something properly or to any sort of standard.",
    "If you can't get a word in edgeways, you don't have the chance to say anything because the person you are with is talking all the time.",
    "unable to perform an act, duty, job etc. (example: I have to quit my job as a computer technician; I just can't hack it)",
    "If something can't hold a candle to something else, it is much worse.",
    "If someone can't see the forest for its trees, they are too focused on specific details to see the picture as a whole.",
    "(UK) A canary in a coal mine is an early warning of danger.",
    "If you card up your sleeve, you have a surprise plan or idea that you are keeping back until the time is right.",
    "If someone offers a carrot and stick, they offer an incentive to do something combined with the threat of punishment.",
    "If you carry the can, you take the blame for something, even though you didn't do it or are only partly at fault.",
    "If something carries the day, it wins a battle or competition for supremacy.",
    "If things are done case by case, each situation or issue is handled separately on its own merits and demerits.",
    "Meaning an instance of something has just occurred that was previously discussed. For instance, a person may have told another that something always happens. Later that day, they see it happening, and the informer might say, 'case in point'.",
    "A product, business, etc, that generates a continuous flow of money or a high proportion of overall profits is a cash cow.",
    "If you cash in your chips, you sell something to get what profit you can because you think its value is going to fall. It can also mean 'to die'.",
    "Something or someone that casts a long shadow has considerable influence on other people or events.",
    "If you cast aspersion, you try to blacken someone's name and make people think badly of them.",
    "If you make other people not sure about a matter, then you have cast doubt on it.",
    "A person with a cast iron stomach can eat or drink anything without any ill effects.",
    "If you cast pearls before swine, you offer something of value to someone who doesn't appreciate it- 'swine' are 'pigs'.",
    "If you cast sheep's eyes at someone, you look lovingly or with longing at them.",
    "If somebody tells you to cast your mind back on something, they want you to think about something that happened in the past, but which you might not remember very well, and to try to remember as much as possible.",
    "If you cast your net widely, you use a wide range of sources when trying to find something.",
    "Plans that are impractical and will never work out are castles in the air.",
    "If something or someone puts, or sets or lets, the cat among the pigeons, they create a disturbance and cause trouble.",
    "If people lead a cat and dog life, they are always arguing.",
    "A cat burglar is a skillful thief who breaks into places without disturbing people or setting off alarms.",
    "If someone asks if the cat has got your tongue, they want to know why you are not speaking when they think you should.",
    "If you have a short sleep during the day, you are cat napping.",
    "(Scot) A cat's lick is a very quick wash.",
    "(USA) Something that is the cat's pajamas is excellent.",
    "Something excellent is the cat's whiskers.",
    "This means that people should try to get something any way they can.",
    "If you catch hell, you get into trouble or get scolded. ('Catch heck' is also used)",
    "If you catch some z's, you get some sleep.",
    "If someone is caught red-handed, they are found doing something wrong or illegal.",
    "(USA) If someone is caught with his or her hand in the cookie jar, he or she is caught doing something wrong.",
    "Things, or people, that are like chalk and cheese are very different and have nothing in common.",
    "If someone is champing at the bit, they are very eager to accomplish something.  ('Chomping at the bit' is also used)",
    "Someone who lives above their means and likes things they cannot afford has champagne taste on a beer budget.",
    "If people change horses in midstream, they change plans or leaders when they are in the middle of something, even though it may be very risky to do so.",
    "If you change the way you think or feel about something, you have a change of heart.",
    "If you change tack, you use a different method for dealing with something.",
    "If someone changes their ideas or the way they talk about them, they change their tune.",
    "When you know something very well, and can quote it, you know it chapter and verse.",
    "This idiom means that family members are more important than anyone else, and should be the focus of a person's efforts.",
    "If someone chases rainbows, they try to do something that they will never achieve.",
    "If you are chasing your tail, you are very busy but not being very productive.",
    "(UK) If something is very inexpensive, it is as cheap as chips.",
    "If something's cheap at half the price, it's very cheap indeed.",
    "A cheap shot is an unprincipled criticism.",
    "If someone cheats death, they narrowly avoid a major problem or accident.",
    "If things or people are cheek by jowl, they are very close together.",
    "If people cherry pick, they choose things that support their position, while ignoring things that contradict it.",
    "If someone is chewing on a bone, he or she is thinking about something intently.",
    "If you chew the cud, you think carefully about something.",
    "If you chew the fat with someone, you talk at leisure with them.",
    "If something is small or unimportant, especially money, it is chickenfeed.",
    "If something is child's play, it is very easy and simple.",
    "(UK) When a story is told from person to person, especially if it is gossip or scandal, it inevitably gets distorted and exaggerated. This process is called Chinese whispers.",
    "If someone is a chip off the old block, they closely resemble one or both of the parents in character.",
    "If someone has a chip on their shoulder, they are resentful about something and feel that they have been treated badly.",
    "If things chop and change, they keep changing, often unexpectedly.",
    "If you cannot get or put a cigarette paper between people, they are so closely bonded that nothing will separate them or their positions on issues.",
    "(USA) If you circle the wagons, you stop communicating with people who don't think the same way as you to avoid their ideas.  It can also mean to bring everyone together to defend a group against an attack.",
    "If someone is circling the drain, they are very near death and have little time to live. The phrase can also describe a project or plan or campaign that that is on the brink of failure.",
    "Someone who's a class act is exceptional in what they do.",
    "If something is as clean as a whistle, it is extremely clean, spotless. It can also be used to mean completely.",
    "If something or someone has a clean bill of health, then there's nothing wrong; everything's fine.",
    "If you make a clean break, you break away completely from something.",
    "Someone with clean hands, or who keeps their hands clean, is not involved in illegal or immoral activities.",
    "When someone has a clean sheet, they have got no criminal record or problems affecting their reputation. In football and other sports, a goalkeeper has a clean sheet when let no goals in.",
    "If you start something with a clean slate, then nothing bad from your past is taken into account.",
    "If someone makes a clean sweep, they win absolutely everything in a competition or contest.",
    "If you clean your clock, you beat someone decisively in a contest or fight.",
    "If something is as clear as a bell, it is very clear or easy to understand.",
    "If something is as clear as mud, then it is very confusing and unclear.",
    "If something like a sports match or an election is a cliffhanger, then the result is so close that it cannot be predicted and will only be known at the very end.",
    "When people climb on the bandwagon they do something because it is popular and everyone else is doing it.",
    "Advance within an organization - especially in politics.",
    "If people cling to hope, they continue to hope though the chances of success are very small.",
    "If something is close at hand, it is nearby or conveniently located.",
    "(USA) If you are close but no cigar, you are close to success, but have not got there.",
    "If the result of something is a close call, it is almost impossible to distinguish between the parties involved and to say who has won or whatever.  It can also mean that you very nearly have a serious accident or get into trouble.",
    "If you have a close shave, you very nearly have a serious accident or get into trouble.",
    "If people try to fix something after the problem has occurred, they are trying to close the stable door after the horse has bolted. 'Close the barn door after the horse has bolted' is alternative, often used in American English.",
    "If something is close to your heart, you care a lot about it. ('Dear to your heart' is an alternative)",
    "If a subject is a closed book to you, it is something that you don't understand or know anything about.",
    "If you don't listen to people, they may suggest you have cloth ears.",
    "If someone has ideas or plans that are completely unrealistic, they are living on cloud cuckoo land.",
    "If you are on cloud nine, you are extremely happy. ('cloud seven' is a less common alternative)",
    "If a cloud of suspicion hangs over an individual, it means that they are not believed or are distrusted.",
    "If you can see a problem ahead, you can call it a cloud on the horizon.",
    "If someone is in serious trouble and tries anything to help them, even though their chances of success are probably nil, they are clutching at straws.",
    "If an activity is referred to as a clutch play, it means that the activity was the key to the success or failure of the venture.",
    "(UK) Taking, bringing, or carrying coals to Newcastle is doing something that is completely unnecessary.",
    "When the coast is clear, the people supposed to be watching you are not there and you are able to move or leave.",
    "A cock and bull story is a lie someone tells that is completely unbelievable.",
    "This is used to describe a male in an all-female environment.",
    "A man who is excessively confident and thinks he's better than other people is the cock of the walk.",
    "This is used as a prediction there is no chance some event or condition will ever happen. 'There will be a cold day in hell before he manages it'",
    "If you get cold feet about something, you lose the courage to do it.",
    "A cold fish is a person who doesn't show how they feel.",
    "If you see things in the cold light of day, you see them as they really are, not as you might want them to be.",
    "If you give or show someone the cold shoulder, you are deliberately unfriendly and unco-operative towards them.",
    "If something brings you out in a cold sweat, it frightens you a lot.",
    "If someone suddenly stops taking drugs, instead of slowly cutting down, they do cold turkey.",
    "If it is colder than a witches tit, it is extremely cold outside.",
    "Accidental or unintended damage or casualties are collateral damage.",
    "If something is collecting dust, it isn't being used any more.",
    "Rules that restrict access on the basis of race or ethnicity are a color bar.",
    "(UK) Someone whose actions or lifestyle will inevitably result in trouble is going to come a cropper.",
    "If someone comes clean about something, they admit to deceit or wrongdoing.",
    "If someone says they'll do something come hell or high water, they mean that nothing will stop them, no matter what happens.",
    "When something comes of age it develops completely and reaches maturity. When someone comes of age, they reach adulthood or fulfill their potential.",
    "If you come on hard, you are aggressive in your dealing with someone.",
    "If something will come out in the wash, it won't have any permanent negative effect.",
    "When things come out of the woodwork, they appear unexpectedly.  ('Crawl out of the woodwork' is also used)",
    "If someone comes out of their shell, they stop being shy and withdrawn and become more friendly and sociable.",
    "If I say I'll be at a place come rain or shine, I mean nothing will deter me or stop me from being there.",
    "If events reach a crisis point, they come to a head.",
    "If something comes to bear on you, you start to feel the pressure or effect of it.",
    "If someone comes to call, they respond to an order or summons directly.",
    "If you come to grips with a problem or issue, you face up to it and deal with it.",
    "If someone comes to heel, they stop behaving in a way that is annoying to someone in authority and start being obedient.",
    "If things come up roses, they produce a positive result, especially when things seemed to be going badly at first.",
    "(UK) If someone comes up smelling of roses, they emerge from a situation with their reputation undamaged.",
    "When someone is said to have 'come up trumps', they have completed an activity successfully or produced a good result, especially when they were not expected to.",
    "If you're prepared to do something come what may, it means that nothing will stop or distract you, no matter how hard or difficult it becomes.",
    "If something comes with the territory, it is part of a job or responsibility and just has to be accepted, even if unpleasant.",
    "It is the temperature range in which the body doesn't shiver or sweat, but has an idiomatic sense of a place where people feel comfortable, where they can avoid the worries of the world. It can be physical or mental.",
    "When you connect the dots, you understand the connections and relationships.",
    "If someone has the constitution of an ox, they are less affected than most people by things like tiredness, illness, alcohol, etc.",
    "If you cook someone's goose, you ruin their plans.",
    "If people cook the books, they keep false accounts to make money illegally or avoid paying tax.",
    "(USA) If you're cooking with gas, you're working very efficiently.",
    "To act fine when you a actually scared or nervous.",
    "If you leave someone to cool their heels, you make them wait until they have calmed down.",
    "(USA) A very long time, as in 'I haven't seen her in a coon's age!'",
    "If a business is dominant in an area and unlikely to be challenged by other companies, it has cornered the market.",
    "A couch potato is an extremely idle or lazy person who chooses to spend most of their leisure time horizontal in front of the TV and eats a diet that is mainly junk food.",
    "If you are very hungry, you could eat a horse.",
    "When people count their blessings, they concentrate on all the good things in their lives instead of the negative ones.",
    "(USA) A country mile is used to describe a long distance.",
    "If you cover all the bases, you deal with all aspects of a situation or issue, or anticipate all possibilities. ('Cover all bases' is also used)",
    "If you use a sledgehammer to crack a nut, you apply too much force to achieve a result. ('Jackhammer' is also used)",
    "The crack of dawn is very early in the morning.",
    "If you crash a party, or are a gatecrasher, you go somewhere you haven't been invited to.",
    "The cream of the crop is the best there is.",
    "A good person or idea cannot go unnoticed for long, just as cream poured in coffee or tea eventually rises to the top.",
    "If a person said 'I hate camping. I don't like giving up my creature comforts.' the person would be referring, in particular, to the comfortable things he/she would have at home but not when camping. At home, for example, he/she would have complete shelter from the weather, a television, a nice comfortable warm bed, the ability to take a warm bath or shower, comfortable lounge chairs to relax in and so on. The person doesn't like giving up the material and psychological benefits of his/her normal life.",
    "The crème de la crème is the very best of something.",
    "(USA) One who always looks at the bad side of things and is morbid or gloomy. In olden days crepe was hung on the door of a deceased person's home.",
    "If someone cries crocodile tears, they pretend to be upset or affected by something.",
    "Someone who is very dishonest is as crooked as a dog's hind leg.",
    "When people cross swords, they argue or dispute.",
    "If you will cross that bridge when you come to it, you will deal with a problem when it arises, but not until that point.",
    "If someone has a cross to bear, they have a heavy burden of responsibility or a problem that they alone must cope with.",
    "When you are crossing the Rubicon, you are passing a point of no return. After you do this thing, there is no way of turning around. The only way left is forward.",
    "When people, companies, etc, have to make an important decision that will have a considerable effect on their future, it is crunch time.",
    "If someone cries wolf, they raise a false alarm about something.",
    "If you cry your eyes out, you cry uncontrollably.",
    "A cry-baby is a person who gets emotional and cries too easily.",
    "Is an issue or a problem, etc, is a cuckoo in the nest, it grows quickly and crowds out everything else.",
    "(UK) To show love to gain something from someone.",
    "As cats are naturally curious animals, we use this expression to suggest to people that excessive curiosity is not necessarily a good thing, especially where it is not their business.",
    "If people try to curry favor, they try to get people to support them. ('Curry favor' is the American spelling)",
    "(USA) If something is a curve ball, it is deceptive.",
    "This idiom is used as a way of shortening a story by getting to the end or the point.",
    "To cut a rug is to dance.",
    "If a person is described as a cut above other people, they are better in some way.",
    "If something is cut and dried, then everything has already been decided and, in the case of an opinion, might be a little stale and predictable.",
    "If people cut and run, they take what they can get and leave before they lose everything.",
    "If you cut it fine, you only just manage to do something- at the very last moment. 'Cut things fine' is the same. 'Cut it a bit fine' is a common variation.",
    "If you cut off your nose to spite your face, you do something rash or silly that ends up making things worse for you, often because you are angry or upset.",
    "To relax a rule or make an allowance, as in allowing someone more time to finish something.",
    "If someone cuts the Gordian knot, they solve a very complex problem in a simple way.",
    "If you cut to the chase, you get to the point, or the most interesting or important part of something without delay.",
    "If someone's cut to the quick by something, they are very hurt and upset indeed.",
    "If you cut your coat according to your cloth, you only buy things that you have sufficient money to pay for.",
    "If you cut your losses, you avoid losing any more money than you already have by getting out of a situation before matters worsen.",
    "the place where you gain your early experience is where you cut your teeth.",
    "(USA) If something is as cute as a bug, it is sweet and endearing.",
    "If something cuts no ice, it doesn't have any effect or influence.",
    "Something that is cutting edge is at the forefront of progress in its area.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'C',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
