import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class E extends StatelessWidget {
  final List _name = [
    "Each to their own",
    "Eager beaver",
    "Eagle eyes",
    "Early bath",
    "Early bird catches the worm",
    "Early to bed, early to rise, makes a man healthy wealthy and wise",
    "Earn a living",
    "Easier said than done",
    "Easy as ABC",
    "Easy as beans",
    "Easy as pie",
    "Easy come, easy go",
    "Easy peasy",
    "Eat crow",
    "Eat humble pie",
    "Eat like a bird",
    "Eat like a horse",
    "Eat like a pig",
    "Eat my hat",
    "Eat someone alive",
    "Eat your heart out",
    "Eat your words",
    "Economical with the truth",
    "Egg on your face",
    "Elbow grease",
    "Elbow room",
    "Elephant in the room",
    "Eleventh hour",
    "Empty vessels make the most noise",
    "End in smoke",
    "Etched in stone",
    "Even a blind squirrel finds a nut once in a while",
    "Even a broken clock is right twice a day",
    "Even keel",
    "Even the dogs in the street know",
    "Every ass likes to hear himself bray",
    "Every cloud has a silver lining",
    "Every dog has its day",
    "Every man and his dog",
    "Every man for himself",
    "Every man has his price",
    "Every man jack",
    "Every nook and cranny",
    "Every Tom, Dick and Harry",
    "Every trick in the book",
    "Everybody and their uncle",
    "Everything but the kitchen sink",
    "Explore all avenues",
    "Eye candy",
    "Eye for an eye",
    "Eye-opener",
    "Eyes are bigger than one's stomach",
  ];
  final List _nameDescription = [
    "Different people have different preferences. In American English, 'Each to his own' is more common.",
    "A person who is extremely keen is an eager beaver.",
    "someone who has eagle eyes sees everything.",
    "(UK) If someone has or goes for an early bath, they quit or lose their job or position earlier than expected because things have gone wrong.",
    "The early bird catches the worm means that if you start something early, you stand a better chance of success.",
    "It means that sleeping well and not staying up late will help you out physically and financially.",
    "To make money Ex: We need to get a good job to earn a decent living.",
    "If something is easier said than done, it is much more difficult than it sounds. It is often used when someone advises you to do something difficult and tries to make it sound easy.",
    "Something that is as easy as ABC is very easy or simple.",
    "Something that is so easy that anyone can do it is easy as beans.",
    "If something is easy as pie, it is very easy indeed.",
    "This idiom means that money or other material gains that come without much effort tend to get spent or consumed as easily.",
    "(UK) If something is easy peasy, it is very easy indeed. ('Easy peasy, lemon squeezy' is also used)",
    "(USA) If you eat crow, you have to admit that you were wrong about something.",
    "If someone apologizes and shows a lot of contrition for something they have done, they eat humble pie.",
    "If someone eats like a bird, they eat very little.",
    "Someone who eats like a horse, eats a lot.",
    "If some eats like a pig, they either eat too much or they have bad table manners.",
    "People say this when they don't believe that something is going to happen e.g. 'If he passes that exam, I'll eat my hat!'",
    "If you eat someone alive, you defeat or beat them comprehensively.",
    "If someone tells you to eat your heart out, they are saying they are better than you at something.",
    "If you eat your words, you accept publicly that you were wrong about something you said.",
    "(UK) If someone, especially a politician, is economical with the truth, they leave out information in order to create a false picture of a situation, without actually lying.",
    "If someone has egg on their face, they are made to look foolish or embarrassed.",
    "If something requires elbow grease, it involves a lot of hard physical work.",
    "If you haven't got enough elbow room, you haven't got enough space.",
    "An elephant in the room is a problem that everyone knows very well but no one talks about because it is taboo, embarrassing, etc.",
    "If something happens at the eleventh hour, it happens right at the last minute.",
    "The thoughtless often speak the most.",
    "If something ends in smoke, it produces no concrete or positive result.",
    "Something, especially rules and customs,  that cannot be changed at all is said to be etched in stone.",
    "This expression means that even if people are ineffective or misguided, sometimes they can still be correct just by being lucky.",
    "This is used when people get lucky and are undeservedly successful.('Even a stopped clock is right twice a day' is also used)",
    "If something is on an even keel, it is balanced.",
    "(Irish) This idiom is used frequently in Ireland, and means something is so obvious that even the dogs in the street know it.",
    "This means that people like the sound of their own voice.",
    "People sometimes say that every cloud has a silver lining to comfort somebody who's having problems. They mean that it is always possible to get something positive out of a situation, no matter how unpleasant, difficult or even painful it might seem.",
    "This idiom means that everyone gets their moment to shine.",
    "A lot of people - as in sending out invitations to a large number of people.",
    "If it's every man for himself, then people are trying to save themselves from a difficult situation without trying to help anyone else.",
    "Anyone's opinion or support can be bought, everyone's principles have a limit.",
    "If every man jack was involved in something, it is an emphatic way of saying that absolutely everybody was involved.",
    "If you search every nook and cranny, you look everywhere for something.",
    "If every Tom, Dick and Harry knows about something, then it is common knowledge.",
    "If you try every trick in the book, you try every possible way, including dishonesty and deceit, to get what you want.",
    "This basically means a lot of people or too many people; everybody and their uncle was there.",
    "If people include everything but the kitchen sink, they include every possibility, regardless of whether they are useful.",
    "If all avenues are being explored, then every conceivable approach is being tried that could possibly get the desired result.",
    "When a person is very attractive, they can be described as eye candy - sweet to look at!",
    "This is an expression for retributive justice, where the punishment equals the crime.",
    "Something surprising, unexpected which reveals the truth about something or someone.",
    "If someone's eyes are bigger than their stomach, they are greedy and take on more than they can consume or manage.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'E',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
