import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class F extends StatelessWidget {
  final List _name = [
    "Face like thunder",
    "Face only a mother could love",
    "Face the music",
    "Face value",
    "Face your demons",
    "Facts of life",
    "Failure is the mother of success",
    "Faint heart never won fair lady",
    "Fair and square",
    "Fair crack of the whip",
    "Fair shake of the whip",
    "Fair thee well",
    "Fair-weather friend",
    "Fall by the wayside",
    "Fall from grace",
    "Fall off the back of a lorry",
    "Fall off the wagon",
    "Fall on our feet",
    "Fall on your sword",
    "Familiarity breeds contempt",
    "Famous last words",
    "Fast and furious",
    "Fat cat",
    "Fat chance!",
    "Fat head",
    "Fat hits the fire",
    "Fat of the land",
    "Fate worse than death",
    "Feast today, famine tomorrow",
    "Feather in your cap",
    "Feather your own nest",
    "Feathers fly",
    "Fed up to the back teeth",
    "Feel at home",
    "Feel free",
    "Feel like a million",
    "Feel the pinch",
    "Feeling blue",
    "Feet on the ground",
    "Fence sitter",
    "Fever pitch",
    "Few and far between",
    "Fiddle while Rome burns",
    "Fifth columnist",
    "Fifth wheel",
    "Fight an uphill battle",
    "Fight tooth and nail",
    "Fighting chance",
    "Find your feet",
    "Fine and dandy",
    "Fine tuning",
    "Fine words butter no parsnips",
    "Finger in the pie",
    "Fingers and thumbs",
    "Fire away",
    "Fire in the hole!",
    "Fire on all cylinders",
    "First come, first served",
    "First out of the gate",
    "First port of call",
    "Fish in troubled waters",
    "Fish or cut bait",
    "Fish out of water",
    "Fishy",
    "Fit as a butcher's dog",
    "Fit as a fiddle",
    "Fit for a king",
    "Fit like a glove",
    "Fit of pique",
    "Fit the bill",
    "Fit to be tied",
    "Five o'clock shadow",
    "Flash in the pan",
    "Flat as a pancake",
    "Flat out",
    "Fleet of foot",
    "Flesh and blood",
    "Flogging a dead horse",
    "Flowery speech",
    "Fly in the ointment",
    "Fly off the handle",
    "Fly on the wall",
    "Fly the coop",
    "Fly the flag",
    "Foam at the mouth",
    "Follow your nose",
    "Food for thought",
    "Fool me once, shame on you; fool me twice, shame on me",
    "Fools rush in where angels fear to tread",
    "Foot in mouth",
    "Foot in the door",
    "Foot the bill",
    "Football's a game of two halves",
    "For a song",
    "For donkey's years",
    "For England",
    "For kicks",
    "For my money",
    "For the birds",
    "For the time being",
    "Forbidden fruit",
    "Foregone conclusion",
    "Forest for the trees",
    "Fortune knocks once at every man's door",
    "Foul play",
    "Four corners of the earth",
    "Four-square behind",
    "Fourth estate",
    "Free rein",
    "Free-for-all",
    "French leave",
    "Fresh from the oven",
    "Freudian Slip",
    "Friendly footing",
    "Frog in my throat",
    "From a different angle",
    "From Missouri",
    "From rags to riches",
    "From scratch",
    "From soup to nuts",
    "From the bottom of your heart",
    "From the get-go",
    "From the horse's mouth",
    "From the word go",
    "Full as a tick",
    "Full bore",
    "Full circle",
    "Full Monty",
    "Full of beans",
    "Full of hot air",
    "Full of oneself",
    "Full of piss and vinegar",
    "Full of the joys of spring",
    "Full swing",
    "Full throttle",
    "Fullness of time",
    "Fuzzy thinking",
  ];

  final List _nameDescription = [
    "If someone has a face like thunder, they are clearly very angry or upset about something.",
    "When someone has a face only a mother could love, they are ugly.",
    "If you have to face the music, you have to accept the negative consequences of something you have done wrong.",
    "If you take something at face value, you accept the appearance rather than looking deeper into the matter.",
    "If you face your demons, you confront your fears or something that you have been trying hard to avoid.",
    "When someone is taught the facts of life, they learn about sex and reproduction.",
    "Failure is often a stepping stone towards success.",
    "This means that you will not get the partner of your dreams if you lack the confidence to let them know how you feel.",
    "If someone wins something fair and square, they follow the rules and win conclusively.",
    "(UK) If everybody has a fair crack of the whip, they all have equal opportunities to do something.",
    "(USA) If everybody has a fair shake of the whip, they all have equal opportunities to do something.",
    "Meaning completely and fully: I am tied up today to a fair-thee-well.",
    "A fair-weather friend is the type who is always there when times are good but forgets about you when things get difficult or problems crop up.",
    "To fall by the wayside is to give up or fail before completion.",
    "If a person falls from grace, they lose favor with someone.",
    "(UK) If someone tries to sell you something that has fallen of the back of a lorry, they are trying to sell you stolen goods.",
    "If someone falls off the wagon, they start drinking after having given up completely for a time.",
    "If you fall on your feet, you succeed in doing something where there was a risk of failure.",
    "If someone falls on their sword, they resign or accept the consequences of some wrongdoing.",
    "This means that the more you know something or someone, the more you start to find faults and dislike things about it or them.",
    "this expression is used as a way of showing disbelief, rejection or self-deprecation. 'They said we had no chance of winning- famous last words!'",
    "Things that happen fast and furious happen very quickly without stopping or pausing.",
    "A fat cat is a person who makes a lot of money and enjoys a privileged position in society.",
    "This idiom is a way of telling someone they have no chance.",
    "A fat head is a dull, stupid person.",
    "When the fat hits the fire, trouble breaks out.",
    "Living off the fat of the land means having the best of everything in life.",
    "Describing something as a fate worse than death is a fairly common way of implying that it is unpleasant.",
    "If you indulge yourself with all that you have today, you may have to go without tomorrow.",
    "A success or achievement that may help you in the future is a feather in your cap.",
    "If someone feathers their own nest, they use their position or job for personal gain.",
    "When people are fighting or arguing angrily, we can say that feathers are flying.",
    "When you are extremely irritated and fed up with something or someone, you are fed up to the back teeth.",
    "If you feel relaxed and comfortable somewhere or with someone, you feel at home.",
    "If you ask for permission to do something and are told to feel free, the other person means that there is absolutely no problem.",
    "If you feel like a million, you are feeling very well (healthy) and happy.",
    "If someone is short of money or feeling restricted in some other way, they are feeling the pinch.",
    "If you feel blue, you are feeling unwell, mainly associated with depression or unhappiness.",
    "A practical and realistic person has their feet on the ground.",
    "Someone that try to support both side of an argument without committing to either is a fence sitter.",
    "When a situation has reached fever pitch, people are extremely excited or agitated.",
    "If things are few and far between, they happen very occasionally.",
    "If people are fiddling while Rome burns, they are wasting their time on futile things while problems threaten to destroy them.",
    "(UK) A fifth columnist is a member of a subversive organization who tries to help an enemy invade.",
    "(USA) A fifth wheel is something unnecessary or useless.",
    "When you fight an uphill battle, you have to struggle against very unfavorable circumstances.",
    "If someone will fight tooth and nail for something, they will not stop at anything to get what they want. ('Fight tooth and claw' is an alternative)",
    "If you have a fighting chance, you have a reasonable possibility of success.",
    "When you are finding your feet, you are in the process of gaining confidence and experience in something.",
    "(UK) If things are fine and dandy, then everything is going well.",
    "Small adjustments to improve something or to get it working are called fine tuning.",
    "This idiom means that it's easy to talk, but talk is not action.",
    "If you have a finger in the pie, you have an interest in something.",
    "If you are all fingers and thumbs, you are being clumsy and not very skilled with your hands.",
    "If you want to ask someone a question and they tell you to fire away, they mean that you are free to ask what you want.",
    "This is used as a warning when a planned explosion is about to happen.",
    "If something is firing on all cylinders, it is going as well as it could.",
    "This means there will be no preferential treatment and a service will be provided to those that arrive first.",
    "When someone is first out of the gate, they are the first to do something that others are trying to do.",
    "The first place you stop to do something is your first port of call.",
    "Someone who fishes in troubled waters tries to takes advantage of a shaky or unstable situation.",
    "(USA) This idiom is used when you want to tell someone that it is time to take action.",
    "If you are placed in a situation that is completely new to you and confuses you, you are like a fish out of water.",
    "If there is something fishy about someone or something, there is something suspicious; a feeling that there is something wrong, though it isn't clear what it is.",
    "Someone who's very healthy, fit or physically attractive is as fit as a butcher's dog.",
    "If you are fit as a fiddle, you are in perfect health.",
    "If something is fit for a king, it is of the very highest quality or standard.",
    "If something fits like a glove, it is suitable or the right size.",
    "If someone reacts badly because their pride is hurt, this is a fit of pique.",
    "If something fits the bill, it is what is required for the task.",
    "If someone is fit to be tied, they are extremely angry.",
    "A five o'clock shadow is the facial hair that a man gets if he doesn't shave for a day or two.",
    "If something is a flash in the pan, it is very noticeable but doesn't last long, like most singers, who are very successful for a while, then forgotten.",
    "It is so flat that it is like a pancake- there is no head on it.",
    "If you work flat out, you work as hard and fast as you possibly can.",
    "If someone is fleet of foot, they are very quick.",
    "Your flesh and blood are your blood relatives, especially your immediate family.",
    "(UK) If someone is trying to convince people to do or feel something without any hope of succeeding.",
    "Flowery speech is full of lovely words, but may well lack substance.",
    "A fly in the ointment is something that spoils or prevents complete enjoyment of something.",
    "If someone flies off the handle, they get very angry.",
    "If you are able to see and hear events as they happen, you are a fly on the wall.",
    "When children leave home to live away from their parents, they fly the coop.",
    "If someone flies the flag, they represent or support their country. ('Wave the flag' and 'show the flag' are alternative forms of this idiom)",
    "If you foam at the mouth, you are very, very angry.",
    "When giving directions, telling someone to follow their nose means that they should go straight ahead.",
    "If something is food for thought, it is worth thinking about or considering seriously.",
    "This means that you should learn from your mistakes and not allow people to take advantage of you repeatedly.",
    "This idiom is used where people who are inexperienced or lack knowledge do something that more informed people would avoid.",
    "This is used to describe someone who has just said something embarrassing, inappropriate, wrong or stupid.",
    "If you have or get your foot in the door, you start working in a company or organization at a low level, hoping that you will be able to progress from there.",
    "The person who foots the bill pays the bill for everybody.",
    "(UK) If something's a game of two halves, it means that it's possible for someone's fortunes or luck to change and the person who's winning could end up a loser.",
    "If you buy or sell something for a song, it is very cheap.",
    "(UK) If people have done something, usually without much if any change, for an awfully long time, they can be said to have done it for donkey's years.",
    "(UK) A person who talks for England, talks a lot- if you do something for England, you do it a lot.",
    "If you do something for kicks, or just for kicks, you do it purely for fun or thrills.",
    "This idiom means 'in my opinion'.",
    "If something is worthless or ridiculous, it is for the birds.",
    "For the time being indicates that an action or state will continue into the future, but is temporary. I'm sharing an office for the time being.",
    "Something enjoyable that is illegal or immoral is forbidden fruit.",
    "If the result of, say, a football match is a foregone conclusion, then the result is obvious before the game has even begun.",
    "(USA) If someone can't see the forest for the trees, they get so caught up in small details that they fail to understand the bigger picture.",
    "Everyone gets one good chance in a lifetime.",
    "If the police suspect foul play, they think a crime was committed.",
    "If something goes to, or comes from, the four corners of the earth, it goes or comes absolutely everywhere.",
    "If someone stands four-square behind someone, they give that person their full support.",
    "This is an idiomatic way of describing the media, especially the newspapers.",
    "If someone has a free rein, they have the authority to make the decisions they want without any restrictions. ('Free reign' is a common mistake)",
    "A free-for-all is a fight or contest in which everyone gets involved and rules are not respected.",
    "To take French leave is to leave a gathering without saying goodbye or without permission.",
    "If something is fresh from the oven, it is very new.",
    "If someone makes a Freudian slip, they accidentally use the wrong word, but in doing so reveal what they are really thinking rather than what they think the other person wants to hear.",
    "When relationships are on a friendly footing, they are going well.",
    "If you have a frog in your throat, you can't speak or you are losing your voice because you have a problem with your throat.",
    "If you look at something from a different angle, you look at it from a different point of view.",
    "(USA) If someone is from Missouri, then they require clear proof before they will believe something.",
    "Someone who starts life very poor and makes a fortune goes from rags to riches.",
    "This idiom means 'from the beginning'.",
    "If you do something from soup to nuts, you do it from the beginning right to the very end.",
    "If someone does something from the bottom of their heart, then they do it with genuine emotion and feeling.",
    "(USA) If something happens from the get-go, it happens from the very beginning.",
    "If you hear something from the horse's mouth, you hear it directly from the person concerned or responsible.",
    "From the word go means from the very beginning of something.",
    "If you are as full as a tick, you have eaten too much.",
    "If something is full bore, it involves the maximum effort or is complete and thorough.",
    "When something has come full circle, it has ended up where it started.",
    "(UK) If something is the Full Monty, it is the real thing, not reduced in any way.",
    "If someone's full of beans, they are very energetic.",
    "Someone who is full of hot air talks a lot of rubbish.",
    "Someone who acts in a arrogant or egotistical manner is full of himself/herself.",
    "Someone who's full of piss and vinegar is full of youthful energy.",
    "If you are full of the joys of spring, you are very happy and full of energy.",
    "If a something is in full swing, it is going or doing well.",
    "If you do something full throttle, you do it with as much speed and energy as you can.",
    "If something happens in the fullness of time, it will happen when the time is right and appropriate.",
    "Thinking or ideas that do not agree with the facts or information available.",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'F',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
