import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class G extends StatelessWidget {
  final List _name = [
    "Game on",
    "Game plan",
    "Garbage fee",
    "Garbage in, garbage out",
    "Gather pace",
    "Gather steam",
    "Get a grip",
    "Get a handle on",
    "Get a sheepskin",
    "Get along famously",
    "Get away scot-free",
    "Get away with murder",
    "Get back on the horse that bucked you",
    "Get in on the act",
    "Get in on the ground floor",
    "Get it in the neck",
    "Get it off your chest",
    "Get my drift",
    "Get off the ground",
    "Get on like a house on fire",
    "Get on your nerves",
    "Get out of bed on the wrong side",
    "Get out of your pram",
    "Get the axe",
    "Get the ball rolling",
    "Get the green light",
    "Get the monkey off your back",
    "Get the nod",
    "Get the picture",
    "Get the show on the road",
    "Get to grips",
    "Get up and go",
    "Get wind of",
    "Get your ducks in a row",
    "Get your feathers in a bunch",
    "Get your feet wet",
    "Get your goat",
    "Get your hands dirty",
    "Get your head around something",
    "Get your teeth into",
    "Get your wires crossed",
    "Ghost of a chance",
    "Gift of the gab",
    "Gild the lily",
    "Gilded cage",
    "Girl Friday",
    "Give a big hand",
    "Give a dog a bad name",
    "Give and take",
    "Give as good as you get",
    "Give away the store",
    "Give it some stick",
    "Give me a hand",
    "Give me five",
    "Give someone a leg up",
    "Give someone a piece of your mind",
    "Give someone a run for their money",
    "Give someone enough rope",
    "Give someone stick",
    "Give someone the runaround",
    "Give up the ghost",
    "Give your eye teeth",
    "Glass ceiling",
    "Glory hound",
    "Gloves are off",
    "Gnaw your vitals",
    "Go awry",
    "Go bananas",
    "Go blue",
    "Go bust",
    "Go by the board",
    "Go by the boards",
    "Go down like a cup of cold sick",
    "Go down like a lead balloon",
    "Go down swinging",
    "Go down without a fight",
    "Go Dutch",
    "Go fly a kite",
    "Go for broke",
    "Go for the jugular",
    "Go fry an egg",
    "Go hand in hand",
    "Go haywire",
    "Go nuts",
    "Go off on a tangent",
    "Go overboard",
    "Go pear-shaped",
    "Go play in traffic",
    "Go round in circles",
    "Go south",
    "Go spare",
    "Go tell it to birds",
    "Go the distance",
    "Go the extra mile",
    "Go the whole hog",
    "Go through the motions",
    "Go to seed",
    "Go to the wire",
    "Go to your head",
    "Go under the hammer",
    "Go west",
    "Go with the flow",
    "Go-to guy",
    "Going concern",
    "Going Jesse",
    "Going overboard",
    "Golden handshake",
    "Golden touch",
    "Gone fishing",
    "Gone pear-shaped",
    "Gone to pot",
    "Gone to the dogs",
    "Good antennae",
    "Good as gold",
    "Good egg",
    "Good fences make good neighbors",
    "Good hand",
    "Good shape",
    "Good time",
    "Good to go",
    "Good walls make good neighbors",
    "Goody two-shoes",
    "Grab the bulls by its horns",
    "Grain of salt",
    "Grasp the nettle",
    "Grass roots",
    "Grass widow",
    "Graveyard shift",
    "Gravy train",
    "Grease monkey",
    "Grease someone's palm",
    "Grease the skids",
    "Greased lightning",
    "Great guns",
    "Greek to me",
    "Green around the gills",
    "Green fingers",
    "Green light",
    "Green thumb",
    "Green with envy",
    "Green-eyed monster",
    "Grey area",
    "Grey cells",
    "Grey matter",
    "Grey pound",
    "Grey suits",
    "Grin and bear it",
    "Grinds my gear",
    "Gunboat diplomacy",
    "Gung ho",
  ];

  final List _nameDescription = [
    "When someone says 'Game on!', it means that they are accepting a challenge or ready to get something done.",
    "A game plan is a strategy.",
    "A garbage fee is a charge that has no value and doesn't provide any real service.",
    "If a computer system or database is built badly, then the results will be bad.",
    "If events gather pace, they move faster.",
    "If something gathers speed, it moves or progresses at an increasing speed.",
    "If you get a grip, you control your emotions so that they don't overwhelm you.",
    "When you get a handle on something, you come to understand it.",
    "Getting a sheepskin (or your sheepskin) means getting a degree or diploma.  (Sheepskin refers to the parchment that a degree is printed on-  parchment comes from sheepskin)",
    "If people get along famously, they have an exceedingly good relationship.",
    "If someone gets away scot-free, they are not punished when they have done something wrong. ('Get off scot-free' is an alternative)",
    "If you get away with murder, you do something bad and don't get caught or punished.('Get away with blue murder' is also used)",
    "When you start drinking again after being hangover from drinking the previous night.",
    "If people want to get in on the act, they want to participate in something that is currently profitable or popular.",
    "If you get in on the ground floor, you enter a project or venture at the start before people know how successful it might be.",
    "(UK) If you get it in the neck, you are punished or criticized for something.",
    "If you get something off your chest, you confess to something that has been troubling you.",
    "If you get someone's drift, you understand what they are trying to say. ('Catch their drift' is an alternative form)",
    "If a project or plan gets off the ground, it starts to be put into operation.",
    "If people get on like a house on fire, they have a very close and good relationship.",
    "If something gets on your nerves, it annoys or irritates you.",
    "If you get out of bed on the wrong side, you wake up and start the day in a bad mood for no real reason.",
    "(UK) If someone gets out of their pram, they respond aggressively to an argument or problem that doesn't involve them.",
    "If you get the axe, you lose your job.  ('Get the ax' is the American spelling)",
    "If you get the ball rolling, you start something so that it can start making progress.",
    "If you get the green light to do something, you are given the necessary permission, authorization.",
    "If you get the monkey off your back, you pass on a problem to someone else.",
    "(UK) If you get the nod to something, you get approval or permission to do it.",
    "If you get the picture, you understand a situation fully.",
    "If you get the show on the road, you put a plan into operation or begin something.",
    "If you get to grips with something, you take control and do it properly.",
    "If someone has lots of get up and go, they have lots of enthusiasm and energy.",
    "If you get wind of something, you hear or learn about it, especially if it was meant to be secret.",
    "If you get your ducks in a row, you organize yourself and your life.",
    "If you get your feathers in a bunch, you get upset or angry about something.",
    "If you get your feet wet, you gain your first experience of something.",
    "If something gets your goat, it annoys you.",
    "If you get your hands dirty, you become involved in something where the realities might compromise your principles.",
    "If you get your head around something, you come to understand it even though it is difficult to comprehend.",
    "If you get your teeth into something, you become involved in or do something that is intellectually challenging or satisfying.  ('Dig you teeth into' and 'sink your teeth into' are also used)",
    "If people get their wires cross, they misunderstand each other, especially when making arrangements.  ('Get your lines crossed' is also used)",
    "If something or someone hasn't got a ghost of a chance, they have no hope whatsoever of succeeding.",
    "If someone has the gift of the gab, they speak in a persuasive and interesting way.",
    "If you gild the lily, you decorate something that is already ornate.",
    "If someone is in a gilded cage, they are trapped and have restricted or no freedom, but have very comfortable surroundings- many famous people live in luxury but cannot walk out of their house alone.",
    "A girl Friday is a female employee who assists someone without any specific duties.",
    "Applaud by clapping hands. 'Let's give all the contestants a big hand.'",
    "Once someone has gained a bad reputation, it is very difficult to lose it.",
    "Where there is give and take, people make concessions in order to get things they want in negotiations.",
    "If you give as good as you get, you are prepared to treat people as badly as they treat you and to fight for what you believe.",
    "(USA) If someone gives away the store, they say or do something that makes their position in negotiations, debates, etc, much weaker.",
    "(UK) If you give something some stick, you put a lot of effort into it.",
    "If someone gives you a hand, they help you.",
    "If someone says this, they want to hit your open hand against theirs as a way of congratulation or greeting.",
    "If you give someone a leg up, you help them to achieve something that they couldn't have done alone.",
    "If you give someone a piece of your mind, you criticize them strongly and angrily.",
    "If you can give someone a run for the money, you are as good, or nearly as good, as they are at something.",
    "If you give someone enough rope, you give them the chance to get themselves into trouble or expose themselves. (The full form is 'give someone enough rope and they'll hang themselves)",
    "(UK) If someone gives you stick, they criticize you or punish you.",
    "If someone gives you the runaround, they make excuses and give you false explanations to avoid doing something.",
    "People give up the ghost when they die.  Machines stop working when they give up the ghost.",
    "If you really want something and would be prepared to sacrifice a lot to get it, you would give your eye teeth for it.",
    "The glass ceiling is the discrimination that prevents women and minorities from getting promoted to the highest levels of companies and organizations.",
    "A glory hound is a person seeking popularity, fame and glory.",
    "When the gloves are off, people start to argue or fight in a more serious way. ('The gloves come off' and 'take the gloves off' are also used. It comes from boxing, where fighters normally wear gloves so that they don't do too much damage to each other)",
    "If something gnaws your vitals, it troubles you greatly and affects you at a very deep level. ('Gnaw at your vitals' is also used)",
    "If things go awry, they go wrong.",
    "If you go bananas, you are wild with excitement, anxiety, or worry.",
    "If you go blue, you are very cold indeed. ('Turn blue' is an alternative form)",
    "If a company goes bust, it goes bankrupt.",
    "When something has gone by the board, it no longer exists or an opportunity has been lost.",
    "If something goes by the boards, it fails to get approved or accepted.",
    "(UK) An idea or excuse that will not be well accepted will go down like a cup of cold sick.",
    "(UK) If something goes down like a lead balloon, it fails or is extremely badly received.",
    "If you want to go down swinging, you know you will probably fail, but you refuse to give up.",
    "If someone goes down without a fight, they surrender without putting up any resistance.",
    "If you go Dutch in a restaurant, you pay equal shares for the meal.",
    "(USA) This is used to tell someone to go away and leave you alone.",
    "If someone goes for broke, they risk everything they have for a potentially greater gain.",
    "If you go for the jugular, you attack someone where they are most vulnerable.",
    "(USA) This is used to tell someone to go away and leave you alone.",
    "If things go hand in hand, they are associated and go together.",
    "When something goes haywire, it is completely out of control and erratic.",
    "If someone goes nuts, they get excited over something.",
    "If someone goes off on a tangent, they change the subject completely in the middle of a conversation or talk.",
    "If you go overboard, you do something excessively.",
    "If things have gone wrong, they have gone pear-shaped.",
    "This is used as a way of telling someone to go away.",
    "If people are going round in circles, they keep discussing the same thing without reaching any agreement or coming to a conclusion.",
    "If things go south, they get worse or go wrong.",
    "(UK) If you go spare, you lose your temper completely.",
    "This is used when someone says something that is not credible or is a lie.",
    "If you go the distance, you continue until something ends, no matter how difficult.",
    "If someone is prepared to go the extra mile, they will do everything they can to help or to make something succeed, going beyond their duty what could be expected of them.",
    "If you go the whole hog, you do something completely or to its limits.",
    "When you go through the motions, you do something like an everyday routine and without any feelings whatsoever.",
    "If someone has gone to seed, they have declined in quality or appearance.",
    "If someone goes to the wire, they risk their life, job, reputation, etc, to help someone.",
    "If something goes to your head, it makes you feel vain.  If alcohol goes to your head, it makes you feel drunk quickly.",
    "If something goes under the hammer, it is sold in an auction.",
    "If something goes west, it goes wrong. If someone goes west, they die.",
    "If you go with the flow, you accept things as they happen and do what everyone else wants to do.",
    "A go-to guy is a person whose knowledge of something is considerable so everyone wants to go to him or her for information or results.",
    "A successful and active business is a going concern.",
    "(USA) If something is a going Jesse, it's a viable, successful project or enterprise.",
    "If you go overboard with something, then you take something too far, or do too much.",
    "A golden handshake is a payment made to someone to get them to leave their job.",
    "Someone with a golden touch can make money from or be successful at anything they do.",
    "If someone has gone fishing, they are not very aware of what is happening around them.",
    "(UK) If things have gone pear-shaped they have either gone wrong or produced an unexpected and unwanted result.",
    "If something has gone to pot, it has gone wrong and doesn't work anymore.",
    "If something has gone to the dogs, it has gone badly wrong and lost all the good things it had.",
    "Someone with good antennae is good at detecting things.",
    "If children are as good as gold, they behave very well.",
    "A person who can be relied on is a good egg. Bad egg is the opposite.",
    "This means that it is better for people to mind their own business and to respect the privacy of others.  ('Good fences make good neighbors' is the American English spelling)",
    "If you are a good hand at something, you do it well.",
    "If something's in good shape, it's in good condition. If a person's in good shape, they are fit and healthy.",
    "If you make good time on a journey, you manage to travel faster than you expected.",
    "Someone or something that meets one's approval. 'He is good to go.' 'The idea you had is good to go.'",
    "Your relationship with your neighbors depends, among other things, on respecting one another's privacy.",
    "A goody two-shoes is a self-righteous person who makes a great deal of their virtue.",
    "If you grab (take) the bull by its horns, you deal head-on and directly with a problem.",
    "If you should take something with a grain of salt, you shouldn't necessarily believe it all. ('pinch of salt' is an alternative)",
    "(UK) If you grasp the nettle, you deal bravely with a problem.",
    "This idioms is often used in politics, where it refers to the ordinary people or voters. It can be used to mean people at the bottom of a hierarchy.",
    "A grass widow is a woman whose husband is often away on work, leaving her on her own.",
    "If you have to work very late at night, it is the graveyard shift.",
    "If someone is on the gravy train, they have found and easy way to make lots of money.",
    "A grease monkey is an idiomatic term for a mechanic.",
    "If you grease someone's palm, you bribe them to do something.",
    "If you grease the skids, you facilitate something.",
    "If something or someone moves like greased lightning, they move very fast indeed.",
    "If something or someone is going great guns, they are doing very well.",
    "If you don't understand something, it's all Greek to you.",
    "If someone looks green around the gills, they look ill.",
    "(UK) Someone with green fingers has a talent for gardening.",
    "If you are given the green light, you are given approval to do something.",
    "(USA) Someone with a talent for gardening has a green thumb.",
    "If you are green with envy, you are very jealous.",
    "The green-eyed monster is an allegorical phrase for somebody's strong jealousy.",
    "A grey/gray area is where there is no clear right or wrong.",
    "'Grey cells' means 'brain' Eg: Use your grey cells to understand it.",
    "Grey/gray matter is the human brain.",
    "(UK) In the UK, the grey pound is an idiom for the economic power of elderly people.",
    "The men in grey suits are people who have a lot of power in business or politics, but aren't well-known.",
    "If you have to grin and bear it, you have to accept something that you don't like.",
    "Something that is very annoying grinds your gear.",
    "If a nation conducts its diplomatic relations by threatening military action to get what it wants, it is using gunboat diplomacy.",
    "If someone is gung ho about something, they support it blindly and don't think about the consequences.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'G',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
