import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class H extends StatelessWidget {
  final List _name = [
    "Hail-fellow-well-met",
    "Hair of the dog",
    "Hairy at the heel",
    "Hale and hearty",
    "Half a loaf is better than no bread",
    "Half a mind",
    "Half-baked",
    "Hammer and tongs",
    "Hand in glove",
    "Hand in hand",
    "Hand that rocks the cradle",
    "Hand to mouth",
    "Hands down",
    "Handwriting like chicken scratch",
    "Hang by a thread",
    "Hang in the balance",
    "Hang out to dry",
    "Hanged for a sheep as a lamb",
    "Happy medium",
    "Happy-go-lucky",
    "Hard as nails",
    "Hard by",
    "Hard cheese",
    "Hard of hearing",
    "Hard on someone's heels",
    "Hard sell",
    "Hard to come by",
    "Hard up",
    "Haste makes waste",
    "Hat trick",
    "Hatchet job",
    "Have a ball",
    "Have a bash",
    "Have a blast",
    "Have a crack",
    "Have a foot in both camps",
    "Have a go",
    "Have a heart",
    "Have a ripper",
    "Have a trick up your sleeve",
    "Have no truck with",
    "Have the floor",
    "Have the guts",
    "Have your cake and eat it too",
    "Have your collar felt",
    "Have your fill",
    "Have your lunch handed to you",
    "Have your moments",
    "Have your tail up",
    "Have your work cut out",
    "Having a gas",
    "Hay is for horses",
    "He that travels far knows much",
    "He who hesitates is lost",
    "Head for the hills",
    "Head is in the clouds",
    "Head nor tail",
    "Head on a spike",
    "Head on the block",
    "Head over heels in love",
    "Head south",
    "Heads will roll",
    "Headstrong",
    "Healthy as a horse",
    "Heap coals on someone's head",
    "Hear a pin drop",
    "Hear on the grapevine",
    "Heart in the right place",
    "Heart in your boots",
    "Heart in your mouth",
    "Heart isn't in it",
    "Heart misses a beat",
    "Heart of glass",
    "Heart of gold",
    "Heart of steel",
    "Heart-to-heart",
    "Heaven knows",
    "Heavenly bodies",
    "Heavy-handed",
    "Hedge your bets",
    "Hell in a handcart",
    "Herding cats",
    "Here today, gone tomorrow",
    "Hide nor hair",
    "Hiding to nothing",
    "High and dry",
    "High and low",
    "High and mighty",
    "High as a kite",
    "High on the hog",
    "High-handed",
    "High-wire act",
    "Highway robbery",
    "Himalayan blunder",
    "Hit a nerve",
    "Hit and miss",
    "Hit me with your best shot",
    "Hit rock bottom",
    "Hit rough weather",
    "Hit the airwaves",
    "Hit the books",
    "Hit the bull's-eye",
    "Hit the ceiling",
    "Hit the Dirt",
    "Hit the fan",
    "Hit the ground running",
    "Hit the hay",
    "Hit the mark",
    "Hit the nail on the head",
    "Hit the road",
    "Hit the roof",
    "Hit the sack",
    "Hive of worker bees",
    "Hoist with your own petard",
    "Hold all the aces",
    "Hold the baby",
    "Hold the bag",
    "Hold the fort",
    "Hold the torch",
    "Hold water",
    "Hold your horses",
    "Hold your own",
    "Hold your tongue",
    "Holier-than-thou",
    "Hollow leg",
    "Hollow victory",
    "Home and hearth",
    "Home is where you lay your hat",
    "Home stretch",
    "Home sweet home",
    "Honor among thieves",
    "Honors are even",
    "Hook, line, and sinker",
    "Hop, skip, and a jump",
    "Hope against hope",
    "Hope in hell",
    "Horns of a dilemma",
    "Horse of a different color",
    "Horse trading",
    "Horses for courses",
    "Hostile takeover",
    "Hot air",
    "Hot as blue blazes",
    "Hot as Hades",
    "Hot button",
    "Hot foot",
    "Hot potato",
    "Hot ticket",
    "Hot to trot",
    "Hot under the collar",
    "Hot water",
    "Hot-blooded",
    "Hot-headed",
    "Hour of need",
    "House of cards",
    "How come",
    "How do you like them apples",
    "How long is a piece of string",
    "How's tricks?",
    "Hue and cry",
    "Hung the moon",
    "Hungry as a bear",
    "Hunky Dory",
  ];

  final List _nameDescription = [
    "Someone whose behavior is hearty, friendly and congenial.",
    "If someone has a hair of the dog, they have an alcoholic drink.",
    "(UK) Someone who is hairy at the heel is dangerous or untrustworthy.",
    "Someone who is hale and hearty is in very good health.",
    "It means that getting part of what you want is better than getting nothing at all.",
    "If you have half a mind to do something, you haven't decided to do it, but are thinking seriously about doing it.",
    "A half-baked idea or scheme hasn't not been thought through or planned very well.",
    "If people are going at it hammer and tongs, they are arguing fiercely. The idiom can also be used hen people are doing something energetically.",
    "If people are hand in glove, they have an extremely close relationship.",
    "Hand in hand= work together closely When people in a group, say in an office or in a project, work together with mutual understanding to achieve the target, we say they work hand in hand.",
    "Women have a great power and influence because they have the greatest influence over the development of children- the hand that rocks the cradle. ('The hand that rocks the cradle rules the world' is the full form)",
    "Someone who's living from hand to mouth, is very poor and needs the little money they have coming in to cover their expenses.",
    "If someone is better hands down than everyone else, they are much better.",
    "If your handwriting is very hard to read, it is like chicken scratch.",
    "If something hangs by a thread, there is a very small chance indeed of it being successful or surviving.",
    "If an outcome is hanging in the balance, there are at least two possibilities and it is impossible to predict which will win out.",
    "If you hang someone out to dry, you abandon them when they are in trouble.",
    "This is an expression meaning that if you are going to get into trouble for doing something, then you ought to stop worrying and should try to get everything you can before you get caught.",
    "If you reach a happy medium, you are making a compromise; reaching a conclusion or decision.",
    "If someone is happy-go-lucky, they don't worry or plan and accept things as they happen.",
    "A person who is as hard as nails is either physically tough or has little or no respect for other people's feelings.",
    "'Hard by' means mean 'close to' or 'near'.",
    "(UK) Hard cheese means hard luck.",
    "Someone who's hard of hearing is a bit deaf.",
    "If you are hard on someone's heels, you are close to them and trying to catch or overtake them.  ('Hot on someone's heels' is also used)",
    "If someone puts a lot of pressure on you to do or buy something, they are hard selling it.",
    "If something is hard to come by, it is difficult to find.",
    "If you are hard up, you have very little money.",
    "This idiom means that if you try to do something quickly, without planning it, you're likely to end up spending more time, money, etc, doing it.",
    "Three successes one after the other is a hat trick.",
    "A piece of criticism that destroys someone's reputation is a hatchet job.",
    "If you have a ball, you have a great time, a lot of fun.",
    "If you have a bash at something, you try to do it, especially when there isn't much chance of success.",
    "It means 'to have a lot of fun'.",
    "If you have a crack at something, you try to do it. If someone is attempting to do something and they are unsuccessful, you might say, 'Let me have a crack at it' suggesting that you might be successful at performing the task. ('Take a crack' is also used)",
    "Someone who plays a part or who is involved in two different groups of people, opinions, ways of thinking or living, etc, has a foot in both camps.",
    "If you have a go, you try to do something, often when you don't think you have much chance of succeeding.",
    "If someone has a heart, they are kind and sympathetic.  If you say, 'Have a heart' to someone, you are asking them to be understanding and sympathetic.",
    "If you have a ripper of a time, you enjoy yourself.",
    "If you have a trick up your sleeve, you have a secret strategy to use when the time is right.",
    "If you have no truck with something or someone, you refuse to get involved with it or them.",
    "If someone has the floor, it is their turn to speak at a meeting.",
    "Someone who has enough courage to do something has the guts to do it.",
    "If someone wants to have their cake and eat it too, they want everything their way, especially when their wishes are contradictory.",
    "If someone has their collar felt, they are arrested.",
    "If you have had your fill, you are fed up of somebody or something.",
    "If you have your lunch handed to you, you are outperformed and shown up by someone better.",
    "Someone who has his or her moments exhibits a positive behavior pattern on an occasional basis but not generally.",
    "If someone has their tail up, they are optimistic and expect to be successful.",
    "If you have your work cut out, you are very busy indeed.",
    "If you're having a gas, you are having a laugh and enjoying yourself in company.",
    "This idiom is used as a way of telling children not to say the word 'hey' as in hey you.",
    "People who travel widely have a wide knowledge.",
    "If one waits too long, the opportunity vanishes.",
    "If people head for the hills, they run away from trouble.",
    "If a person has their head in the clouds, they have unrealistic, impractical ideas.",
    "If you can't make head nor tail of something, you cannot understand it at all or make any sense of it.",
    "If someone wants a head on a spike, they want to be able to destroy or really punish a person.",
    "If someone's head is on the block, they are going to be held responsible and suffer the consequences for something that has gone wrong.",
    "When someone falls passionately in love and is intoxicated by the feeling has fallen head over heels in love.",
    "If something head south, it begins to fail or start going bad.'The project proceeded well for the first two months, but then it headed south.'",
    "If heads will roll, people will be punished or sacked for something that has gone wrong.",
    "A headstrong person is obstinate and does not take other people's advice readily.",
    "If you're as healthy as a horse, you're very healthy.",
    "To do something nice or kind to someone who has been nasty to you.",
    "If there is complete silence in a room, you can hear a pin drop.",
    "To receive information indirectly through a series of third parties, similar to a rumor.",
    "If someone's heart is in the right place, they are good and kind, though they might not always appear to be so.",
    "If you're heart is in your boots, you are very unhappy.",
    "If your heart is in your mouth, then you feel nervous or scared.",
    "If your heart is not in something, then you don't really believe in it or support it.",
    "If your heart misses a beat, you are suddenly shocked or surprised. ('Heart skips a beat' is an alternative)",
    "When someone has a heart of glass, they are easily affected emotionally.",
    "someone with a heart of gold is a genuinely kind and caring person.",
    "When someone has a heart of steel, they do not show emotion or are not affected emotionally.",
    "A heart-to-heart is a frank and honest conversation with someone, where you talk honestly and plainly about issues, no matter how painful.",
    "If you ask someone a question and they say this, they have no idea.",
    "The heavenly bodies are the stars.",
    "If someone is heavy-handed, they are insensitive and use excessive force or authority when dealing with a problem.",
    "If you hedge your bets, you don't risk everything on one opportunity, but try more than one thing.",
    "If something is going to hell in a handcart, it is getting worse and worse, with no hope of stopping the decline.",
    "If you have to try to co-ordinate a very difficult situation, where people want to do very different things, you are herding cats.",
    "Money, happiness and other desirable things are often here today, gone tomorrow, which means that they don't last for very long.",
    "When there's no trace of something or a person, you haven't seen hide nor hair of it or them.('Neither hide nor hair' is also used)",
    "If people are on a hiding to nothing, their schemes and plans have no chance of succeeding. 'Hiding to nowhere' is an alternative.",
    "If you are left high and dry, you are left alone and given no help at all when you need it.",
    "If you search high and low, you look everywhere for something or someone.",
    "The high and mighty are the people with authority and power. If a person is high and mighty, they behave in a superior and condescending way.",
    "If someone's as high as a kite, it means they have had too much to drink or are under the influence of drugs.",
    "To live in great comfort with lots of money.",
    "If someone is high-handed, they behave arrogantly and pompously.",
    "A high-wire act is a dangerous or risky strategy, plan, task, etc.",
    "Something that is ridiculously expensive, especially when you have no choice but to pay, is a highway robbery.",
    "A Himalayan blunder is a very serious mistake or error.",
    "If something hits a nerve, it upsets someone or causes them pain, often when it is something they are trying to hide.",
    "Something that is hit and miss is unpredictable and may produce results or may fail.",
    "If someone tells you to hit them with your best shot, they are telling you that no matter what you do it won't hurt them or make a difference to them.",
    "When someone hits rock bottom, they reach a point in life where things could not get any worse.",
    "If you hit rough weather, you experience difficulties or problems.",
    "If someone hits the airwaves, they go on radio and TV to promote something or to tell their side of a story.",
    "If you hit the books, you study or read hard.",
    "If someone hits the bull's-eye, they are exactly right about something or achieve the best result possible. 'Bulls-eye' and 'bullseye' are alternative spellings.",
    "If someone hits the ceiling, they lose their temper and become very angry.",
    "To duck out of the way or fall to the ground to avoid something dangerous.",
    "When it hits the fan, or, more rudely, the shit hits the fan, serious trouble starts.",
    "If someone hits the ground running, they start a new job or position in a very dynamic manner.",
    "When you hit the hay, you go to bed.",
    "If someone hits the mark, they are right about something.",
    "If someone hits the nail on the head, they are exactly right about something.",
    "When people hit the road, they leave a place to go somewhere else.",
    "If you lose your temper and get very angry, you hit the roof.",
    "When you hit the sack, you go to bed.",
    "A hive of worker bees is a group of people working actively and cooperatively. Example: The classroom was a hive of worker bees.",
    "If you are hoist with your own petard, you get into trouble or caught in a trap that you had set for someone else.",
    "If you hold all the aces, you have all the advantages and your opponents or rivals are in a weak position.",
    "(UK) If someone is responsible for something, they are holding the baby.",
    "(USA) If someone is responsible for something, they are holding the bag.",
    "If you hold the fort, you look after something or assume someone's responsibilities while they are away.",
    "If you hold the torch for someone, you have an unrequited or unspoken love.",
    "When you say that something does or does not 'hold water', it means that it is or is not gonna work out.",
    "If someone tells you to hold your horses, you are doing something too fast and they would like you to slow down.",
    "If you can hold your own, you can compete or perform equally with other people.",
    "If you hold your tongue, you keep silent even though you want to speak.",
    "Someone who is holier-than-thou believes that they are morally superior to other people.",
    "Someone who has a hollow leg eats what seems to be more than his stomach can hold.",
    "A hollow victory is where someone wins something in name, but are seen not to have gained anything by winning.",
    "'Home and hearth' is an idiom evoking warmth and security.",
    "Wherever you are comfortable and at ease with yourself is your home, regardless where you were born or brought up.('Home is where you lay your head'  and 'Home is where you hang your hat' are also used.)",
    "The home stretch is the last part of something, like a journey, race or project.",
    "This is said when one is pleased to be back at one's own home.",
    "If someone says there is honor among thieves, this means that even corrupt or bad people sometimes have a sense of honor or integrity, or justice, even if it is skewed.  ('Honour among thieves' is the British English version)",
    "If honors are even, then a competition has ended with neither side emerging as a winner.",
    "If somebody accepts or believes something hook, line, and sinker, they accept it completely.",
    "If a place is a hop, skip, and a jump from somewhere, it's only a short distance away.",
    "If you hope against hope, you hope for something even though there is little or no chance of your wish being fulfilled.",
    "If something hasn't got a hope in hell, it stands absolutely no chance of succeeding.",
    "If you are on the horns of a dilemma, you are faced with two equally unpleasant options and have to choose one.",
    "(USA) If something is a horse of a different color, it's a different matter or separate issue altogether.",
    "Horse trading is an idiom used to describe negotiations, especially where these are difficult and involve a lot of compromise.",
    "Horses for courses means that what is suitable for one person or situation might be unsuitable for another.",
    "If a company is bought out when it does not want to be, it is known as a hostile takeover.",
    "Language that is full of words but means little or nothing is hot air.",
    "If something's as hot as blue blazes, it's extremely hot.",
    "If something's as hot as Hades, it's extremely hot.",
    "(USA) A hot button is a topic or issue that people feel very strongly about.",
    "If you hot foot it out of a place, you leave very quickly, often running.",
    "A problem or issue that is very controversial and no one wants to deal with is a hot potato.",
    "(USA) A hot ticket is something that is very much in demand at the moment.",
    "If someone is hot to trot, they are sexually aroused or eager to do something.",
    "If you're hot under the collar, you're feeling angry or bothered.",
    "If you get into hot water, you get into trouble.",
    "Someone who is hot-blooded is easily excitable or passionate.",
    "A hot-headed person gets angry very easily. (The noun 'hothead' can also be used)",
    "A time when someone really needs something, almost a last chance, is their hour of need.",
    "Something that is poorly thought out and can easily collapse or fail is a house of cards.",
    "If you want to show disbelief or surprise about an action, you can ask a question using 'how come'. How come he got the job? (You can't believe that they gave the job to somebody like him)",
    "(USA) This idiomatic expression is used to express surprise or shock at something that has happened. It can also be used to boast about something you have done.",
    "If someone has no idea of the answer to a question, they can ask 'How long is a piece of string?' as a way of indicating their ignorance.",
    "This is used as a way of asking people how they are and how things have been going in their life.",
    "Hue and cry is an expression that used to mean all the people who joined in chasing a criminal or villain.",
    "If you refer to someone as having hung the moon, you think they are extremely wonderful, or amazing, or good.",
    "If you are hungry as a bear, it means that you are really hungry.",
    "If something is hunky dory, it is perfectly satisfactory, fine.",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'H',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
