import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class I extends StatelessWidget {
  final List _name = [
    "I hereby give notice of my intention",
    "I may be daft, but I'm not stupid",
    "I'll cross that road when I come to it",
    "I'll eat my hat",
    "I've got a bone to pick with you",
    "Icing on the cake",
    "Idle hands are the devil's handiwork",
    "If at first you don't succeed try again",
    "If I had a nickel for every time",
    "If it ain't broke, don't fix it",
    "If the cap fits, wear it",
    "If wishes were horses, beggars would ride",
    "If you are given lemons make lemonade",
    "If you can't stand the heat, get out of the kitchen",
    "If you fly with the crows, you get shot with the crows",
    "If you lie down with dogs, you will get up with fleas",
    "If you lie down with the Devil, you will wake up in hell",
    "If you'll pardon my French",
    "Ill at ease",
    "Ill-gotten gains",
    "In a cleft stick",
    "In a fix",
    "In a flash",
    "In a fog",
    "In a heartbeat",
    "In a jam",
    "In a jiffy",
    "In a nutshell",
    "In a pickle",
    "In a rut",
    "In a tick",
    "In a tight spot",
    "In all honesty",
    "In an instant",
    "In another's shoes",
    "In apple-pie order",
    "In broad daylight",
    "In cahoots",
    "In cold blood",
    "In dire straits",
    "In donkey's years",
    "In dribs and drabs",
    "In droves",
    "In for a penny, in for a pound",
    "In full swing",
    "In high gear",
    "In high spirits",
    "In his cups",
    "In hot water",
    "In light of",
    "In my bad books",
    "In my book",
    "In my good books",
    "In one ear and out the other",
    "In over your head",
    "In rude health",
    "In so many words",
    "In someone's pocket",
    "In spades",
    "In stitches",
    "In tandem",
    "In that vein",
    "In the bag",
    "In the ballpark",
    "In the black",
    "In the cards",
    "In the catbird seat",
    "In the clear",
    "In the clink",
    "In the club",
    "In the dock",
    "In the doghouse",
    "In the driver's seat",
    "In the face of",
    "In the family way",
    "In the flesh",
    "In the gravy",
    "In the hole",
    "In the hot seat",
    "In the know",
    "In the lap of luxury",
    "In the long run",
    "In the loop",
    "In the lurch",
    "In the making",
    "In the offing",
    "In the pink",
    "In the pipeline",
    "In the red",
    "In the saddle",
    "In the same boat",
    "In the short run",
    "In the soup",
    "In the swim",
    "In the swing",
    "In the tall cotton",
    "In the twinkling of an eye",
    "In the zone",
    "In turn",
    "In two minds",
    "In your blood",
    "In your element",
    "In your face",
    "In your sights",
    "Indian file",
    "Indian giver",
    "Indian summer",
    "Ins and outs",
    "Into each life some rain must fall",
    "Into thin air",
    "Iron fist",
    "Irons in the fire",
    "Is Saul also among the prophets?",
    "It ain't over till the fat lady sings",
    "It cost an arm and a leg",
    "It cost the earth",
    "It never rains but it pours",
    "It takes a village to raise a child",
    "It takes two to tango",
    "It's an ill wind that blows no good",
    "It's no use crying over spilt milk",
    "It's not the size of the dog in fight, it's the size of the fight in the dog",
    "It's not the size of the man in the fight, it's the size of the fight in the man",
    "It's your funeral",
    "Itch to",
    "Itchy feet",
    "Ivory tower",
  ];

  final List _nameDescription = [
    "Hereby is used sometimes in formal, official declarations and statements to give greater force to the speaker' or the writer's affirmation. People will say it sometimes to emphasize their sincerity and correctness.",
    "I might do or say silly things occasionally, but in this instance I know what I am doing.",
    "I'll think about something just when it happens, not in advance.",
    "You can say this when you are absolutely sure that you are right to let the other person know that there is no chance of your being wrong.",
    "If somebody says this, they mean that they have some complaint to make against the person they are addressing.",
    "This expression is used to refer to something good that happens on top of an already good thing or situation.",
    "When someone is not busy, or being productive, trouble is bound to follow.",
    "When you fail, try until you get it right!",
    "(USA) When someone uses this expression, they mean that the specific thing happens a lot. It is an abbreviation of the statement 'If I had a nickel for every time that happened, I would be rich'.",
    "Any attempt to improve on a system that already works is pointless and may even hurt it.",
    "This idiom means that if the description is correct, then it is describing the truth, often when someone is being criticized. ('If the shoe fits, wear it' is an alternative)",
    "This means that wishing for something or wanting it is not the same as getting or having it.",
    "Always try and make the best out of a bad situation. With some ingenuity you can make a bad situation useful.",
    "Originally a Harry S. Truman quote, this means that if you can't take the pressure, then you should remove yourself from the situation.",
    "If you wish to be associated with a particular high risk and/or high profile situation and benefit from the rewards of that association, you have to accept the consequences if things go wrong - you cannot dissociate yourself.",
    "This means that if you become involved with bad company, there will be negative consequences.",
    "This means that if you become involved with bad company, there will be negative consequences.",
    "(UK) This idiom is used as a way of apologizing for swearing.",
    "If someone is ill at ease, they are worried or uncomfortable.",
    "Ill-gotten gains are profits or benefits that are made either illegally or unfairly.",
    "If you are in a cleft stick, you are in a difficult situation, caught between choices.",
    "If you are in a fix, you are in trouble.",
    "If something happens in a flash, it happens very quickly indeed.",
    "If you're in a fog, you are confused, dazed or unaware.",
    "If something happens very quickly or immediately, it happens in a heartbeat.",
    "If you are in a jam, you are in some trouble.  If you get out of a jam, you avoid trouble.",
    "If something happens in a jiffy, it happens very quickly.",
    "This idiom is used to introduce a concise summary.",
    "If you are in a pickle, you are in some trouble or a mess.",
    "In a settled or established pattern, habit or course of action, especially a boring one.",
    "(UK) If someone will do something in a tick, they'll do it very soon or very quickly.",
    "If you're in a tight spot, you're in a difficult situation.",
    "If you say something in all honesty, you are telling the complete truth. It can be used as a way of introducing a negative opinion whilst trying to be polite; in all honesty, I have to say that I wasn't very impressed.",
    "If something happens in an instant, it happens very rapidly.",
    "It is difficult to know what another person's life is really like, so we don't know what it is like to be in someone's shoes.",
    "If something is in apple-pie order, it is very neat and organized.",
    "If a crime or problem happens in broad daylight, it happens during the day and should have been seen and stopped.",
    "If people are in cahoots, they are conspiring together.",
    "If something is done in cold blood, it is done ruthlessly, without any emotion.",
    "If you're in dire straits, you're in serious trouble or difficulties.",
    "'I haven't seen her in donkey's years.' - This means for a very long time.",
    "If people arrive in dribs and drabs, they come in small groups at irregular intervals, instead of all arriving at the same time.",
    "When things happen in droves, a lot happen at the same time or very quickly.",
    "If something is worth doing then it is a case of in for a penny, in for a pound, which means that when gambling or taking a chance, you might as well go the whole way and take all the risks, not just some.",
    "If things are in full swing, they have been going for a sufficient period of time to be going well and very actively.",
    "(USA) If something is in high gear, it is in a quick-paced mode. If someone is in high gear, they are feverishly on the fast track.",
    "If someone is in high spirits, they are in a very good mood or feeling confident about something.",
    "If someone is in their cups, they are drunk.",
    "If you are in hot water, you are in serious trouble.",
    "'In light of' is similar to 'due to'.",
    "If you are in someone's bad books, they are angry with you. Likewise, if you are in their good books, they are pleased with you.",
    "This idiom means 'in my opinion'.",
    "If someone is in your good books, you are pleased with or think highly of them at the moment.",
    "If something goes in one ear and out the other, you forget it as soon as you've heard it because it was too complicated, boring etc.",
    "If someone is in over their head, they are out of the depth in something they are involved in, and may end up in a mess.",
    "(UK) If someone's in rude health, they are very healthy.",
    "This phrase  used to mean 'approximately' or 'more or less'.",
    "If a person is in someone's pocket, they are dependent, especially financially.",
    "(UK) If you have something in spades, you have a lot of it.",
    "If someone is in stitches, they are laughing uncontrollably.",
    "If people do things in tandem, they do them at the same time.",
    "If you do something in that (or this) vein, you do it in the same distinctive manner or style.",
    "If something is in the bag, it is certain that you will get it or achieve it.",
    "This means that something is close to the adequate or required value.",
    "If your bank account is in credit, it is in the black.",
    "If something is in the cards, it is bound to occur, it is going to happen, or it is inevitable.",
    "(USA) If someone is in the catbird seat, they are in an advantageous or superior position.",
    "If someone is in the clear, they are no longer suspected of or charged with wrongdoing.",
    "(UK) If someone is in the clink, they are in prison.",
    "(UK) If a woman's in the club, she's pregnant. 'In the pudding club' is an alternative form.",
    "If someone is in the dock, they are on trial in court.",
    "If someone is in the doghouse, they are in disgrace and very unpopular at the moment.",
    "If you are in the driver's seat, you are in charge of something or in control of a situation.",
    "If people act in the face of something, they do it despite it or when threatened by it.",
    "If a woman is in the family way, she is pregnant.",
    "If you meet or see someone in the flesh you actually meet or see them, rather than seeing them on TV or in other media.",
    "If you're in the gravy, you're rich and make money easily.",
    "If someone is in the hole, they have a lot of problems, especially financial ones.",
    "If someone's in the hot seat, they are the target for a lot of unwelcome criticism and examination.",
    "If you are in the know, you have access to all the information about something, which other people don't have.",
    "People in the lap of luxury are very wealthy and have everything that money can buy.",
    "This means 'over a long period of time', 'in the end' or 'in the final result'.",
    "If you're in the loop, you are fully informed about what is happening in a certain area or activity. Bring me to the loop.",
    "If you are left in the lurch, you are suddenly left in an embarrassing or tricky situation.",
    "When something is in the making, it means it is in the process of being made.",
    "If something is in the offing, it is very likely to happen soon.",
    "If you are in very good health, you are in the pink.",
    "If something's in the pipeline, it hasn't arrived yet but its arrival is expected.",
    "If your bank account is overdrawn, it is in the red.",
    "If you're in the saddle, you are in control of a situation.",
    "If people are in the same boat, they are in the same predicament or trouble.",
    "This refers to the immediate future.",
    "If you're in the soup, you're in trouble.",
    "If you are in the swim, you are up-to-date with and fully informed about something.",
    "If things are in the swing, they are progressing well.",
    "A phrase that expresses good times or times of plenty and wealth as tall cotton means a good crop.",
    "If something happens in the twinkling of an eye, it happens very quickly.",
    "If you are in the zone, you are very focused on what you have to do.",
    "This means one after the other. Example: She spoke to each of the guests in turn.",
    "If you are in two minds about something, you can't decide what to do.",
    "A trait or liking that is deeply ingrained in someone's personality and unlikely to change is in their blood.  A similar idiom is 'in his DNA.'",
    "If you are in your element, you feel happy and relaxed because you are doing something that you like doing and are good at. 'You should have seen her when they asked her to sing; she was in her element.'",
    "If someone is in your face, they are direct and confrontational.",
    "If you have someone or something in your sights, they are your target to beat.",
    "If people walk in Indian file, they walk in a line one behind the other.",
    "An Indian giver gives something, then tries to take it back.",
    "If there is a period of warmer weather in late autumn, it is an Indian summer.",
    "If you know the ins and outs of something, you know all the details.",
    "This means that bad or unfortunate things will happen to everyone at some time.",
    "If something vanishes or disappears without trace, it vanishes into thin air; no-one knows where it has gone.",
    "Someone who rules or controls something with an iron fist is in absolute control and tolerates no dissent. An iron fist in a velvet glove is used to describe someone who appears soft on the outside, but underneath is very hard. 'Mailed fist' is an alternative form.",
    "A person who has a few irons in the fire has a number of things working to their advantage at the same time.",
    "It's a biblical idiom used when somebody known for something bad appears all of a sudden to be doing something very good.",
    "This idiom means that until something has officially finished, the result is uncertain.",
    "If something costs an arm and a leg, it is very expensive indeed.",
    "If something costs the earth, it is very expensive indeed.",
    "'It never rains but it pours' means that when things go wrong, they go very wrong.",
    "It takes many people to teach a child all that he or she should know.",
    "This idiom is used to suggest that when things go wrong, both sides are involved and neither side is completely innocent.",
    "This is said when things have gone wrong; the idea being that when bad things happen, there can also be some positive results.",
    "This idiom means that getting upset after something has gone wrong is pointless; it can't be changed so it should be accepted.",
    "Usually referring to a small dog attacking a larger animal, this means that fierceness is not necessarily a matter of physical size, but rather mental/psychological attitude.",
    "This idiom means that determination is often more important than size, strength, or ability.  ('It's not the size of the dog in the fight, it's the size of the fight in the dog.' is also used)",
    "The other person has made a decision that you think is bad. However, it is their choice; it is their funeral.",
    "If you are itching to do something, you are very eager to do it.",
    "One gets itchy feet when one has been in one place for a time and wants to travel.",
    "People who live in ivory towers are detached from the world around them.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'I',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
