import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class K extends StatelessWidget {
  final List _name = [
    "Kangaroo court",
    "Keen as mustard",
    "Keep abreast",
    "Keep at bay",
    "Keep body and soul together",
    "Keep in touch",
    "Keep it on the Q T",
    "Keep it under your hat",
    "Keep mum",
    "Keep posted",
    "Keep someone at arm's length",
    "Keep someone on their toes",
    "Keep the wolf at bay",
    "Keep the wolf from the door",
    "Keep up with the Joneses",
    "Keep your chin up",
    "Keep your cool",
    "Keep your ear to the ground",
    "Keep your eye on the ball",
    "Keep your eye on the prize",
    "Keep your eyes peeled",
    "Keep your fingers crossed",
    "Keep your hair on",
    "Keep your head",
    "Keep your head above water",
    "Keep your nose clean",
    "Keep your nose to the grindstone",
    "Keep your options open",
    "Keep your pants on",
    "Keep your pecker up",
    "Keep your powder dry",
    "Keep your shirt on!",
    "Keep your wig on!",
    "Kettle of fish",
    "Kick a habit",
    "Kick away the ladder",
    "Kick in the teeth",
    "Kick something into the long grass",
    "Kick the ballistics",
    "Kick the bucket",
    "Kick up your heels",
    "Kick your heels",
    "Kicked to touch",
    "Kid gloves",
    "Kill the goose that lays the golden egg",
    "Kill two birds with one stone",
    "Kindred spirit",
    "King of the castle",
    "King's ransom",
    "Kiss and tell",
    "Kiss of death",
    "Kiss something goodbye",
    "Kissing cousin",
    "Kith and kin",
    "Knee slapper",
    "Knee-jerk reaction",
    "Knickers in a twist",
    "Knight in shining armor",
    "Knit your brows",
    "Knock 'em dead",
    "Knock on wood",
    "Knock something on the head",
    "Knock the pins from under someone",
    "Knock your block off",
    "Knock your socks off",
    "Know a hawk from a handsaw",
    "Know full well",
    "Know the ropes",
    "Know where all the bodies are buried",
    "Know which side one's bread is buttered on",
    "Know which way the wind blows",
    "Know your onions",
    "Know your place",
  ];

  final List _nameDescription = [
    "When people take the law into their own hands and form courts that are not legal, these are known as kangaroo court.",
    "(UK) If someone is very enthusiastic, they are as keen as mustard.",
    "If you keep abreast of things, you stay informed about developments.",
    "If you keep someone or something at bay, you maintain a safe distance from them.",
    "If you earn enough to cover your basic expenses, but nothing more than that, you earn enough to keep body and soul together.",
    "If you keep in touch with someone, you keep communicating with them even though you may live far apart.",
    "If you keep something on the Q T, you keep it quiet or secret.('Q-T' is also used)",
    "If you keep something under your hat, you keep it secret.",
    "If you keep mum about something, you keep quiet and don't tell anyone.",
    "If you keep posted about something, you keep up-to-date with information and developments.",
    "If you keep someone or something at arm's length, you keep a safe distance away from them.",
    "If you keep someone on their toes, you make sure that they concentrate on what they are supposed to do.",
    "If you keep the wolf at bay, you make enough money to avoid going hungry or falling heavily into debt.",
    "If you keep the wolf from the door, you have enough money for food and the basic essentials.",
    "People who try to keep up with the Joneses are competitive about material possessions and always try to have the latest and best things.",
    "(UK) This expression is used to tell someone to have confidence.",
    "If you keep your cool, you don't get excessively excited or disturbed in a bad situation.",
    "If you keep your ear to the ground, you try to keep informed about something, especially if there are rumors or uncertainties.",
    "If you keep your eye on the ball, you stay alert and pay close attention to what is happening.",
    "This means that you should keep your focus on achieving a positive end result.",
    "If you keep your eyes peeled, you stay alert or watchful.",
    "If you are keeping your fingers crossed, you are hoping for a positive outcome.",
    "Keep your hair on is advice telling someone to keep calm and not to over-react or get angry.",
    "If you keep your head, you stay calm in times of difficulty.",
    "If you are just managing to survive financially, you are keeping your head above water.",
    "If someone is trying to keep their Nose Clean, they are trying to stay out of trouble by not getting involved in any sort of wrong-doing.",
    "If you keep your nose to the grindstone, you work hard and seriously.",
    "If someone's keeping their options open, they aren't going to restrict themselves or rule out any possible course of action.",
    "If someone tells you to keep your pants on, they mean that you should be patient and not make them rush.",
    "If someone tells you to keep your pecker up, they are telling you not to let your problems get on top of you and to try to be optimistic.",
    "If you keep your powder dry, you act cautiously so as not to damage your chances.",
    "This idiom is used to tell someone to calm down.",
    "(UK) This idiom is used to tell someone to calm down.",
    "A pretty or fine kettle of fish is a difficult problem or situation.",
    "If you kick a habit, you stop doing it.",
    "If someone kicks away the ladder, they remove something that was supporting or helping someone.",
    "Bad news or sudden disappointments are a kick in the teeth.",
    "If an issue or problem is kicked into the long grass, it is pushed aside and hidden in the hope that it will be forgotten or ignored.",
    "It means you realize the intensity of a situation. For example, there is too much unemployment now, so the prime minister must kick the ballistics and change his policy.",
    "When someone kicks the bucket, they die.",
    "(USA) If you kick up your heels, you go to parties or celebrate something.",
    "(UK) If you have to kick your heels, you are forced to wait for the result or outcome of something.",
    "Touch is a zone of the playing field in Rugby. Kicked to touch means the ball was put safely out of play. Idiomatic usage usually means a person has deftly avoided an issue in argument.",
    "If someone is handled with kid gloves, they are given special treatment and handled with great care.",
    "If you kill the goose that lays the golden egg, you ruin something that is very profitable.",
    "When you kill two birds with one stone, you resolve two difficulties or matters with a single action.",
    "A kindred spirit is someone who feels and thinks the way you do.",
    "The king of the castle is the person who is in charge of something or in a very comfortable position compared to their companions.",
    "If something costs or is worth a king's ransom, it costs or is worth a lot of money.",
    "If people kiss and tell, they disclose private or confidential information.",
    "The kiss of death is an action that means failure or ruin for someone, a scheme, a plan, etc.",
    "If someone tells you that you can kiss something goodbye, you have no chance of getting or having it.",
    "A kissing cousin is someone you are related to, but not closely.",
    "your kith and kin are your family; your next of kin are close relations you nominate to deal with your affairs in the event of your death on a document, like a passport.",
    "A knee slapper is something that is considered funny, though it is often used sarcastically.",
    "A knee-jerk reaction is an instant, instinctive response to a situation.",
    "When your knickers are in a twist, you are angry and snappish over something trivial. 'Whenever he loses his car keys, he gets his knickers in a twist.'",
    "A knight in shining armor is someone who saves you when you are in great trouble or danger.",
    "If you knit your brows, you frown or look worried.",
    "'Knock 'em dead' is used as a way of wishing someone luck before they give a performance or have to appear before people, as in an interview, etc. ('em = them)",
    "This idiom is used to wish for good luck. ('Touch wood' is also used)",
    "If you knock something on the head, you stop it or stop doing it.",
    "If someone knocks the pins from under you, they let you down.",
    "To punch someone in the face Eg : The next time you do something like that I'm going to 'knock your block off'.",
    "If something knocks your socks off, it amazes and surprises you, usually in a positive way.",
    "If someone knows a hawk from a handsaw, they are able to distinguish things and assess them.",
    "When you know full well, you are absolutely sure that you know.",
    "Someone who is experienced and knows how the system works know the ropes.",
    "Someone who by virtue of holding a position of trust with an organization for a long period of time has come to know many of the secrets that others in more powerful positions would rather be kept secret knows where the bodies are buried. An implication is that the person knowing these secrets will use that knowledge to secure something of value for him- or herself.",
    "If you know which side one's bread is buttered on, you know where your interests lie and will act accordingly to protect or further them.",
    "This means that you should know how things are developing and be prepared for the future.",
    "If someone is very well-informed about something, they know their onions.",
    "A person who knows their place doesn't try to impose themselves on others.",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'K',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
