import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class M extends StatelessWidget {
  final List _name = [
    "Mad as a badger",
    "Mad as a bag of hammers",
    "Mad as a cut snake",
    "Mad as a hornet",
    "Mad as a March hare",
    "Mad as a wet hen",
    "Made in the shade",
    "Made of money",
    "Major league",
    "Make a better fist",
    "Make a clean breast",
    "Make a killing",
    "Make a meal",
    "Make a mint",
    "Make a monkey of someone",
    "Make a mountain out of a molehill",
    "Make a pig's ear",
    "Make a request",
    "Make a song and dance",
    "Make a virtue out of necessity",
    "Make an enquiry",
    "Make bets in a burning house",
    "Make ends meet",
    "Make hay",
    "Make headway",
    "Make money hand over fist",
    "Make my day",
    "Make no bones about it",
    "Make or break",
    "Make out like a bandit",
    "Make waves",
    "Make you spit",
    "Make your blood boil",
    "Make your flesh crawl",
    "Make your hair stand on end",
    "Make your toes curl",
    "Make yourself scarce",
    "Man Friday",
    "Man in the street",
    "Man of his word",
    "Man of letters",
    "Man of means",
    "Man of parts",
    "Man of straw",
    "Man of the cloth",
    "Man proposes, God disposes",
    "Man upstairs",
    "Man's best friend",
    "Man's man",
    "Many a slip twixt cup and lip",
    "Many hands make light work",
    "Many happy returns",
    "Many moons ago",
    "March to the beat of your own drum",
    "Mark my words",
    "Mark someone's card",
    "Marked man",
    "Matter of life and death",
    "Mealy-mouthed",
    "Meat and drink",
    "Meat and potatoes",
    "Meet someone halfway",
    "Meet your expectations",
    "Meet your Maker",
    "Meet your match",
    "Megaphone diplomacy",
    "Melt your heart",
    "Melting pot",
    "Memory like a sieve",
    "Memory like an elephant",
    "Mend fences",
    "Mess with a bull, you get the horns",
    "Method in his madness",
    "Mexican standoff",
    "Mickey Mouse",
    "Midas touch",
    "Middle of nowhere",
    "Might and main",
    "Mighty oaks from little acorns grow",
    "Mile a minute",
    "Millstone round your neck",
    "Mince words",
    "Mind over matter",
    "Mind the gap",
    "Mind your own beeswax",
    "Mind Your P's and Q's",
    "Mind your P's and Q's",
    "Mint condition",
    "Misery guts",
    "Miss is as good as a mile",
    "Miss the boat",
    "Mom and pop",
    "Monday morning quarterback",
    "Money burns a hole in your pocket",
    "Money doesn`t grow on trees",
    "Money for jam",
    "Money for old rope",
    "Money laundering",
    "Money makes many things",
    "Money talks",
    "Money to burn",
    "Monkey business",
    "Monkey see, monkey do",
    "Moot point",
    "Moral fibre",
    "Moral high ground",
    "More bang for your buck",
    "More front than Brighton",
    "More haste, less speed",
    "More heat than light",
    "More holes than Swiss cheese",
    "More than meets the eye",
    "More than one string to their bow",
    "More than one way to skin a cat",
    "More than you can shake a stick at",
    "Mountain to climb",
    "Move heaven and earth",
    "Move mountains",
    "Move the goalposts",
    "Mover and shaker",
    "Much ado about nothing",
    "Much of a muchness",
    "Muck or nettles",
    "Mud in the fire",
    "Mud in your eye",
    "Mud-slinging",
    "Muddy the waters",
    "Mummy's boy",
    "Murder will out",
    "Murky waters",
    "Music to my ears",
    "Mutton dressed as lamb",
    "My dogs are barking",
    "My eye",
    "My foot!",
    "My hands are full",
    "My hands are tied",
    "My heart bleeds",
    "My heart goes out to someone",
    "My way or the highway",
  ];

  final List _nameDescription = [
    "If someone is as mad as a badger, they are crazy.",
    "Someone who is as mad as a bag of hammers is crazy or stupid. ('Daft as a bag of hammers' is also used)",
    "(AU) One who is mad as a cut snake has lost all sense of reason, is crazy, out of control.",
    "(USA) If someone is as mad as a hornet, they are very angry indeed.",
    "Someone who is excitable and unpredictable is as mad as a March hare.",
    "If someone is as mad as a wet hen, they are extremely angry.",
    "One has an easy time in life or in a given situation.",
    "If you are made of money, you have a lot of money.",
    "Something major league is very important.",
    "If someone makes a better fist of doing something, they do a better job.",
    "If someone makes a clean breast, they confess in full to something they have done.",
    "If you make a killing, you do something that makes you a lot of money.",
    "If someone makes a meal of something, they spend too long doing it or make it look more difficult than it really is.",
    "If someone is making a mint, they are making a lot of money.",
    "If you make a monkey of someone, you make them look foolish.",
    "If somebody makes a mountain out of a molehill, they exaggerate the importance or seriousness of a problem.",
    "If you make a pig's ear of something, you make a mess of it.",
    "If you request something, or make a request, you are asking for something you want or need.",
    "(UK) If someone makes a song and dance, they make an unnecessary fuss about something unimportant.",
    "If you make a virtue out of necessity, you make the best of a difficult or unsatisfactory situation.",
    "If you make an enquiry, you ask for general information about something.",
    "(USA) If people are making bets in a burning house, they are engaged in futile activity while serious problems around them are getting worse.",
    "If somebody finds it hard to make ends meet, they have problems living on the money they earn.",
    "If you make hay, or may hay while the sun shines, you take advantage of an opportunity as soon as it arises and do not waste time.",
    "If you make headway, you make progress.",
    "If you make money hand over fist, you make a lot of money without any difficulty.",
    "If something makes your day, it satisfies you or makes you happy.",
    "If somebody make no bones about a scandal in their past, they are open and honest about it and show no shame or embarrassment.",
    "A make or break decision, stage, etc, is a crucial one that will determine the success or failure of the whole venture.",
    "(USA) If someone is extremely successful in a venture, they make out like a bandit.",
    "If someone makes waves, they cause a lot of trouble.",
    "If something makes you spit, it irritates you or makes you angry.",
    "If something makes your blood boil, it makes you very angry.",
    "If something makes your flesh crawl, it really scares or revolts you. ('Make your flesh creep' is an alternative. 'Make your skin crawl' is also used)",
    "If something makes your hair stand on end, it terrifies you.",
    "If something makes your toes curl, it makes you feel very uncomfortable, shocked or embarrassed.",
    "If someone makes themselves scarce, they go away from a place, especially to avoid trouble or so that they can't be found.",
    "From 'Robinson Crusoe', a 'Man Friday' refers to an assistant or companion, usually a capable one. The common feminine equivalent is 'Girl Friday'. (Also, 'right-hand man')",
    "The man in the street is an idiom to describe ordinary people, especially when talking about their opinions and ideas.",
    "A man of his word is a person who does what he says and keeps his promises.",
    "A man of letters is someone who is an expert in the arts and literature, and often a writer too.",
    "A man, or woman, of means is wealthy.",
    "A man of parts is a person who is talented in a number of different areas or ways.",
    "A weak person that can easily be beaten of changed is a man of straw.",
    "A man of the cloth is a priest.",
    "your fate lies in the hands of God.",
    "When people refer to the man upstairs, they are referring to God.",
    "This is an idiomatic term for dogs.",
    "A man's man is a man who does things enjoyed by men and is respected by other men.",
    "There's many a slip twixt cup and lip means that many things can go wrong before something is achieved.",
    "This idiom means that when everyone gets involved in something, the work gets done quickly.",
    "This expression is used to wish someone a happy birthday.",
    "A very long time ago.",
    "If people march to the beat of their own drum, they do things the way they want without taking other people into consideration.",
    "Mark my words is an expression used to lend an air of seriousness to what the speaker is about to say when talking about the future.",
    "If you mark someone's card, you correct them in a forceful and prompt manner when they say something wrong.",
    "A marked man is a person who is being targeted by people who want to do them harm or cause them trouble.",
    "If something is a matter of life and death, it is extremely important.",
    "A mealy-mouthed person doesn't say what they mean clearly.",
    "If something is meat and drink to you, you enjoy it and are naturally good at it, though many find it difficult.",
    "The meat and potatoes is the most important part of something. A meat and potatoes person is someone who prefers plain things to fancy ones.",
    "If you meet someone halfway, you accept some of their ideas and make concessions.",
    "If something doesn't meet your expectations, it means that it wasn't as good as you had thought it was going to be; a disappointment.",
    "If someone has gone to meet their Maker, they have died.",
    "If you meet your match, you meet a person who is at least as good if not better than you are at something.",
    "If negotiations between countries or parties are held through press releases and announcements, this is megaphone diplomacy, aiming to force the other party into adopting a desired position.",
    "If something melts your heart, it affects you emotionally and you cannot control the feeling.",
    "A melting pot is a place where people from many ethnicities and nationalities live together.",
    "If somebody can't retain things for long in his or her memory and quickly forgets, he or she has a memory like a sieve. A sieve has lots of tiny holes in it to let liquids out while keeping the solids inside.",
    "'An elephant never forgets' is a saying, so if a person has a memory like an elephant, he or she has a very good memory indeed.",
    "When people mend fences, they try to improve or restore relations that have been damaged by disputes or arguments.",
    "If you do something stupid or dangerous, you can get hurt.",
    "If there's method in someone's madness, they do things in a strange and unorthodox way, but manage to get results.",
    "When there is a deadlock in strategy and neither side can do anything that will ensure victory, it's a Mexican standoff.",
    "If something is Mickey Mouse, it is intellectually trivial or not of a very high standard.",
    "If someone has the Midas touch, they make a lot of money out of any scheme they try.",
    "If someone says that he/she is in the middle of nowhere, he/she means that he/she is not sure where he/she is.",
    "this means with all your effort and strength.  As he failed in the previous exam, the student tried might and main to pass the next one.",
    "Big or great things start very small.",
    "To do something very quickly. For example: He was talking a mile a minute.",
    "A millstone around your neck is a problem that prevents you from doing what you want to do.",
    "If people mince words, or mince their words, they don't say what they really mean clearly.",
    "This idiom is used when someone uses their willpower to rise above adversity.",
    "Mind the gap is an instruction used on the Underground in the UK to warn passengers to be careful when leaving the tube or train as there is quite a distance between the train and the platform.",
    "(USA) This idiom means that people should mind their own business and not interfere in other people's affairs.",
    "If you are careful about the way you behave and are polite, you mind Your P's and Q's.",
    "This is used as a way of telling someone to be polite and behave well.",
    "If something is in mint condition, it is in perfect condition.",
    "A misery guts is a person who's always unhappy and tries to make others feel negative.",
    "A miss is as good as a mile means that if you fail, even by the smallest margin, it is still a failure.",
    "If you miss the boat, you are too late to take advantage of an opportunity.",
    "(USA) A mom and pop business is a small business, especially if it is run by members of a family. It can be used in a wider sense to mean that something is small scale.",
    "(USA) A Monday morning quarterback is someone who, with the benefit of hindsight, knows what should have been done in a situation.",
    "If someone has money burning a hole in their pocket, they are eager to spend it, normally in a wasteful manner.",
    "This means that you have to work to earn money; it doesn't come easily or without effort.",
    "If something's money for jam, it's a very easy way of making money.",
    "(UK) If something's money for old rope, it's a very easy way of making money.",
    "If people launder money, they get money made illegally into the mainstream so that it is believed to be legitimate and clean.",
    "This means that money is important.",
    "This means that people can convey many messages with money, and many things can be discovered about people by observing the way they use their money.",
    "If someone is very rich, they have money to burn.",
    "If children get up to monkey business, they are behaving naughtily or mischievously. This is the same as 'monkeying around'.",
    "This idiom means that children will learn their behavior by copying what they see happening around them.",
    "If something's a moot point, there's some disagreement about it.",
    "Moral fibre is the inner strength to do what you believe to be right in difficult situations Example: He lacked the moral fibre to be leader (In American English the correct spelling is 'fiber')",
    "If people have/take/claim/seize, etc, the moral high ground, they claim that their arguments, beliefs, etc, are morally superior to other people.",
    "(USA) Something that will give you more bang for your buck will deliver more value than any other option.",
    "(UK) If you have more front than Brighton, you are very self-confident, possibly excessively so.",
    "The faster you try to do something, the more likely you are to make mistakes that make you take longer than it would had you planned it.",
    "If a discussion generates more heat than light, it doesn't provide answers, but does make people angry.",
    "If something has more holes than a Swiss cheese, it is incomplete, and lacks many parts.",
    "If there is more than meets the eye to something, it is more complex or difficult than it appears.",
    "A person who has more than one string to their bow has different talents or skills to fall back on.",
    "When people say that there is more than one way to skin a cat, they mean that there are different ways of achieving the same thing.",
    "If you have more of something than you can shake a stick at, then you have a lot.",
    "If you have a mountain to climb, you have to work hard or make a lot of progress to achieve something.",
    "This expression indicates a person's determined intention of getting a work done in spite of all odds he may face. He will use all and every means to accomplish the target.",
    "If you would move mountains to do something, you would make any effort to achieve your aim. When people say that faith can move mountains, they mean that it can achieve a lot.",
    "When people move the goalposts, they change the standards required for something to their advantage.",
    "A person who is a mover and shaker is a highly respected, key figure in their particular area with a lot of influence and importance.",
    "If there's a lot of fuss about something trivial, there's much ado about nothing.",
    "Things are much of a muchness when there is very little difference between them.",
    "'Muck or nettles' means 'all or nothing'.",
    "The things that cannot be changed in the past that we usually forget about are mud in the fire.",
    "This is a way of saying 'cheers' when you are about to drink something, normally alcohol.",
    "If someone is mud-slinging, they are insulting someone and trying to damage that person's reputation.",
    "If somebody muddies the waters, he or she makes the situation more complex or less clear.",
    "A man who is still very dependent on his mother is a mummy's boy.",
    "This idiom means that bad deeds can't be kept secret forever.",
    "Where people are behaving in morally and ethically questionable ways, they are in murky waters.",
    "If something someone says is music to your ears, it is exactly what you had wanted to hear.",
    "Mutton dressed as lamb is term for middle-aged or elderly people trying to look younger.",
    "(USA) When someone says this, they mean that their feet are hurting.",
    "This idiom is added to an adjective to show that you disagree with it: 'He's shy.' 'Shy my eye- he's just planning something secret.'",
    "This idiom is used to show that you do not believe what someone has just said.",
    "If your hands are full, you have so much to do that you cannot take on any more work, responsibilities and so on.",
    "If your hands are tied, you are unable to act for some reason.",
    "If your heart bleeds for someone, you feel genuine sympathy and sadness for them.",
    "If your heart goes out to someone, you feel genuine sympathy for them.",
    "This idiom is used to say that if people don't do what you say, they will have to leave or quit the project, etc.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'M',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
