import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class N extends StatelessWidget {
  final List _name = [
    "Nail in the coffin",
    "Nail-biter",
    "Nature of the beast",
    "Neck and neck",
    "Neck of the woods",
    "Need no introduction",
    "Needle in a haystack",
    "Neither fish nor fowl",
    "Neither here nor there",
    "Nerves of steel",
    "Nervous Nellie",
    "Nest egg",
    "Never a rose without the prick",
    "Never darken my door again",
    "New blood",
    "New brush sweeps clean",
    "New kid on the block",
    "New lease of life",
    "New man",
    "New sheriff in town",
    "New York minute",
    "Newfangled",
    "Nice as pie",
    "Nick of time",
    "Nickel tour",
    "Night owl",
    "Ninth circle of hell",
    "Nip and tuck",
    "Nip at the bit",
    "Nip it in the bud",
    "Nitty gritty",
    "No bed of roses",
    "No can do",
    "No go",
    "No good deed goes unpunished",
    "No great shakes",
    "No harm, no foul",
    "No holds barred",
    "No ifs or buts",
    "No laughing matter",
    "No love lost",
    "No pain, no gain",
    "No quarter",
    "No question",
    "No skin off my nose",
    "No smoke without fire",
    "No spine",
    "No spring chicken",
    "No strings attached",
    "No time for",
    "No time like the present",
    "No time to lose",
    "No two ways about it",
    "No use to man or beast",
    "Nod's as good as a wink",
    "Noddy work",
    "None so blind as those who will not see",
    "Nose in the air",
    "Nosy parker",
    "Not a snowball's chance in hell",
    "Not all there",
    "Not bat an eye",
    "Not born yesterday",
    "Not cricket",
    "Not enough room to swing a cat",
    "Not have the heart",
    "Not have two pennies to rub together",
    "Not hurt a fly",
    "Not know beans about",
    "Not know you are born",
    "Not much cop",
    "Not my cup of tea",
    "Not our bag",
    "Not the only pebble on the beach",
    "Not to be sneezed at",
    "Not wash",
    "Not worth a red cent",
    "Notch on your belt",
    "Nothing to crow about",
    "Nothing to write home about",
    "Nothing ventured, nothing gained",
    "Now and then",
    "Null and void",
    "Number cruncher",
    "Nuts and bolts",
    "Nutty as a fruitcake",
  ];

  final List _nameDescription = [
    "A nail in someone or something's coffin is a problem or event that is a clear step towards an inevitable failure.",
    "If a game, election, contest, etc, is a nail-biter, it is exciting because the competitors are so close that it is impossible to predict the result.",
    "The basic characteristics of something is the nature of the beast; often used when there's an aspect of something that cannot be changed or that is unpleasant or difficult.",
    "If two competitors or candidates, etc, are neck and neck, then they are very close and neither is clearly winning.",
    "If someone talks about their neck of the woods, they mean the area where they live.",
    "Someone who is very famous and known to everyone needs no introduction.",
    "If trying to find something is like looking for a needle in a haystack, it means that it is very difficult, if not impossible to find among everything around it.",
    "Something or someone that is neither fish nor fowl doesn't really fit into any group.",
    "If something is neither here nor there, it is of very little importance.",
    "If someone has nerves of steel, they don't get frightened when other people do.",
    "Someone excessively worried or apprehensive is a nervous Nellie (or Nelly).",
    "If you have some money saved for the future, it is a nest egg.",
    "This means that good things always have something bad as well; like the thorns on the stem of a rose.",
    "This is a way of telling someone never to visit you again.",
    "If something needs new blood, it has become stale and needs new ideas or people to invigorate it.",
    "'A new brush sweeps clean' means that someone with a new perspective can make great changes. However, the full version is 'a new brush sweeps clean, but an old brush knows the corners', which warns that experience is also a valuable thing. Sometimes 'broom' is used instead of 'brush'.",
    "A new kid on the block is a person who has recently joined a company, organization, team, etc, and does not know how things work yet.",
    "If someone finds new enthusiasm and energy for something, they have a new lease of life.",
    "(UK) A New man is a man who believes in complete equality of the sexes and shares domestic work equally.",
    "This is used when a new authority figure takes charge.",
    "(USA) If something happens in a New York minute, it happens very fast.",
    "People who don't like new methods, technologies, etc, describe them as newfangled, which means new but not as good or nice as the old ones.",
    "If a person is nice as pie, they are surprisingly very kind and friendly. 'After our argument, she was nice as pie!'",
    "If you do something in the nick of time, you do it at the very last minute or second.",
    "(USA) If someone gives you a nickel tour, they show you around a place. ('Fifty-cent tour' is also used)",
    "A night owl is someone who goes to bed very late.",
    "In Dante's Inferno, the ninth circle of hell is the centre where the worst punishments are found, so it is used idiomatically for something that couldn't get worse.",
    "A close contest where neither opponent seems to be gaining the advantage.",
    "If someone is nipping at the bit, they are anxious to get something done and don't want to wait.",
    "If you nip something in the bud, you deal with a problem when it is still small, before it can grow into something serious.",
    "If people get down to the nitty gritty, they concentrate on the most important and serious issues.",
    "If something isn't a bed of roses, it is difficult.",
    "No can do means that the speaker can't do whatever it is that has been asked of him or her.",
    "Something that will not work. 'A square peg in a round hole is a no go.'",
    "This means that life is unfair and people can do or try to do good things and still end up in a lot of trouble.",
    "If someone is no great shakes at something, they are not very good at it.",
    "There's no problem when no harm or damage is done.",
    "If there are no holds barred, there are no rules of conduct; you can do anything.",
    "Ifs and Buts is a term used to describe the reasons people give for not wanting to do something. To show that you don't wish to accept any excuses, you can tell somebody that you wish to hear no ifs or buts Here IF & BUT have become nouns.",
    "Something that is no laughing matter is very serious.",
    "If there is no love lost between two people they have a strong enmity towards or hate for the other and make no effort to conceal it.",
    "Achievements require some sort of sacrifice.",
    "This means without mercy. We can say no quarter given or asked.",
    "This idiom means that something is certain or definite.",
    "If something's no skin off your nose, it doesn't affect or bother you at all.",
    "This idiom means that when people suspect something, there is normally a good reason for the suspicion, even if there is no concrete evidence.  ('Where's there's smoke, there's fire' is also used)",
    "If someone has no spine, they lack courage or are cowardly.",
    "If someone is no spring chicken, they are not young.",
    "If something has no strings attached, there are no obligations or requirements involved.",
    "If you have no time for an activity, you have absolutely no desire to spend or waste any time doing it. You can have no time for people, too.",
    "If people say that there's no time like the present , they believe that it is far better to do something now than to leave it for later, in which case it might never get done.",
    "If there's no time to lose, then it's time to get started otherwise it won't be finished on time.",
    "If there are no two ways about something, there is no other possible interpretation.",
    "If something or someone is no use to man or beast, it or they are utterly useless.",
    "(UK) 'A nod's as good as a wink' is a way of saying you have understood something that someone has said, even though it was not said directly.  The full phrase (sometimes used in the UK ) is 'a nod's as good as a wink to a blind horse'.",
    "(UK) Unimportant or very simple tasks are noddy work.",
    "This idiom is used when people refuse to accept facts presented to them. ('None so deaf as those who will not hear' is an alternative)",
    "If someone has their nose in the air, they behave in a way that is meant to show that they are superior to others.",
    "(UK) A nosy parker is someone who is excessively interested in other people's lives. ('Nosey parker' is an alternative spelling)",
    "There is absolutely no possibility of something happening if there's not a snowball's chance in hell.",
    "If someone isn't all there, they are a little bit stupid or crazy.",
    "If someone doesn't bat an eye, they do not react when other people normally would.",
    "When someone says that they weren't born yesterday, they mean that they are not naive or easily fooled.",
    "(UK) If something is not cricket, it is unfair.",
    "If a room is very small, you can say that there isn't enough room to swing a cat in it.",
    "If you don't have the heart to do something, you don't have the strength or courage to do something. (Usually used in the negative)",
    "If someone hasn't got two pennies to rub together, they are very poor indeed.",
    "Somebody who would not hurt a fly is not aggressive.",
    "(USA) If someone doesn't know beans about something, they know nothing about it.",
    "This indicates that the person described is unaware of his or her good fortune or is unaware of how difficult day to day life was before he/she was born. Typical usage: 'Kids today don't know they are born'.",
    "Describing a film or something as not much cop is a way of saying that you didn't think much of it.",
    "If something is not your cup of tea, you don't like it very much.",
    "If something is not your bag, it is not really suitable for your needs or you don't like it much.",
    "If something is not the only pebble on the beach, there are other possibilities or alternatives.",
    "If something is not to be sneezed at, it should be taken seriously.",
    "If a story or explanation will not wash, it is not credible.",
    "(USA) If something is not worth a red cent, it has no value.",
    "A success or achievement that might help you in the future is a notch on your belt.",
    "If something's nothing to crow about, it's not particularly good or special.",
    "Something that is not special or good is nothing to write home about.",
    "You can't win if you don't join in the game; if you don't participate in something, you will not achieve anything.",
    "This idiom means 'occasionally'.",
    "If something's null and void, it is invalid or is no longer applicable.",
    "A number cruncher is an accountant or someone who is very good at dealing with numbers and calculations.",
    "The nuts and bolts are the most essential components of something.",
    "Someone who's nutty as a fruitcake is irrational or crazy. (This can be shortened to 'a fruitcake')",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'N',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
