import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class O extends StatelessWidget {
  final List _name = [
    "Object lesson",
    "Odds and ends",
    "Off colour",
    "Off the beaten track",
    "Off the chart",
    "Off the cuff",
    "Off the grid",
    "Off the hook",
    "Off the mark",
    "Off the rails",
    "Off the scale",
    "Off the shelf",
    "Off the top of your head",
    "Off the track",
    "Off the wall",
    "Off your chump",
    "Off your rocker",
    "Off-hand",
    "Oh, my goodness!",
    "Old chestnut",
    "Old flames die hard",
    "Old friends and old wine are best",
    "Old hat",
    "Old wives tale",
    "Oldest trick in the book",
    "Olive branch",
    "On a fishing expedition",
    "On a roll",
    "On a silver platter",
    "On all fours",
    "On Carey Street",
    "On good terms",
    "On hold",
    "On ice",
    "On pins and needles",
    "On tenterhooks",
    "On the ball",
    "On the blink",
    "On the blower",
    "On the cards",
    "On the case",
    "On the cheap",
    "On the dole",
    "On the dot",
    "On the factory floor",
    "On the fiddle",
    "On the flip side",
    "On the fly",
    "On the game",
    "On the ground",
    "On the hoof",
    "On the house",
    "On the lam",
    "On the level",
    "On the line",
    "On the make",
    "On the map",
    "On the money",
    "On the never-never",
    "On the nod",
    "On the nod",
    "On the nose",
    "On the rebound",
    "On the right foot",
    "On the ropes",
    "On the run",
    "On the same page",
    "On the same wavelength",
    "On the shelf",
    "On the skids",
    "On the sly",
    "On the stump",
    "On the take",
    "On the tip of your tongue",
    "On the trot",
    "On the up and up",
    "On the wagon",
    "On the wallaby track",
    "On top of the world",
    "On your high horse",
    "On your last legs",
    "On your tod",
    "On your toes",
    "Once bitten, twice shy",
    "Once in a blue moon",
    "One bad apple",
    "One fell swoop",
    "One for the road",
    "One good turn deserves another",
    "One hand washes the other",
    "One in the eye",
    "One man's loss is another man's gain",
    "One man's meat is another man's poison",
    "One man's trash is another man's treasure",
    "One over the eight",
    "One swallow does not make a summer",
    "One-man band",
    "One-off",
    "One-trick pony",
    "Oops a daisy",
    "Open all hours",
    "Open book",
    "Open old sores",
    "Open old wounds",
    "Opening a can of worms",
    "Opportunity knocks but once",
    "Other fish to fry",
    "Other side of the coin",
    "Out and about",
    "Out in the sticks",
    "Out like a light",
    "Out of hand",
    "Out of hand",
    "Out of pocket",
    "Out of sight, out of mind",
    "Out of sorts",
    "Out of the blue",
    "Out of the box",
    "Out of the frying pan, into the fire",
    "Out of the gate running",
    "Out of the left field",
    "Out of the mouths of babes",
    "Out of the woods",
    "Out of this world",
    "Out of Whack",
    "Out of your hair",
    "Out of your mind",
    "Out of your own pocket",
    "Out on a limb",
    "Out to lunch",
    "Out-and-out",
    "Over a barrel",
    "Over and over",
    "Over my dead body",
    "Over the counter",
    "Over the hill",
    "Over the moon",
    "Over the top",
    "Over your head",
    "Over-egg the pudding",
  ];

  final List _nameDescription = [
    "An object lesson serves as a warning to others. (In some varieties of English 'abject lesson' is used)",
    "Odds and ends are small, remnant articles and things- the same as 'bits and bobs'.",
    "If someone looks off colour/color, they look ill.",
    "Somewhere that's off the beaten track is in a remote location.",
    "If something goes off the chart, it far exceeds the normal standards, good or bad, for something.",
    "If you do something off the cuff, you do it without any preparation.",
    "Someone who is off the grid lives outside society and chooses not to follow its rules and conventions.",
    "If someone is off the hook, they have avoided punishment or criticism for something they have done.",
    "If something is off the mark, it is inaccurate or incorrect.",
    "If someone has gone off the rails, they have lost track of reality.",
    "If something goes off the scale, it far exceeds the normal standards, good or bad, for something.",
    "If a product is off the shelf, it can be used straightaway without any setting-up.",
    "If you say something off the top of your head, you don't think about it beforehand.",
    "If something puts or throws you off your track, it distracts you or keeps you from achieving what you want.",
    "Something that is off the wall is unconventional.",
    "(UK) If someone is off their chump, they are crazy or irrational.",
    "(UK) Someone who is off their rocker is crazy.",
    "Off-hand means without preparation. People say that they don't know the answer off-hand, meaning that they don't know it at that time.",
    "An expression of surprise.",
    "An old chestnut is something that has been repeated so many times that it has lost its impact.",
    "It's very difficult to forget old things, especially the first love.",
    "This idiom means that the things and people that we know well are better than the unfamiliar.",
    "If something's old hat, it seems rather old fashioned and dated.",
    "A proverb or piece of advice that is commonly accepted as truth and is handed down the generations, but is normally false.",
    "The oldest trick in the book is a well-known way of deceiving someone, though still effective.",
    "If you hold out or offer an olive branch, you make a gesture to indicate that you want peace.",
    "If someone is on a fishing expedition, they are trying to get information, often using incorrect or improper ways to find things out.",
    "If you're on a roll, you're moving from success to success.",
    "If you hand or give something on a silver platter to someone, you let them have it too easily.",
    "If someone is on all fours, they crawl.",
    "(UK) If someone is on Carey Street, they are heavily in debt or have gone bankrupt.",
    "If people are on good terms, they have a good relationship.",
    "If something is on hold, no action is being taken.",
    "If plans are put on ice, they are delayed and no action will be taken for the foreseeable future.",
    "If you are on pins and needles, you are very worried about something.",
    "This means that she/he is waiting impatiently and excitedly for something.",
    "If someone's on the ball, they are well-informed and know what's going on in their area of responsibility or interest.",
    "(UK) Is a machine is on the blink, it isn't working properly or is out of order.",
    "(UK) If someone is on the blower, they are on the phone.",
    "(UK) If something is in the cards, it is almost certain to happen.",
    "If someone is on the case, they are dealing with a problem.",
    "If you do something on the cheap, you spend as little as possible to do it.",
    "(UK) Someone receiving financial assistance when unemployed is on the dole.",
    "If someone says that they're leaving at seven on the dot, don't be late; they mean at exactly seven o'clock.",
    "On the factory floor means the place where things are actually produced.",
    "(UK) Someone who is stealing money from work is on the fiddle, especially if they are doing it by fraud.",
    "On the reverse or the other side.",
    "If you do things on the fly, you do things without preparation, responding to events as they happen.",
    "(UK) A person who is on the game works as a prostitute.",
    "Events on the ground are where things are actually happening.",
    "If you decide something on the hoof, you do it without planning, responding to events as they happen.",
    "If you get something for free that would normally have to be bought, especially in a bar or restaurant, it is on the house.",
    "If someone is on the lam, they are hiding from the police or authorities, especially to avoid arrest or prison.",
    "If someone is honest and trustworthy, they are on the level.",
    "If somebody's job is on the line, they stand a very good chance of losing it.",
    "If someone is on the make, they are trying to make a lot of money, usually illegally.",
    "If a place becomes widely known, it is put on the map. A place that remains unknown is off the map.",
    "If you are on the money, you are right about something.",
    "(UK) If you buy something on the never-never, you buy it on long-term credit.",
    "(UK) If something is accepted by parliament or a committee majority, it is on the nod.",
    "(UK) Someone who's on the nod is either asleep or falling asleep, especially when the shouldn't or are in a position unusual for sleep, like sitting or standing.",
    "This means right on time.",
    "If someone is on the rebound, their relationship has recently ended and they are emotionally unstable.",
    "If you start something or set off on the right foot, you get off to a good start.",
    "When something or someone is on the ropes, it or they are doing badly and likely to fail.",
    "If someone is on the run, they are avoiding arrest and hiding from the police.",
    "If people are on the same page, they have the same information and are thinking the same way.",
    "If people are on the same wavelength, they have the same ideas and opinions about something.",
    "If something like a project is on the shelf, nothing is being done about it at the moment.",
    "When things or people are on the skids, they are in serious decline and trouble.",
    "If someone does something on the sly, they do it furtively or secretly.",
    "When politicians are campaigning for support and votes, they are on the stump.",
    "(UK) Someone who is stealing from work is on the take.",
    "If a word is on the tip of your tongue, you know you know the word, but you just can't quite remember it at the moment.",
    "(UK) This idiom means 'consecutively'; I'd saw them three days on the trot, which means that I saw them on three consecutive days.",
    "If you are on the up and up, you are making very good progress in life and doing well.",
    "If someone is on the wagon, they have stopped drinking alcohol.",
    "(AU) In Australian English, if you're on the wallaby track, you are unemployed.",
    "If you are on top of the world, everything is going well for you.",
    "When someone is on their high horse, they are being inflexible, arrogant and will not make any compromises.",
    "If someone's on their last legs, they're close to dying.",
    "If you are on your tod, you are alone.",
    "Someone on his or her toes is alert and ready to go.",
    "If somebody is said to be once bitten twice shy, it means that someone who has been hurt or who has had something go wrong will be far more careful the next time.",
    "If something happens once in a blue moon, it happens very rarely indeed.",
    "The full form of this proverb is 'one bad apple spoils the barrel', meaning that a bad person, policy, etc, can ruin everything around it.",
    "If something is done at one fell swoop, it is done in a single period of activity, usually swiftly and ruthlessly.",
    "A last drink before leaving a pub or bar is one for the road.",
    "This means that when people do something good, something good will happen to them.",
    "This idiom means that we need other people to get on as cooperation benefits us all.",
    "If you achieve something that will irritate someone because they did not think that you were capable it is one in the eye for them.",
    "This means that one person's setback benefits someone else.",
    "This idiom means that one person can like something very much, but another can hate it.",
    "What is useless to one person might be valuable to another.",
    "(UK) Someone who has had one over the eight is very drunk indeed. It refers to the standard eight pints that most people drink and feel is enough.",
    "This means that one good or positive event does not mean that everything is all right.",
    "If one person does all the work or has all the responsibility somewhere, then they are a one-man band.",
    "A one-off event only happens once and will not be repeated.",
    "A one-trick pony is someone who does one thing well, but has limited skills in other areas.",
    "An expression used to indicate surprise.",
    "If a shop or suchlike is open all hours, it closes terribly late.",
    "If a person is an open book, it is easy to know what they think or how they feel about things.",
    "When a sore is almost healed, and if a person rips or tears it open, it is way of preventing the healing process and further aggravating the pain. This phrase, metaphorically suggests, reviving or reopening a quarrel or enmity which was almost forgotten.",
    "If you open old wounds, you revive a quarrel or problem that caused a lot of trouble in the past.",
    "If you open a can of worms, you do something that will cause a lot of problems and is probably going to cause more trouble than it's worth.",
    "This idiom means that you only get one chance to achieve what you really want to do.",
    "If you have other fish to fry, it doesn't matter if one opportunity fails to materialize as you have plenty of others.",
    "The other side of the coin is a different, usually opposing, view of a situation. ('Flip side of the coin' is an alternative)",
    "If someone is out and about, they have left their home and are getting things done that they need to do.",
    "(UK) If someone lives out in the sticks, they live out in the country, a long way from any metropolitan area.",
    "If you are out like a light, you fall fast asleep.",
    "If something gets out of hand, it gets out of control.",
    "If someone or something is out of your league, you aren't good enough or rich enough, etc, for it or them.",
    "If you are out of pocket on a deal, you have lost money.",
    "Out of sight, out of mind is used to suggest that someone will not think or worry about something if it isn't directly visible or available to them.",
    "If you are feeling a bit upset and depressed, you are out of sorts.",
    "If something happens out of the blue, it happens suddenly and unexpectedly.",
    "Thinking out of the box is thinking in a creative way. However, it can also be used for a ready-made product that requires no specialist knowledge to set it up.",
    "If you get out of one problem, but find yourself in a worse situation, you are out of the frying pan, into the fire.",
    "If someone comes out of the gate running, they start something at a fast pace, without any build-up.",
    "(USA) If something comes out of the left field, it is beside the point and has nothing to do with the matter being discussed.",
    "People say this when children unexpectedly say something very intelligent or wise.",
    "If you are out of the woods, you have emerged safely from a dangerous situation, though the idiom is often used in the negative.",
    "If something is out of this world, it is fantastic.",
    "If something is out of whack, it is not working correctly or not in the correct order.",
    "If you get someone out of your hair, you get them to stop bothering or annoying you. ('Stay/keep/get out of my hair!' can be used as imperatives)",
    "If someone is out of the mind, they are so emotional about something that they are no longer rational or you don't think about them anymore.",
    "If someone does something out of their own pocket, they pay all the expenses involved.",
    "If somebody's out on a limb, they are in a very exposed position and could get into difficulties.",
    "If someone's out to lunch, they are crazy or out of touch.",
    "This means complete or total; an out-and-out lie is completely false.",
    "If someone has you over a barrel, they have you in a position where you have no choice but to accept what they want.",
    "If something happens over and over, it happens repeatedly.",
    "If you say that something will happen over your dead body, you will not let it happen.",
    "Medicines and drugs that can be sold without a doctor's prescription are sold over the counter.",
    "If someone is over the hill they have reached an age at which they can longer perform as well as they used to.",
    "If you are over the moon about something, you are overjoyed.",
    "If something is over the top, it is excessive or unnecessary.  It refers to the moment a soldier leaves the trenches.",
    "If something is over your head, or goes over your head, it is too complex or difficult for you to understand.",
    "(UK) If you over-egg the pudding, you spoil something by trying to improve it excessively. It is also used nowadays with the meaning of making something look bigger or more important than it really is. ('Over-egg' alone is often used in this sense)",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'O',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
