import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class P extends StatelessWidget {
  final List _name = [
    "Packed like sardines",
    "Paddle your own canoe",
    "Pain in the neck",
    "Paint the town red",
    "Paint yourself into a corner",
    "Pandora's box",
    "Paper over the cracks",
    "Paper tiger",
    "Par for the course",
    "Parrot fashion",
    "Part and parcel",
    "Pass muster",
    "Pass the buck",
    "Pass the hat",
    "Pass the time of day",
    "Patience of Job",
    "Pay on the nail",
    "Pay the piper",
    "Pay through the nose",
    "Pay your dues",
    "Peeping Tom",
    "Pen is mightier than the sword",
    "Pennies on the dollar",
    "Penny pincher",
    "Penny wise, pound foolish",
    "People who live in glass houses should not throw stones",
    "Pep talk",
    "Perish the thought",
    "Pet peeve",
    "Photo finish",
    "Pick up the tab",
    "Pick-up game",
    "Picture perfect",
    "Pie in the sky",
    "Piece of cake",
    "Pieces of the same cake",
    "Pig in a poke",
    "Pigs might fly",
    "Pin down with a label",
    "Pin money",
    "Pinch of salt",
    "Pink pound",
    "Pink slip",
    "Pipe dream",
    "Piping hot",
    "Place in the sun",
    "Plain as a pikestaff",
    "Plain as the nose on your face",
    "Plain Jane",
    "Plain sailing",
    "Plan B",
    "Plastic smile",
    "Play by ear",
    "Play fast and loose",
    "Play for keeps",
    "Play for time",
    "Play hard to get",
    "Play hardball",
    "Play havoc",
    "Play hooky",
    "Play into someone's hands",
    "Play out of your skin",
    "Play possum",
    "Play second fiddle",
    "Play the field",
    "Play the fool",
    "Play with fire",
    "Playing to the gallery",
    "Please revert",
    "Pleased as punch",
    "Poacher turned gamekeeper",
    "Poetry in motion",
    "Point the finger",
    "Pointy-heads",
    "Poison pill",
    "Poisoned chalice",
    "Poker face",
    "Polish the apples",
    "Polishing peanuts",
    "Politically correct",
    "Poor as a church mouse",
    "Pop the question",
    "Pop your clogs",
    "Pork barrel",
    "Pot calling the kettle black",
    "Pot-luck",
    "Pound of flesh",
    "Pour oil on troubled waters",
    "Powder your nose",
    "Powers that be",
    "Practical joke",
    "Practice what you preach",
    "Preaching to the choir",
    "Presence of mind",
    "Press the flesh",
    "Pressed for time",
    "Prick up your ears",
    "Prim and proper",
    "Primrose path",
    "Prince charming",
    "Problem is thirty",
    "Proclaim it from the rooftops",
    "Prodigal son",
    "Proof of the pudding is in the eating",
    "Pros and cons",
    "Proud as a peacock",
    "Pull a rabbit out of your hat",
    "Pull in the reins",
    "Pull no punches",
    "Pull numbers out of your ass",
    "Pull out all the stops",
    "Pull out of the fire",
    "Pull rank",
    "Pull someone's leg",
    "Pull strings",
    "Pull the fat from the fire",
    "Pull the other one, it's got brass bells on",
    "Pull the trigger",
    "Pull the wool over someone's eyes",
    "Pull up your socks",
    "Pull your chain",
    "Pull your finger out!",
    "Pull your punches",
    "Pull your weight",
    "Pull yourself up by your bootstraps",
    "Punching bag",
    "Pup's chance",
    "Puppy love",
    "Purple patch",
    "Push comes to shove",
    "Push the envelope",
    "Pushing up the daisies",
    "Put a bug in your ear",
    "Put a cork in it!",
    "Put a sock in it",
    "Put all your eggs in one basket",
    "Put it on the cuff",
    "Put lipstick on a pig",
    "Put more green into something",
    "Put on airs",
    "Put or get someone's back up",
    "Put some dirt on it",
    "Put somebody's nose out of joint",
    "Put someone on a pedestal",
    "Put someone out to pasture",
    "Put that in your pipe and smoke it",
    "Put the carriage before the horse",
    "Put the kybosh on",
    "Put the pedal to the metal",
    "Put to the sword",
    "Put two and two together",
    "Put up or shut up",
    "Put you in mind",
    "Put you in the picture",
    "Put your best foot forward",
    "Put your cards on the table",
    "Put your foot down",
    "Put your foot in it",
    "Put your foot in your mouth",
    "Put your hand on your heart",
    "Put your heads together",
    "Put your money where your mouth is",
    "Put your shoulder to the wheel",
    "Put your thumb on the scales",
    "Put yourself in someone's shoes",
    "Putting the cart before the horse",
    "Pyrrhic victory",
  ];

  final List _nameDescription = [
    "If a place is extremely crowded, people are packed like sardines, or packed in like sardines.",
    "(USA) If you paddle your own canoe, you do things for yourself without outside help.",
    "If someone is very annoying and always disturbing you, they are a pain in the neck. Pain in the butt, or pain in the ass (USA) are less polite alternative forms.",
    "If you go out for a night out with lots of fun and drinking, you paint the town red.",
    "(USA) If someone paints themselves into a corner, they get themselves into a mess.",
    "If you open a Pandora's box, something you do causes all sorts of trouble that you hadn't anticipated.",
    "If you paper over the cracks, you try to make something look or work better but only deal with superficial issues, not the real underlying problems.",
    "A paper tiger is a person, country, institution, etc, that looks powerful, but is actually weak.",
    "If something is par for the course, it is what you expected it would be. If it is above par, it is better, and if it is below par, it is worse.",
    "If you learn something parrot fashion, you learn it word for word.",
    "If something is part and parcel of your job, say, it is an essential and unavoidable part that has to be accepted.",
    "If something passes muster, it meets the required standard.",
    "If you pass the buck, you avoid taking responsibility by saying that someone else is responsible.",
    "If you pass the hat, you ask a person in a group to give money.",
    "If you pass the time of day with somebody, you stop and say hello, enquire how they are and other such acts of social politeness.",
    "If something requires the patience of Job, it requires great patience.",
    "If you pay on the nail, you pay promptly in cash.",
    "When you pay the piper, you have to accept the consequences of something that you have done wrong or badly.",
    "If you pay through the nose for something, you pay a very high price for it.",
    "If you have paid your dues, you have had your own struggles and earned your place or position.",
    "A peeping Tom is someone who tries to look through other people's windows without being seen in order to spy on people in their homes.",
    "The idiom means that words and communication are more powerful than wars and fighting.",
    "(USA) If something is pennies on the dollar, it's much cheaper than it  cost originally.",
    "A penny pincher is a mean person or who is very frugal.",
    "Someone who is penny wise, pound foolish can be very careful or mean with small amounts of money, yet wasteful and extravagant with large sums.",
    "People should not criticize other people for faults that they have themselves.",
    "When someone gives you a pep talk it is to build you up to help you accomplish something. In sports a coach might give a player a pep talk before the game to bolster his confidence. At work the boss might give you a pep talk to get you to do a better job.",
    "Perish the thought is an expression meaning that you really hope something will not happen.",
    "A pet peeve is something that irritates an individual greatly.",
    "A photo finish is when two contestants (usually in a race) finish at almost exactly the same time, making it difficult to determine the winner.",
    "A person who pays for everyone picks up the tab.",
    "(USA) A pick-up game is something unplanned where people respond to events as they happen.",
    "When something is exactly as it should be it is said to be picture perfect.",
    "If an idea or scheme is pie in the sky, it is utterly impractical.",
    "If something is a piece of cake, it is really easy.",
    "Pieces of the same cake are things that have the same characteristics or qualities.",
    "If someone buys a pig in a poke, they buy something without checking the condition it was in, usually finding out later that it was defective.",
    "If you think something will never happen or succeed, you can say that 'pigs might fly' (or 'pigs can fly' and 'pigs will fly'- the idiom is used in many forms)",
    "If you pin someone down with a label, you characterize them, often meant negatively as the label is restrictive.",
    "(UK) If you work for pin money, you work not because you need to but because it gives you money for extra little luxuries and treats.",
    "If what someone says should be taken with a pinch of salt, then they exaggerate and distort things, so what they say shouldn't be believed unquestioningly. ('with a grain of salt' is an alternative)",
    "(UK) In the UK, the pink pound is an idiom for the economic power of gay people.",
    "If someone receives a pink slip, they receive a letter telling them they have lost their job.",
    "A pipe dream is an unrealistic, impractical idea or scheme.",
    "If food is piping hot, it is very hot indeed.",
    "If you have your place in the sun, you find wealth, happiness or whatever you are looking for in life.",
    "(UK) If something is as plain as a pikestaff, it is very clear.",
    "If something is as plain as the nose on your face, it is very clear and obvious.",
    "A plain Jane is a woman who isn't particularly attractive.",
    "If something is relatively easy and there are no problems doing it, it is plain sailing.",
    "Plan b is an alternate or fall-back position or method when the initial attempt or plan goes wrong.",
    "When someone is wearing a plastic smile, they are appear to be happier with a situation or events than they actually are. This is actually a description of the forced smile you might see in many photographs.",
    "If you play by ear, you deal with something, without guidelines or rules. It refers to playing music without using written notation.",
    "If people play fast and loose, they behave in an irresponsible way and don't respect rules, etc.",
    "If you are playing for keeps, you take things very seriously and the outcome is very important to you; it is not a mere game.",
    "If you play for time, you delay something because you are not ready or need more time to think about it.  E.g. I knew I had to play for time until the police arrived.",
    "If someone plays hard to get, they pretend not to be interested or attracted by someone, usually to make the other person increase their efforts.",
    "If someone plays hardball, they are very aggressive in trying to achieve their aim.",
    "Playing havoc with something is creating disorder and confusion; computer viruses can play havoc with your programs.",
    "If people play hooky, they don't attend school when they should and don't have a valid reason for their absence.",
    "If you play into someone's hands, you do what they were expecting you to do and take advantage of this.",
    "If someone plays out of their skin, they give an outstanding performance.",
    "to pretend to be dead or sleeping. His younger sister jumped on him because she knew he was just playing possum.",
    "If you play second fiddle, you take a subordinate role behind someone more important.",
    "Someone who plays the field has sexual relationships with many people.",
    "If someone plays the fool, they behave in a silly way to make people laugh. ('Act the fool' is an alternative form)",
    "If people take foolish risks, they are playing with fire.",
    "If someone plays to the gallery, they say or do things that will make them popular at the expense of more important issues.",
    "(India) Please respond to me if the provided solution is incorrect or insufficient.",
    "When someone is pleased as punch, they are very satisfied about something.",
    "someone who gets a legitimate job which is the opposite of their previous one. E.G a computer hacker who helps to catch other hackers or an ex-bank robber who advises banks on security.",
    "something that is poetry in motion is beautiful to watch.",
    "When you point the finger at someone, you are accusing and blaming them for something.",
    "Pointy-heads are supposed intellectuals or experts, but who don't really know that much.",
    "A poison pill is a strategy designed to prevent a company from being take over.",
    "If someone is given a poisoned chalice, they are given a job or task which appears attractive but is actually doomed to failure or beset with problems that will damage their reputation or harm them.",
    "Someone with a poker face doesn't show any emotion or reaction so that people don't know what they are feeling.",
    "(USA) Someone who polishes the apples with someone, tries to get into that person's favor.",
    "To work very hard at something for little or no return. In other words, wasting time on work which will not yield reasonable value.",
    "Things or people that are politically correct use language that will not cause offence.",
    "If someone is as poor as a church mouse, they are very poor indeed.",
    "When someone pops the question, they ask someone to marry them.",
    "When someone pops their clogs, they die.",
    "Pork barrel politics involves investing money in an area to get political support rather than using the money for the common good.",
    "If someone hypocritically criticizes a person for something that they themselves do, then it is a case of the pot calling the kettle black.",
    "If you take pot-luck, you take whatever happens to be available at the time.",
    "If someone wants their pound of flesh, the force someone to pay or give back something owed, even though they don't need it and it will cause the other person a lot of difficulty.",
    "If someone pours oil on troubled waters, they try to calm things down.",
    "If somebody goes to powder your nose, it is a euphemism for going to the lavatory (toilet).",
    "The powers that be are the people who are in charge of something.",
    "A practical joke is a trick played on someone that is meant to be funny for people watching, though normally embarrassing for the person being tricked.",
    "If you practice what you preach, you do what you say other people should do.",
    "If someone preaches to the choir, they talking about a subject or issue with which their audience already agrees. ('Preaching to the converted' is an alternative form)",
    "If someone behaves calmly and rationally in difficult circumstances, they show presence of mind.",
    "When people, especially politicians, press the flesh, they meet members of the public and shake their hands, usually when trying to get support.",
    "If you are pressed for time, you are in a hurry or working against a very tight schedule.",
    "If you prick up your ears, you listen very carefully.  ('Pick up your ears' is also used)",
    "Someone who is prim and proper always behaves in the correct way and never breaks the rules of etiquette.",
    "The primrose path is an easy and pleasurable lifestyle, but one that ends in unpleasantness and problems.",
    "A prince charming is the perfect man in a woman's life.",
    "If a problem is 30, the problem is the person who sits 30 cm from the computer screen. It is used to describe people that lack technical knowledge and can be used when you insult someone who's having computer problems.",
    "If something is proclaimed from the rooftops, it is made as widely known and as public as possible.",
    "A prodigal son is a young man who wastes a lot on money on a lavish lifestyle. If the prodigal son returns, they return to a better way of living.",
    "This means that something can only be judged when it is tested or by its results. (It is often shortened to 'Proof of the pudding')",
    "Pros and cons are arguments for or against a particular issue. Pros are arguments which aim to promote the issue, while cons suggest points against it.",
    "Someone who is as proud as a peacock is excessively proud.",
    "If you pull a rabbit out of a hat, you do something that no one was expecting.",
    "When you pull in the reins, you slow down or stop something that has been a bit out of control.",
    "If you pull no punches, you hold nothing back.",
    "(USA) If someone pulls numbers out of their ass, they give unreliable or unsubstantiated figures to back their argument.",
    "If you pull out all the stops, you do everything you possibly can to achieve the result you want.",
    "(USA) If you pull something out of the fire, you save or rescue it.",
    "A person of higher position or in authority pulls rank; he or she exercises his/her authority, generally ending any discussion and ignoring other people's views.",
    "If you pull someone's leg, you tease them, but not maliciously.",
    "If you pull strings, you use contacts you have got to help you get what you want.",
    "If you pull the fat from the fire, you help someone in a difficult situation.",
    "This idiom is way of telling somebody that you don't believe them. The word 'brass' is optional.",
    "The person who pulls the trigger is the one who does the action that closes or finishes something.",
    "If you pull the wool over someone's eyes, you deceive or cheat them.",
    "If you aren't satisfied with someone and want them to do better, you can tell them to pull up their socks.",
    "(USA) If someone pulls your chain, they take advantage of you in an unfair way or do something to annoy you.",
    "(UK) If someone tells you to do this, they want you to hurry up. ('Get your finger out' is also used)",
    "If you pull your punches, you do not use all the power or authority at your disposal.",
    "If someone is not pulling their weight, they aren't making enough effort, especially in group work.",
    "If you pull yourself up by your bootstraps, you make the effort to improve things for yourself.",
    "A punching bag (or punch bag) is a person who gets a lot of unfair criticism.",
    "A pup's chance is no chance.",
    "Puppy love is love between two very young people.",
    "A purple patch is a period of time when someone or something is successful and doing well.",
    "If or when push comes to shove, the situation has become some bad that you are forced to do something: If push comes to shove, we'll just have to use our savings.",
    "This means to go to the limits, to do something to the maximum possible.",
    "If someone is said to be pushing up the daisies, they are dead.",
    "If you put a bug in someone's ear, you give him or her  a reminder or suggestion relating to a future event.",
    "This is a way of telling someone to be quiet.",
    "If someone tells you to put a sock in it, they are telling you to shut up.",
    "If you put all your eggs in one basket, you risk everything on a single opportunity which, like eggs breaking, could go wrong.",
    "If you put something on the cuff, you will take it now and pay for it later.",
    "If people put lipstick on a pig, they make superficial or cosmetic changes, hoping that it will make the product more attractive.",
    "(USA) To put more green into something is to spend more or to increase investment in it.",
    "If someone puts on airs, they pretend to be grander and more important than they really are.",
    "If you put or get someone's back up, you annoy them.",
    "This means that when you get hurt, you should rub it off or shake it off and you'll be ok.",
    "If you put someone's nose out of joint, you irritate them or make them angry with you.",
    "If you put someone on a pedestal, you admire them greatly, idolize them.",
    "If someone is put out to pasture, they are forced to resign or give up some responsibilities.",
    "This is used as an unsympathetic way of telling someone to accept what you have just said.",
    "If you put the carriage before the horse, you try to do things in the wrong order.",
    "To put an end to something.",
    "If you put the pedal to the metal, you go faster.",
    "If someone is put to the sword, he or she is killed or executed.",
    "If someone puts two and two together, they reach a correct conclusion from the evidence.",
    "'Put up or shut up' means you do something you are talking about or not to talk about it anymore.",
    "If something suggests something to you, it puts you in mind of that thing.",
    "If you put someone in the picture, you tell them the information they need to know about something.",
    "If you put your best foot forward, you try your best to do something.",
    "If you put your cards on the table, you make your thoughts or ideas perfectly clear.",
    "When someone puts their foot down, they make a firm stand and establish their authority on an issue.",
    "If you put your foot in it, you do or say something embarrassing and tactless or get yourself into trouble.",
    "If you put your foot in your mouth, you say something stupid or embarrassing.",
    "If you can out your hand on your heart, then you can say something knowing it to be true.",
    "If people put their head together, they exchange ideas about something.",
    "If someone puts their money where their mouth is, they back up their words with action.",
    "When you put your shoulder to the wheel, you contribute to an effort.",
    "If you put your thumb on the scales, you try to influence the result of something in your favor.",
    "If you put yourself in someone's shoes, you imagine what it is like to be in their position.",
    "When you put the cart before the horse, you are doing something the wrong way round.",
    "A Pyrrhic victory is one that causes the victor to suffer so much to achieve it that it isn't worth winning.",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'P',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
