import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class R extends StatelessWidget {
  final List _name = [
    "Rack and ruin",
    "Rack your brain",
    "Rags to riches",
    "Rain on your parade",
    "Raining cats and dogs",
    "Rainy day",
    "Raise Cain",
    "Raise eyebrows",
    "Rake over old coals",
    "Rake someone over the coals",
    "Rank and file",
    "Rat race",
    "Raw deal",
    "Read between the lines",
    "Read from the same page",
    "Read someone the riot act",
    "Real deal",
    "Real McCoy",
    "Real plum",
    "Real trouper",
    "Rearrange the deckchairs on the Titanic",
    "Recharge your batteries",
    "Recipe for disaster",
    "Red carpet",
    "Red herring",
    "Red letter day",
    "Red light district",
    "Red mist",
    "Red rag to a bull",
    "Reds under the bed",
    "Reduce to ashes",
    "Reinvent the wheel",
    "Renaissance man",
    "Rest on your laurels",
    "Revenge is sweet",
    "Rewrite history",
    "Rhyme or reason",
    "Rice missionary",
    "Rich man's family",
    "Ride for a fall",
    "Ride high",
    "Ride roughshod",
    "Ride shotgun",
    "Ride with the tide",
    "Right as rain",
    "Right out of the blocks",
    "Right royal",
    "Right up my alley",
    "Right up your street",
    "Ring a bell",
    "Ringside seat",
    "Rip van Winkle",
    "Rise and shine",
    "Rise from the ashes",
    "Rob Peter to pay Paul",
    "Rock the boat",
    "Rocket science",
    "Roll out the red carpet",
    "Roll with the punches",
    "Roll your eyes",
    "Rolling in money",
    "Rome was not built in a day",
    "Root hog or die poor",
    "Rooted to the spot",
    "Rose-colored glasses",
    "Rose-tinted glasses",
    "Rough and ready",
    "Rough around the edges",
    "Rough diamond",
    "Rough edges",
    "Rough end of the stick",
    "Rough-hewn",
    "Round the bend",
    "Round the houses",
    "Rub shoulders",
    "Rub someone up the wrong way",
    "Rue the day",
    "Ruffle a few feathers",
    "Rule of thumb",
    "Rule the roost",
    "Run a mile",
    "Run amok",
    "Run around the bush",
    "Run before you can walk",
    "Run circles around someone",
    "Run into the sand",
    "Run it up the flagpole and see if anyone salutes",
    "Run off your feet",
    "Run out of gas",
    "Run rings around someone",
    "Run something into the ground",
    "Run the gauntlet",
    "Run the show",
    "Run to ground",
    "Run your mouth off",
    "Run-of-the-mill",
    "Running on empty",
    "Running on fumes",
    "Runs in the family",
    "Russian roulette",
    "Rusty needle",
  ];

  final List _nameDescription = [
    "If something or someone goes to rack and ruin, they are utterly destroyed or wrecked.",
    "If you rack your brain, you think very hard when trying to remember something. ('Rack your brains' is an alternative)",
    "Someone who starts life very poor and becomes rich goes from rags to riches.",
    "If someone rains on your parade, they ruin your pleasure or your plans.",
    "When it is raining cats and dogs, it is raining very heavily.",
    "If you save something, especially money, for a rainy day, you save it for some possible problem or trouble in the future.",
    "(USA) If someone raises Cain, they make a big fuss publicly, causing a disturbance.",
    "If something raises eyebrows, it shocks or surprises people.",
    "(UK) If you go back to old problems and try to bring them back, making trouble for someone, you are raking over old coals.",
    "(USA) If you rake someone over the coals, you criticize or scold them severely.",
    "the rank and file are the ordinary members of a company, organization, etc, excluding the managers and directors.",
    "The rat race is the ruthless, competitive struggle for success in work, etc.",
    "If you get a raw deal, you are treated unfairly.",
    "If you read between the lines, you find the real message in what you're reading or hearing, a meaning that is not available from a literal interpretation of the words.",
    "When people are reading from the same page, they say the same things in public about an issue.",
    "If you read someone the riot act, you give them a clear warning that if they don't stop doing something, they will be in serious trouble.",
    "If something is the real deal, it is genuine and good.",
    "Something that's the real McCoy is the genuine article, not a fake.",
    "A real plum is a good opportunity.",
    "A real trouper is someone who will fight for what they believe in and doesn't give up easily. ",
    "(UK) If people are rearranging the deckchairs on the Titanic, they are making small changes that will have no effect as the project, company, etc, is in very serious trouble.",
    "If you recharge your batteries, you do something to regain your energy after working hard for a long time.",
    "A recipe for disaster is a mixture of people and events that could only possibly result in trouble.",
    "If you give someone the red-carpet treatment, you give them a special welcome to show that you think they are important.",
    "If something is a distraction from the real issues, it is a red herring.",
    "A red letter day is a one of good luck, when something special happens to you.",
    "The red light district is the area of a town or city where there is prostitution, sex shops, etc.",
    "If someone sees red or the red mist, they lose their temper and self-control completely.",
    "If something is a red rag to a bull, it is something that will inevitably make somebody angry or cross.",
    "An ironic allusion to the obsession some people have that there are reds (communists) everywhere plotting violent revolution.",
    "If something is reduced to ashes, it is destroyed or made useless. His infidelities reduced their relationship to ashes.",
    "If someone reinvents the wheel, they waste their time doing something that has already been done by other people, when they could be doing something more worthwhile.",
    "A Renaissance man is a person who is talented in a number of different areas, especially when their talents include both the sciences and the arts.",
    "If someone rests on their laurels, they rely on their past achievements, rather than trying to achieve things now.",
    "When you are happy to be proved right, then you know that revenge is sweet.",
    "If you rewrite history, you change your version of past events so as to make yourself look better than you would if the truth was told.",
    "If something is without rhyme or reason, it is unreasonable. ('Beyond rhyme or reason' is an alternative)",
    "A rice missionary gives food to hungry people as a way of converting them to Christianity.",
    "A rich man's family consists of one son and one daughter.",
    "If someone is riding for a fall, they are taking great risks that are likely to end in a disaster.",
    "If someone is riding high, they are very successful at the moment.",
    "If someone rides roughshod over other people, they impose their will without caring at all for other people's feelings.",
    "If you ride shotgun, you protect or guard something when it is being transported.",
    "If you ride with the tide, you accept the majority decision.",
    "If things are right as rain, then everything is going well in your life.",
    "This means immediately; at the very beginning.",
    "(UK) A right royal night out would be an extremely exciting, memorable and fun one.",
    "If something is right up your alley, it suits you perfectly.",
    "If something is ideal for you, it is right up your street.",
    "If something rings a bell, it reminds you of something you have heard before, though you may not be able to remember it very well. A name may ring a bell, so you know you have heard the name before, but cannot place it properly.",
    "If you have a ringside seat, you can observe something from a very close and clear position.",
    "Rip van Winkle is a character in a story who slept for twenty years, so if someone is a Rip van Winkle, they are behind the times and out of touch with what's happening now.",
    "If you wake up full of energy, you rise and shine.",
    "If something rises from the ashes, it recovers after a serious failure.",
    "If you rob Peter to pay Paul, you try to solve one problem, but create another in doing so, often through short-term planning.",
    "If you rock the boat, you destabilize a situation by making trouble. It is often used as advice; 'Don't rock the boat'.",
    "If something is not rocket science, it is not very complicated or difficult to understand. This idiom is normally used in the negative.",
    "you roll out the red carpet, you treat someone in a special way, especially when welcoming them.",
    "If you roll with the punches, you are flexible and able to adapt to difficult circumstances.",
    "If you roll your eyes, you show with your eyes that you don't believe someone or aren't interested in what they're saying.",
    "If someone has a lot of money, more than they could possibly need, they are rolling in money.",
    "This idiom means that many things cannot be done instantly, and require time and patience.",
    "(USA) It's a expression used in the Southern USA that means that you must look out for yourself as no one's going to do it for you.  (It can be shortened to 'root hog'.  A hog is a pig)",
    "If someone is rooted to the spot, they cannot move, either physically or they cannot think their way out of a problem.",
    "If people see things through rose-colored glasses, they see them in a more positive light than they really are.",
    "If people see things through rose-tinted glasses, they see them in a more positive light than they really are.",
    "If something is rough and ready, it has not been carefully prepared, but is fit for its purpose. If a person is rough and ready, they are not very refined or mannered.",
    "If someone is rough around the edges, they haven't mastered something, though they show promise.",
    "A rough diamond is a person who might be a bit rude but who is good underneath it all.",
    "If something has rough edges, it is still not a finished product and not all of a uniform standard.",
    "To get the rough end of the stick is to be treated unfairly or to come off worse than the other party in a transaction, situation or relationship.",
    "If something, especially something made from wood or stone, is rough-hewn, it is unfinished or unpolished.",
    "If someone has gone round the bend, they have stopped being rational about something. If something drives you round the bend, it irritates you or makes you angry.",
    "If you go round the houses, you do something in an inefficient way when there is a quicker, more convenient way.",
    "If you rub shoulders with people, you meet and spend time with them, especially when they are powerful or famous.",
    "If you annoy or irritate someone when you didn't mean to, you rub them up the wrong way.",
    "This means that the person will one day bitterly regret what they have done.",
    "If you ruffle a few feathers, you annoy some people when making changes or improvements.",
    "Rule of thumb means approximately.",
    "If someone rules the roost they are the boss. Example: There’s no doubt that who rules the roost in this house.",
    "If someone 'Runs a mile', they do everything they can to avoid a situation. Example: 'I was worried that he'd take one look at me and run a mile'",
    "When things or people are running amok, they are wild and out of control.('Run amuck' is also used)",
    "(USA) If you run around the bush, it means that you're taking a long time to get to the point.",
    "If someone tries to run before they can walk, they try to do something requiring a high level of knowledge before they have learned the basics.",
    "If you can run circles around someone, you are smarter and intellectually quicker than they are.",
    "If something runs into the sand, it fails to achieve a result.",
    "This idiom is used to suggest trying out an idea to see if people accept it.",
    "If you are run off your feet, you are extremely busy and don't have enough time to do everything.",
    "If a campaign, project, etc, runs out of gas, it loses energy and momentum, and progress slows or halts.",
    "If you run rings around someone, you are so much better than them that they have no chance of keeping up with you.",
    "If people run something into the ground, they treat or manage it so badly that they ruin it.",
    "If somebody is being criticized harshly by a lot of people, they are said to run the gauntlet.",
    "If someone runs the show, they like to be in control and make all the decisions.",
    "If you run someone or something to ground, you pursue until you capture or find them or it.",
    "If someone runs their mouth off, they talk too much.",
    "If something is run-of-the-mill, there is nothing exceptional about it- it is ordinary or average.",
    "If you are exhausted but keep going, you are running on empty.",
    "If someone has used all their energy on something, but must continue, they are running on fumes.",
    "If a characteristic runs in the family, it can clearly be seen members of different generations.  A hereditary illness that is passed from one generation to the next also runs in the family.",
    "If people take a dangerous and unnecessary risk, they are playing Russian roulette.",
    "When something is described as a rusty needle, it is badly damaged but still works, or if someone very is sick or tired but still manages to do things at a fairly good level. An alternative form is 'a tarnished needle'.",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'R',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
