import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class T extends StatelessWidget {
  final List _name = [
    "Tables are turned",
    "Tackle an issue",
    "Take a hike",
    "Take a leaf out of someone's book",
    "Take a nosedive",
    "Take a punch",
    "Take a rain check",
    "Take a straw poll",
    "Take by the scruff of the neck",
    "Take for a test drive",
    "Take for granted",
    "Take forty winks",
    "Take guts",
    "Take it in your stride",
    "Take it on the chin",
    "Take no prisoners",
    "Take sand to the beach",
    "Take someone down a peg",
    "Take someone for a ride",
    "Take someone to task",
    "Take someone to the woodshed",
    "Take someone under your wing",
    "Take the biscuit",
    "Take the bull by its horns",
    "Take the chair",
    "Take the fall",
    "Take the fifth",
    "Take the flak",
    "Take the floor",
    "Take the heat",
    "Take the Mickey",
    "Take the plunge",
    "Take the rough with the smooth",
    "Take to your heels",
    "Take up the torch",
    "Take your breath away",
    "Take your eye off the ball",
    "Take your hat off",
    "Taken as read",
    "Talk a blue streak",
    "Talk a glass eye to sleep",
    "Talk is cheap",
    "Talk nineteen to the dozen",
    "Talk of the town",
    "Talk out of the back of your head",
    "Talk shop",
    "Talk the hind legs off a donkey",
    "Talk the legs off an iron pot",
    "Talk turkey",
    "Talk your arm off",
    "Talking to a brick wall",
    "Tall drink of water",
    "Tall order",
    "Tall story",
    "Tally ho!",
    "Tar baby",
    "Tar with the same brush",
    "Taste blood",
    "Taste of your own medicine",
    "Teach your grandmother to suck eggs",
    "Teacher's pet",
    "Tear your hair out",
    "Tears before bedtime",
    "Teeny-weeny",
    "Teething problems",
    "Tell them where the dog died",
    "Tempest in a teapot",
    "Tempt providence",
    "Ten a penny",
    "Test the waters",
    "That and 50 cents will buy you a cup of coffee",
    "That dog won't hunt",
    "That is the way the cookie crumbles",
    "That makes two of us",
    "That ship has sailed",
    "That's all she wrote",
    "The apple does not fall far from the tree",
    "The ball's in your court",
    "The be all and end all",
    "The bigger they are, the harder they fall",
    "The cat's meow",
    "The common weal",
    "The grass is always greener",
    "The line forms on the right",
    "The more the merrier",
    "The penny dropped",
    "The plot thickens",
    "The rough and tumble",
    "The short straw",
    "The sun might rise in the west",
    "The whole shooting match",
    "The world and his wife",
    "Their bark is worse than their bite",
    "There are many ways to skin a cat",
    "There's never a road without a turning",
    "There's no such thing as a free lunch",
    "There's the rub",
    "Thick and fast",
    "Thick as mince",
    "Thick as thieves",
    "Thick-skinned",
    "Thin as a rake",
    "Thin end of the wedge",
    "Thin line",
    "Thin-skinned",
    "Think outside the box",
    "Think the world of",
    "Third degree",
    "Third rail",
    "Third time's the charm",
    "Thorn in your side",
    "Those who live by the sword die by the sword",
    "Three sheets in the wind",
    "Thrilled to bits",
    "Through gritted teeth",
    "Through the ceiling",
    "Through the floor",
    "Through thick and thin",
    "Throw a curve",
    "Throw a monkey wrench into the works",
    "Throw a sickie",
    "Throw caution to the wind",
    "Throw down the gauntlet",
    "Throw in the towel",
    "Throw pearls to the pigs",
    "Throw someone a bone",
    "Throw someone a line",
    "Throw someone in at the deep end",
    "Throw someone to the wolves",
    "Throw someone under the bus",
    "Throw the baby out with the bath water",
    "Throw the book at someone",
    "Throw your hat in the ring",
    "Throw your toys out of the pram",
    "Throw your weight around",
    "Thumb your nose at",
    "Thumbs down & thumbs up",
    "Tickle your fancy",
    "Tickled pink",
    "Tidy desk, tidy mind",
    "Tie the knot",
    "Tied to your mother's apron strings",
    "Tight rein",
    "Tight ship",
    "Tighten your belt",
    "Till the cows come home",
    "Till the pips squeak",
    "Till you're blue in the face",
    "Tilt at windmills",
    "Time and again",
    "Time and tide wait for no man",
    "Time does sail",
    "Time flies",
    "Time is on my side",
    "Time of your life",
    "Time-honored practice",
    "Tip of the iceberg",
    "Tipping point",
    "Tired and emotional",
    "Tit for tat",
    "To a fault",
    "To a man",
    "To a T",
    "To all intents and purposes",
    "To be as thick as two bricks",
    "To be dog cheap",
    "To err is human, to forgive divine",
    "To have the courage of your convictions",
    "To little avail",
    "To the end of time",
    "Toe the line",
    "Tomorrow's another day",
    "Tongue in cheek",
    "Too big for your boots",
    "Too big for your britches",
    "Too many chiefs and not enough Indians",
    "Too many cooks spoil the broth",
    "Too many irons in the fire",
    "Toot you own horn",
    "Top dog",
    "Top notch",
    "Touch and go",
    "Touch base",
    "Touch wood",
    "Tough as old boots",
    "Tough cookie",
    "Tough luck",
    "Tough nut to crack",
    "Tough row to hoe",
    "Trade barbs",
    "Traffucked",
    "Trail your coat",
    "Train of thought",
    "Tread on someone's toes",
    "Tread the boards",
    "Tread water",
    "Treasure trove",
    "Tried and tested",
    "True blue",
    "True colors",
    "Trump card",
    "Truth will out",
    "Tug at the heartstrings",
    "Turf war",
    "Turn a blind eye",
    "Turn a deaf ear",
    "Turn a new leaf",
    "Turn something on its head",
    "Turn the crack",
    "Turn the other cheek",
    "Turn turtle",
    "Turn up like a bad penny",
    "Turn up one's toes to the daisies",
    "Turn water into wine",
    "Turn your nose up",
    "Turn-up for the books",
    "Twenty-four seven",
    "Twinkling of an eye",
    "Twist someone's arm",
    "Twisting in the wind",
    "Two cents",
    "Two heads are better than one",
    "Two left feet",
    "Two peas in a pod",
    "Two sides of the same coin",
    "Two-edged sword",
    "Two-faced",
  ];

  final List _nameDescription = [
    "When the tables are turned, the situation has changed giving the advantage to the party who had previously been at a disadvantage.",
    "If you tackle an issue or problem, you resolve or deal with it.",
    "This is a way of telling someone to get out.",
    "If you take a leaf out of someone's book, you copy something they do because it will help you.",
    "When things take a nosedive, they decline very quickly and head towards disaster.",
    "If somebody takes a punch, something bad happens to them.",
    "If you take a rain check, you decline an offer now, suggesting you will accept it later. ('Raincheck' is also used)",
    "If you take a straw poll, you sound a number of people out to see their opinions on an issue or topic.",
    "If you take something by the scruff on the neck, you take complete control of it.",
    "If you take something for a test drive, you try something to see if you like it.",
    "If you take something for granted, you don't worry or think about it because you assume you will always have it.  If you take someone for granted, you don't show your appreciation to them.",
    "If you take forty winks, you have a short sleep.",
    "If something takes guts, it requires courage in the face of danger or great risk. It takes guts for firemen to enter a burning building to save someone.",
    "If you take something in your stride, you deal with it even though it is difficult or unpleasant without letting it bother or upset you.",
    "If you take something on the chin, something bad happens to you and you take it directly without fuss.",
    "If people take no prisoners, they do things in a very aggressive way, without considering any harm they might do to achieve their objectives.",
    "Doing something that is completely pointless or unnecessary is like taking sand to the beach.",
    "If someone is taken down a peg , they lose status in the eyes of others because of something they have done wrong or badly.",
    "If you are taken for a ride, you are deceived by someone.",
    "If you take someone to task, you scold them for something they have done wrong.",
    "If someone is taken to the woodshed, they are punished for something they have done.",
    "If you take someone under your wing, you look after them while they are learning something.",
    "(UK) If something takes the biscuit, it is remarkable or foolish of its kind.",
    "Taking a bull by its horns would be the most direct but also the most dangerous way to try to compete with such an animal. When we use the phrase in everyday talk, we mean that the person we are talking about tackles their problems directly and is not worried about any risks involved.",
    "If you take the chair, your become the chairman or chairwoman of a committee, etc.",
    "If you take the fall, you accept the blame and possibly the punishment for another's wrongdoing.",
    "(USA) If you do not want to answer a question you can take the fifth, meaning you are choosing not to answer.",
    "If you take the flak, you are strongly criticized for something. ('Take flak' is also used)",
    "Start talking or giving a speech to a group.",
    "If you take the heat, you take the criticism or blame for something you didn't do, normally to protect the guilty person.",
    "(UK) If you take the Mickey, you tease someone. ('Take the Mick' is also used)",
    "If you take the plunge, you decide to do something or commit yourself even though you know there is an element of risk involved.",
    "People say that you have to take the rough with the smooth, meaning that you have to be prepared to accept the disadvantages as well of the advantages of something.",
    "If you take to your heels, you run away.",
    "If you take up the torch, you take on a challenge or responsibility, usually when someone else retires, or leaves an organization, etc.",
    "If something takes your breath away, it astonishes or surprises you.",
    "If someone takes their eye off the ball, they don't concentrate on something important that they should be looking at.",
    "If you say that you take your hat off to someone, you are showing your respect or admiration.",
    "If something can be taken as read, it is so definite that it's not necessary to talk about it.",
    "(USA) If someone talks a blue streak, they speak quickly and at length. ('Talk up a blue streak' is also used)",
    "Someone who could talk a glass eye to sleep is very boring and repetitive.",
    "It's easy to talk about something but harder to actually do it.",
    "If someone talks very quickly, they talk nineteen to the dozen.",
    "When everybody is talking about particular people and events, they are the talk of the town.",
    "If someone is talking out of the back of their head, they are talking rubbish.",
    "If you talk shop, you talk about work matters, especially if you do this outside work.",
    "A person who is excessively or extremely talkative can talk the hind legs off a donkey.",
    "(AU) Somebody who is excessively talkative or is especially convincing is said to talk the legs off an iron pot. ('Talk the legs off an iron chair' is also used)",
    "When people talk turkey, they discuss something frankly.",
    "Someone who talks so much that it is a strain to listen can talk your arm off.",
    "If you talk to someone and they do not listen to you, it is like talking to a brick wall.",
    "Someone who is very tall and slender is a tall drink of water. ('A tall glass of water' is also used)",
    "Something that is likely to be hard to achieve or fulfill is a tall order.",
    "A tall story is one that is untrue and unbelievable.",
    "(UK) This is an exclamation used for encouragement before doing something difficult or dangerous.",
    "A tar baby is a problem that gets worse when people try to sort it out.",
    "If people are tarred with the same brush, they are said to have the same set of attributes or faults as someone they are associated with.",
    "If someone has tasted blood, they have achieved something and are encouraged to think that victory is within their grasp.",
    "If you give someone a taste of their own medicine, you do something bad to someone that they have done to you to teach them a lesson.",
    "When people say 'don't teach your grandmother to suck eggs', they mean that people shouldn't try to teach someone who has experience or is an expert in that area.",
    "The teacher's favorite pupil is the teacher's pet, especially if disliked by the other pupils.",
    "If someone is tearing their hair out, they are extremely worried or agitated about something.",
    "(UK) This idiom is used when something seems certain to go wrong or cause trouble.",
    "If something is teeny-weeny, it is very small indeed. ('teensie-weensie' is also used)",
    "(UK) The problems that a project has when it is starting are the teething problems.",
    "(USA) If you tell them where the dog died, you strongly and sharply correct someone.",
    "If people exaggerate the seriousness of a situation or problem, they are making a tempest in a teapot.",
    "If you tempt providence, you take a risk that may well have unpleasant consequences. ('Tempt fate' is also used)",
    "(UK) If something is ten a penny, it is very common. ('Two a penny' is also used)",
    "If you test the waters, or test the water, you experiment to see how successful or acceptable something is before implementing it.",
    "(USA) This is used to describe something that is deemed worthless. 'He's got a Ph.D. in Philosophy.' 'So? That and 50 cents will buy you a cup of coffee.'",
    "(USA) Very common Southern US expression meaning: What you say makes no sense.",
    "'That's the way the cookie crumbles' means that things don't always turn out the way we want.",
    "A speaker says 'that makes two of us' to indicate agreement with what another speaker just said. For example, I can say, 'I wish I would win the lottery.' A listener who says 'That makes two of us' is indicating the he or she wants to win the lottery, too.",
    "A particular opportunity has passed you by when that ship has sailed.",
    "(USA) This idiom is used to show that something has ended and there is nothing more to say about something.",
    "Offspring grow up to be like their parents.",
    "If somebody says this to you, they mean that it's up to you to decide or take the next step.",
    "the phrase 'The be all and end all' means that a something is the final, or ultimate outcome or result of a situation or event.",
    "This idiom means that the more powerful have more to lose, so when they suffer something bad, it is worse for them.",
    "If something is the cat's meow, it's excellent.",
    "If something is done for the common weal, it is done in the interests and for the benefit of the majority or the general public.",
    "This idiom means that what other people have or do looks preferable to our life. The complete phrase is 'The grass is always greener on the other side of the fence'.",
    "Something's meaning is becoming clear when the line forms on the right.",
    "The more the merrier means that the greater the quantity or the bigger the number of something, the happier the speaker will be.",
    "When the penny drops, someone belatedly understands something that everyone else has long since understood.",
    "When the plot thickens, a situation become more complicated and difficult.",
    "The rough and tumble refers to areas of life like business, sports, politics, etc, where competition is hard and people will take any advantage that they can.",
    "If you take the short straw, you lose a selection process, which means that you have to do something unpleasant.",
    "When people say this, they mean that they don't expect something to happen.",
    "Everything, the entire object, or all the related parts.",
    "If the world and his wife were somewhere, then huge numbers of people were present.",
    "If someone's bark is worse than their bite, they get angry and shout and make threats, but don't actually do anything.",
    "This is an expression meaning there are many different ways of doing the same thing.",
    "No situation in life stays the same forever.",
    "This idiom means that you don't get things for free, so if something appears to be free, there's a catch and you'll have to pay in some way.",
    "The meaning of this idiom is 'that's the problem'.",
    "If things are happening thick and fast, they are happening so fast they seemed to be joined together.",
    "(UK) If someone is as thick as mince, they are very stupid indeed.",
    "If people are thick as thieves, they are very close friends who have no secrets from each other.",
    "If a person is thick-skinned, they are not affected by criticism.",
    "A rake is a garden tool with a long, thin, wooden handle, so someone very thin is thin as a rake.",
    "The thin end of the wedge is something small and seemingly unimportant that will lead to something much bigger and more serious.",
    "If there's a thin line between things, it's hard to distinguish them.",
    "If somebody is thin-skinned, they are very sensitive to any sort of criticism.",
    "If you think outside the box, you think in an imaginative and creative way.",
    "To hold something or someone in very high esteem, to love or admire immensely.",
    "If someone is given the third degree, they are put under a great deal of pressure and intimidation to force them to tell the truth about something.",
    "The third rail of something is dangerous to alter or change. Originally, the third rail is the one carrying the electricity for a train.",
    "This is used when the third time one tries something, one achieves a successful outcome.",
    "A thorn in your side is someone or something that causes trouble or makes life difficult for you.",
    "this means that violent people will be treated violently themselves.",
    "(UK) Someone who is three sheets in the wind is very drunk. ('Three sheets to the wind' is also used.  'Seven sheets' is an alternative number used)",
    "If you are thrilled to bits, you are extremely pleased or excited about something.",
    "If you do something through gritted teeth, you accept or agree with it against your will and it is obvious to others how you really feel.",
    "If prices go through the ceiling, they rise very quickly.",
    "If prices go, or fall, through the floor, they fall very quickly.",
    "If someone supports you through thick and thin, they support you during good times and bad.",
    "(USA) If you throw someone a curve, you surprise them with something they find difficult to deal with. ('Throw' a curveball' is also used)",
    "(USA) If you throw a monkey wrench into the works, you ensure that something fails.",
    "If you pretend to be ill to take a day off work or school, you throw a sickie.",
    "When people throw caution to the wind, they take a great risk.",
    "Throw down the gauntlet is to issue a challenge to somebody.",
    "If you throw in the towel, you admit that you are defeated or cannot do something.",
    "Someone that throws pearls to pigs is giving someone else something they don't deserve or appreciate. ('Throw pearls before pigs' and 'Cast pearls before swine' are also used)",
    "If you throw someone a bone, you give them a small reward or some kind words to make them feel good even if they've not really contributed much.",
    "If someone throws you a line, they give you help when you are in serious difficulties.",
    "If you are thrown in at the deep end, you have to deal with serious issues the moment you start something like a job, instead of having time to acquire experience.",
    "If someone is thrown to the wolves, they are abandoned and have to face trouble without any support.",
    "To throw someone under the bus is to get the person in trouble either by placing blame on that person or not standing up for him.",
    "If you get rid of useful things when discarding inessential things, you throw the baby out with the bath water.",
    "If you throw the book at someone, you punish them as severely as possible.",
    "If someone throws their hat in the ring, they announce that they want to take part in a competition or contest. 'Toss your hat in the ring' is an alternative.",
    "To make an angry protest against a relatively minor problem, in the process embarrassing the protester. The analogy is with a baby who throws toys out of the pram in order to get their parent to pay attention to them. The implication in the idiom is that the protester is acting like a baby.",
    "If someone throws their weight around, they use their authority or force of personality to get what they want in the face of opposition.",
    "If you thumb your nose at something, you reject it or scorn it.",
    "If something gets the thumbs up, it gets approval, while the thumbs down means disapproval.",
    "If something tickles your fancy, it appeals to you and you want to try it or have it.",
    "If you are very pleased about something, you are tickled pink.",
    "A cluttered or disorganized environment will affect your clarity of thought. Organized surroundings and affairs will allow for clearer thought organization.",
    "When people tie the knot, they get married.",
    "Describes a child (often a boy) who is so used to his mother's care that he or she cannot do anything on his or her own.",
    "If things or people are kept on a tight rein, they are given very little freedom or controlled carefully.",
    "If you run a tight ship, you control something strictly and don't allow people much freedom of action.",
    "If you have to tighten your belt, you have to economize.",
    "This idioms means 'for a very long time'. ('Until the cows come home' is also used)",
    "If someone will do something till the pips squeak, they will do it to the limit, even though it will make other people suffer.",
    "If you do something till you're blue in the face, you do it repeatedly without achieving the desired result until you're incredibly frustrated.",
    "A person who tilts at windmills, tries to do things that will never work in practice.",
    "If something happens time and again, it happens repeatedly. ('Time and time again' is also used)",
    "This is used as a way of suggestion that people should act without delay.",
    "This idioms means that time passes by unnoticed.",
    "This idiom means that time moves quickly and often unnoticed.",
    "If time is on your side, you have the luxury of not having to worry about how long something will take.",
    "If you're having the time of your life, you are enjoying yourself very much indeed.",
    "A time-honored practice is a traditional way of doing something that has become almost universally accepted as the most appropriate or suitable way.",
    "The tip of the iceberg is the part of a problem that can be seen, with far more serious problems lying underneath.",
    "Small changes may have little effect until they build up to critical mass, then the next small change may suddenly change everything. This is the tipping point.",
    "(UK) This idiom is a euphemism used to mean 'drunk'.",
    "If someone responds to an insult by being rude back, it's tit for tat- repaying something negative the same way.",
    "If something does something to a fault, they do it excessively. So someone who is generous to a fault is too generous.",
    "If a group of people does, believes, thinks, etc, something to a man, then they all do it.",
    "If something is done to a T, it is done perfectly.",
    "This means in all the most important ways.",
    "Someone who is as thick as two bricks is really stupid.",
    "If something's dog cheap, it is very cheap indeed.",
    "This idiom is used when someone has done something wrong, suggesting that they should be forgiven.",
    "If you have the courage of your convictions, you are brave enough to do what you feel is right, despite any pressure for you to do something different.",
    "If something is to little avail, it means that, despite great efforts, something ended in failure, but taking comfort from the knowledge that nothing else could have been done to avert or avoid the result.",
    "To the end of time is an extravagant way of saying 'forever'.",
    "If someone toes the line, they follow and respect the rules and regulations.",
    "This means that things might turn out better or that there might be another opportunity in the future.",
    "If something is tongue in cheek, it isn't serious or meant to be taken seriously.",
    "If someone is too big for their boots, they are conceited and have an exaggerated sense of their own importance.",
    "If someone is too big for their britches, they are conceited and have an exaggerated sense of their own importance.",
    "When there are too many chiefs and not enough Indians, there are too many managers and not enough workers to work efficiently.",
    "This means that where there are too many people trying to do something, they make a mess of it.",
    "This means juggling too many projects at once and something's bound to fail; when a smith had too many irons in his fire, he couldn't effectively keep track of all of them.",
    "If someone toot their own horn, they like to boast about their achievements.",
    "The most important or influential person is the top dog.",
    "If something is top notch, it's excellent, of the highest quality or standard.",
    "If something is touch and go, the result is uncertain and could be good or bad.",
    "If you touch base with someone, you contact them.",
    "This idiom is used to wish for good luck. ('Knock on wood' is also used)",
    "Something or someone that is as tough as old boots is strong and resilient.",
    "A tough cookie is a person who will do everything necessary to achieve what they want.",
    "Tough luck is bad luck.",
    "If something is a tough nut to crack, it is difficult to find the answer or solution. When used about a person, it means that it is difficult to get them to do or allow what you want. 'Hard nut to crack' is an alternative.",
    "(USA) A tough row to hoe is a situation that is difficult to handle. ('A hard row to hoe' is an alternative form)",
    "If people trade barbs, they insult or attack each other.",
    "If you are traffucked, you are stuck in heavy traffic and get where you need to be.",
    "If you trail your coat, you act in a provocative way.",
    "A train of thought is a sequence of thoughts, especially when you are talking to someone and you forget what you were going to say.",
    "If you tread on someone's toes, you upset them.",
    "When someone treads the boards, they perform on stage in a theatre.",
    "If someone is treading water, they are making no progress.",
    "Something of great value or a very good source.",
    "If a method has been tried and tested, it is known to work or be effective because it has been successfully used long enough to be trusted.",
    "A person who is true blue is loyal and dependable, someone who can be relied on in all circumstances.",
    "If someone shows their true colors, they show themselves as they really are.",
    "A trump card is a resource or strategy that is held back for use at a crucial time when it will beat rivals or opponents.",
    "Truth will out means that, given time, the facts of a case will emerge no matter how people might try to conceal them.",
    "if something tugs at the heartstrings, it makes you feel sad or sympathetic towards it.",
    "If people or organizations are fighting for control of something, it is a turf war.",
    "When people turn a blind eye, they deliberately ignore something, especially if people are doing something wrong.",
    "If someone turns a deaf ear to you, they don't listen to you.",
    "If someone turns a new leaf, they change their behavior and stop doing wrong or bad things.",
    "If you turn something on its head, you turn it upside down or reverse it.",
    "(Scot) If you turn the crack, you change the subject of a conversation.",
    "If you turn the other cheek, you are humble and do not retaliate or get outwardly angry when someone offends or hurts you, in fact, you give them the opportunity to re-offend instead and compound their unpleasantness.",
    "If something turns turtle, it turns upside down.",
    "If someone turns up like a bad penny, they go somewhere where they are not wanted.",
    "If someone has turned up their toes to the daisies, it means that the person died.",
    "If someone turns water into wine, they transform something bad into something excellent.",
    "If someone turns their nose up at something, they reject it or look down on it because they don't think it is good enough for them.",
    "A turn-up for the books is an unexpected or surprising event.",
    "Twenty-four seven or 24/7 means all the time, coming from 24 hours a day, 7 days a week.",
    "If something happens in the twinkling of an eye, it happens very quickly.",
    "If you twist someone's arm, you put pressure on them to try to make them do what you want them to do.",
    "If you are twisting in the wind, you are without help or support - you are on your own.",
    "If you add or throw in your two cents, you give your opinion on an issue.",
    "When two people work together more things get accomplished.",
    "A person with two left feet can't dance.",
    "If things or people are like two peas in a pod, they look very similar or are always together.",
    "If two things are two sides of the same coin, there is much difference between them.",
    "If someone uses an argument that could both help them and harm them, then they are using a two-edged sword; it cuts both ways.",
    "Someone who is two-faced will say one thing to your face and another when you're not there.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'T',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
