import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class U extends StatelessWidget {
  final List _name = [
    "U-turn",
    "Ugly as a stick",
    "Ugly duckling",
    "Uncalled for",
    "Uncharted waters",
    "Uncle Sam",
    "Under a cloud",
    "Under a flag of convenience",
    "Under false colors",
    "Under fire",
    "Under lock and key",
    "Under someone's heel",
    "Under the radar",
    "Under the table",
    "Under the weather",
    "Under the wire",
    "Under your belt",
    "Under your breath",
    "Under your nose",
    "Under your skin",
    "Under your thumb",
    "Uneasy lies the head that wears the crown",
    "Unwavering loyalty",
    "Up a gum tree",
    "Up a river without a paddle",
    "Up for grabs",
    "Up in the air",
    "Up sticks",
    "Up the ante",
    "Up the creek",
    "Up the duff",
    "Up the spout",
    "Up the stick",
    "Up the wall",
    "Up the wooden hill",
    "Up to scratch",
    "Up to snuff",
    "Up to speed",
    "Up to the eyes",
    "Up to the neck",
    "Up to your eyes",
    "Up to your neck",
    "Up with the lark",
    "Upper crust",
    "Upper hand",
    "Upset the apple cart",
  ];

  final List _nameDescription = [
    "If a government changes its position radically on an issue, especially when they have promised not to do so, this is a U-turn.",
    "(USA) If someone is as ugly as a stick, they are very ugly indeed.",
    "a person who turns out to be beautiful or talented against all expectations.",
    "If someone does something bad and unnecessary without consideration for another’s feelings, what they do is uncalled for.",
    "If you're in uncharted waters, you are in a situation that is unfamiliar to you, that you have no experience of and don't know what might happen. ('Unchartered waters' is an incorrect form that is a common mistake)",
    "(USA) Uncle Sam is the government of the USA.",
    "If someone is suspected of having done something wrong, they are under a cloud.",
    "If a ship sails under a flag of convenience, it is registered in a country where taxes, etc, are lower than in the country it comes from, so if someone does something under a flag of convenience, they attempt to avoid regulations and taxes by a similar means.",
    "If someone does something under false colours/colors, they pretend to be something they are not in order to deceive people so that they can succeed.",
    "If someone is being attacked and criticized heavily, they are under fire.",
    "If something is under lock and key, it is stored very securely.",
    "If you are under someone's heel, they have a complete control over you.",
    "If something slips under the radar, it isn't detected or noticed.",
    "Bribes or illegal payments are often described as money under the table.",
    "If you are feeling a bit ill, sad or lack energy, you are under the weather.",
    "(USA) If a person does something under the wire, they do it at the last possible moment.",
    "If you have something under your belt, you have already achieved or experienced it and it will probably be of benefit to you in the future.",
    "If you say something under your breath, you whisper or say it very quietly.",
    "If something happens right in front of you, especially if it is surprising or audacious, it happens under your nose.",
    "If someone gets under your skin, they really annoy you.",
    "Someone who is manipulated or controlled by another person is under his or her thumb.",
    "This means that people with serious responsibilities have a heavy burden.",
    "Unwavering loyalty does not question or doubt the person or issue and supports them completely.",
    "(AU) If you're up a gum tree, you're in trouble or a big mess.",
    "If you up a river without a paddle, you are in an unfortunate situation, unprepared and with none of the resources to remedy the matter.",
    "If something is up for grabs, it is available and whoever is first or is successful will get it.",
    "If a matter is up in the air, no decision has been made and there is uncertainty about it.",
    "(UK) If you up sticks, you leave somewhere, usually permanently and without warning- he upped sticks and went to work abroad.",
    "If you up the ante, you increase the importance or value of something, especially where there's an element of risk as the term comes from gambling, where it means to increase the stake (the amount of money bet).",
    "If someone or something is up the creek, they are in real trouble. 'Up the creek without a paddle' is an alternative, and 'up shit creek (without a paddle)' is a ruder form.",
    "(UK) If a woman is up the duff, she's pregnant.",
    "(UK) If something has gone up the spout, it has gone wrong or been ruined.",
    "(UK) If a woman is up the stick, she's pregnant.",
    "If someone goes up the wall, they get very angry.",
    "When you go up the wooden hill, you go up the stairs to bed.",
    "If something doesn't come up to scratch, it doesn't meet the standard required or expected.",
    "If something isn't up to snuff, it doesn't meet the standard expected.",
    "If you bring someone up to speed, you update them on something.",
    "You are up to your eyes in something, you are deeply involved or to have too much of something like work. ('Up the neck', 'up to the eyeballs' and 'up to the ears' are also used)",
    "If someone's in something up to the neck, they are very involved in it, especially when it's something wrong.",
    "When you've got too much work to do, you're up to your eyes in it.",
    "If someone is very involved in something, they are up to their neck in it, especially if it is something bad or immoral.",
    "If you get up very early, you're up with the lark.",
    "The upper crust are the upper classes and the establishment.",
    "If you have the upper hand, you have the advantage.",
    "If you upset the apple cart, you cause trouble and upset people.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'U',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
