import 'package:flutter/material.dart';
import 'package:flutter_english_edioms_app/content_screen/content_screen.dart';

class W extends StatelessWidget {
  final List _name = [
    "Wait for a raindrop in the drought",
    "Wake up and smell the coffee",
    "Wake-up call",
    "Walk a fine line",
    "Walk a mile in my shoes",
    "Walk a tightrope",
    "Walk on eggshells",
    "Walk the green mile",
    "Walk the plank",
    "Walking encyclopedia",
    "Walking on air",
    "Walking on broken glass",
    "Walking time-bomb",
    "Wallflower",
    "War chest",
    "War of words",
    "Warm the cockles of your heart",
    "Warpath",
    "Warts and all",
    "Wash your hands of something",
    "Waste not, want not",
    "Waste of skin",
    "Watch grass grow",
    "Watch your six",
    "Watching paint dry",
    "Water over the dam",
    "Water under the bridge",
    "Watering hole",
    "Watery grave",
    "Weak at the knees",
    "Wear your heart on your sleeve",
    "Weather a storm",
    "Wedge politics",
    "Weight off your shoulders",
    "Well-heeled",
    "Well-oiled",
    "Well-oiled machine",
    "Were you born in a barn?",
    "Wet behind the ears",
    "Wet blanket",
    "Wet your whistle",
    "Whale of a time",
    "What can sorry do?",
    "What can you expect from a hog but a grunt?",
    "What does that have to do with the price of tea in China?",
    "What goes around comes around",
    "What will be will be",
    "What's cooking?",
    "What's good for the goose is good for the gander",
    "What's your poison?",
    "What's your take on that?",
    "Whatever floats your boat",
    "Wheels fall off",
    "When hell freezes over",
    "When in Rome, do as the Romans do",
    "When it rains, it pours",
    "When pigs fly",
    "When the chickens come home to roost",
    "Where the rubber meets the road",
    "Where there's a will, there's a way",
    "Where there's muck, there's brass",
    "Where there's smoke, there's fire",
    "Whet your appetite",
    "Which came first the chicken or the egg?",
    "While the cat's away, the mouse will play",
    "Whistle for it",
    "Whistle-stop tour",
    "Whistling Dixie",
    "Whistling in the dark",
    "Whistling past the graveyard",
    "White as a sheet",
    "White as snow",
    "White elephant",
    "White feather",
    "White lie",
    "White-bread",
    "Who wears the pants?",
    "Who wears the trousers?",
    "Who will ring the bell?",
    "Whole ball of wax",
    "Whole kit and caboodle",
    "Whole new ball game",
    "Whole nine yards",
    "Whole shebang",
    "Why buy the cow when you can get the milk for free",
    "Why keep a dog and bark yourself?",
    "Wide berth",
    "Wide of the mark",
    "Wild goose chase",
    "Will never fly",
    "Will-o'-the-wisp",
    "Win by a nose",
    "Window dressing",
    "Window to the soul",
    "Wing and a prayer",
    "Winner takes all",
    "Wipe the floor with",
    "Wipe the smile of someone's face",
    "With a heavy hand",
    "With child",
    "With flying colours (colors)",
    "With friends like that, who needs enemies?",
    "Wither on the vine",
    "Within a whisker",
    "Without a hitch",
    "Woe betide you",
    "Woe is me",
    "Wolf in sheep's clothing",
    "Wood for the trees",
    "Word of mouth",
    "Words fail me",
    "Work like a charm",
    "Work like a dog",
    "Work the system",
    "Work your fingers to the bone",
    "Work your socks off",
    "Work your tail off",
    "World at your feet",
    "World is your oyster",
    "Worm information",
    "Worm's eye view",
    "Worse for wear",
    "Worse things happen at sea",
    "Worth a shot",
    "Worth your salt",
    "Wrap yourself in the flag",
    "Wrench in the works",
    "Writ large",
    "Write your own ticket",
    "Writing on the wall",
    "Written all over your face",
    "Written in stone",
    "Wrong end of the stick",
    "Wrong foot",
  ];

  final List _nameDescription = [
    "When someone is waiting for a raindrop in the drought, they are waiting or hoping for something that is extremely unlikely to happen.",
    "When someone doesn't realize what is really happening or is not paying enough attention to events around them, you can tell them to wake up and smell the coffee.",
    "A wake-up call is a warning of a threat or a challenge, especially when it means that people will have to change their behavior to meet it.",
    "If you have to walk a fine line, you have to be very careful not to annoy or anger people or groups that are competing. ('Walk a thin line' is an alternative)",
    "This idiom means that you should try to understand someone before criticizing them.",
    "If you walk a tightrope, you have to be very careful not to annoy or anger people who could become enemies.",
    "If you have to walk on eggshells when with someone, you have to be very careful because they get angry or offended very easily.('Walk on eggs' is also used)",
    "someone or something that is walking the green mile is heading towards the inevitable.",
    "If someone walks the plank, they are going toward their own destruction or downfall.",
    "A very knowledgeable person is a walking encyclopedia.",
    "If you are walking on air, you are so happy that you feel as if you could float.",
    "When a person is punished for something. e.g. 'She had me walking on broken glass.'",
    "A person whose behavior is erratic and totally unpredictable is a walking time-bomb.",
    "(UK) A woman politician given an unimportant government position so that the government can pretend it takes women seriously is a wallflower.",
    "A war chest is a fund that can be used to finance a campaign like and election or for use in emergencies or unexpected times of difficulty.",
    "A war of words is a bitter argument between people or organizations, etc.",
    "If something warms the cockles of your heart, it makes you feel happy.",
    "If someone is on the warpath, they are very angry about something and will do anything to get things sorted the way they want.",
    "If you like someone warts and all, you like them with all their faults.",
    "If you wash your hands of something, you disassociate yourself and accept no responsibility for what will happen.",
    "If you don't waste things, you are less likely to end up lacking.",
    "If a person is referred to as a 'waste of skin', it means he is not worth very much.",
    "If something is like watching grass grow, it is really boring.",
    "(USA) This idiom means that you should look behind you for dangers coming that you can't see.",
    "If something is like watching paint dry, it is really boring.",
    "(USA) If something has happened and cannot be changed, it is water over the dam.",
    "If something belongs to the past and isn't important or troubling any more, it is water under the bridge.",
    "(UK) A watering hole is a pub.",
    "If someone has gone to a watery grave, they have drowned.",
    "If people go weak at the knees, they have a powerful emotional reaction to something and feel that they might fall over.",
    "Someone who wears their heart on their sleeve shows their emotions and feelings publicly.",
    "If you weather a storm, you get through a crisis or hard times.",
    "(USA) In wedge politics, one party uses an issue that they hope will divide members of a different party to create conflict and weaken it.",
    "If something is a weight off your shoulders, you have relieved yourself of a burden, normally a something that has been troubling you or worrying you.",
    "Someone who is well-heeled is rich.",
    "If someone is well-oiled, they have drunk a lot.",
    "Something that functions very well is a well-oiled machine.",
    "If someone asks you this, it means that you forgot to close the door when you came in.",
    "Someone who is wet behind the ears is either very young or inexperienced.",
    "A wet blanket is someone who tries to spoil other people's fun.",
    "If you are thirsty and have an alcoholic drink, you wet your whistle. 'Whet your whistle' is also used.",
    "If you have a whale of a time, you really enjoy yourself.",
    "This means that it is not enough to apologize.",
    "(USA) This means that you can't expect people to behave in a way that is not in their character- a 'hog' is a 'pig', so an unrefined person can't be expected to behave in a refined way.",
    "This idiom is often used when someone says something irrelevant to the topic being discussed.",
    "This saying means that of people do bad things to other people, bad things will happen to them.",
    "The expression what will be will be is used to describe the notion that fate will decide the outcome of a course of events, even if action is taken to try to alter it.",
    "When you ask what's cooking it means you want to know what's happening.",
    "This idiom means that the sexes should be treated the same way and not be subjected to different standards.",
    "This is a way of asking someone what they would like to drink, especially alcohol.",
    "This idiom is way of asking someone for their opinion and ideas.",
    "When people say this, they mean that you should do whatever makes you happy.",
    "When the wheels fall off something, it goes wrong or fails. ('Wheels come off' is an alternative)",
    "An impossible or very unlikely situation or event.",
    "This idiom means that when you are visiting a different place or culture, you should try to follow their customs and practices.",
    "This idiom means that when things go wrong, a lot of things go wrong at the same time.",
    "never and impossible. I will marry her when pigs fly.",
    "When a person pays dearly for something bad he or she did in the past, the chickens come home to roost.",
    "(USA) Where the rubber meets the road is the most important point for something, the moment of truth. An athlete can train all day, but the race is where the rubber meets the road and they'll know how good they really are.",
    "This idiom means that if people really want to do something, they will manage to find a way of doing it.",
    "You can make money doing dirty jobs nobody else wants to do. 'Where there's muck, there's money' is also used.",
    "When there is an indication or sign of something bad, usually the indication is correct.",
    "If something whets your appetite, it interests you and makes you want more of it.",
    "This idiomatic expression is used when it is not clear who or what caused something.",
    "People whose behavior is strictly controlled go over the top when the authority is not around, which is why most teenagers have parties when their parents have gone on holiday. The parents are the scary authority figures, but the cat's away and the kids are the mice partying and enjoying their freedom.",
    "If someone says that you can whistle for something, they are determined to ensure that you don't get it.",
    "A whistle-stop tour is when someone visits a number of places quickly, not stopping for long.",
    "(USA) If someone is whistling Dixie, they talk about things in a more positive way than the reality.",
    "If someone is whistling in the dark, they believe in a positive result, even though everybody else is sure it will not happen.",
    "(USA) If someone is whistling past the graveyard, they are trying to remain cheerful in difficult circumstances. ('Whistling past the cemetery' is also used)",
    "A bad shock can make somebody go as white as a sheet.",
    "If something or someone is as white as snow, they are perfect or completely uncorrupted and honest.",
    "A white elephant is an expensive burden; something that costs far too much money to run, like the Millennium Dome in the UK.",
    "If someone shows a white feather, they are cowards.",
    "If you tell a white lie, you lie in order not to hurt someone's feelings.",
    "If something is white-bread, it is very ordinary and boring.",
    "(USA) The person who wears the pants in a relationship is the dominant person who controls things.",
    "(UK) The person who wears the trousers in a relationship is the dominant person who controls things.",
    "'Who will ring the bell?' asks who will assume the responsibility to help us out of a difficult situation.",
    "(USA) The whole ball of wax is everything.",
    "The whole kit and caboodle means 'everything' required or involved in something. ('Kaboodle' is an alternative spelling)",
    "If something's a whole new ball game, it is completely new or different.",
    "The whole nine yards means everything that is necessary or required for something.",
    "The whole shebang includes every aspect of something.",
    "This idiom is usually used to refer to men who don't want to get married, when they can get all the benefits of marriage without getting married.",
    "There's no need to do something yourself when you have somebody to do it for you, usually trivial matters.",
    "If you give someone a wide berth, you keep yourself well away from them because they are dangerous.",
    "If something is wide of the mark, it is inaccurate or incorrect.",
    "A wild goose chase is a waste of time- time spent trying to do something unsuccessfully.",
    "If an idea or project, etc, will never fly, it has no chance of succeeding.",
    "Something that deceives by its appearance is a will-o'-the-wisp; it looks good, but turns out to be a disappointment.",
    "If somebody wins by a nose, they win by a very narrow margin.",
    "If something is done to pretend to be dealing with an issue or problem, rather than actually dealing with it, it is window dressing.",
    "Eyes are sometimes referred to as the window to the soul.",
    "If you do something on a wing and a prayer, you try to do something and hope you'll succeed even though you have a very little chance of success.",
    "If everything goes to the winner, as in an election, the winner takes all.",
    "(UK) If you wipe the floor with someone, you destroy the arguments or defeat them easily.",
    "If you wipe the smile of someone's face, you do something to make someone feel less pleased with themselves.",
    "If someone does something with a heavy hand, they do it in a strict way, exerting a lot of control.",
    "(UK) If a woman's with child, she's pregnant.",
    "If you pass something with flying colours (colors), you pass easily, with a very high mark or grade.",
    "This expression is used when people behave badly or treat someone badly that they are supposed to be friends with.",
    "If something withers on the vine, it fails to get the intended result, doesn't come to fruition.",
    "If you come within a whisker of doing something, you very nearly manage to do it but don't succeed.",
    "If something happens without a hitch, nothing at all goes wrong.",
    "This is used to wish that bad things will happen to someone, usually because of their bad behavior.",
    "This means that you are sad or in a difficult situation. It's archaic, but still used.",
    "A wolf in sheep's clothing is something dangerous that looks quite safe and innocent.",
    "(UK) If someone can't see the wood for the trees, they get so caught up in small details that they fail to understand the bigger picture.",
    "If something becomes known by word of mouth, it is because people are talking about it, not through publicity, etc.",
    "If words fail you, you can't find the words to express what you are trying to say.",
    "If something works like a charm, it works perfectly.",
    "If you work like a dog, you work very hard.",
    "If people work the system, they exploit the state or similar setup to their advantage.",
    "If you work your fingers to the bone, you work extremely hard on something.",
    "If you work your socks off, you work very hard.",
    "If you work your tail off, you work extremely hard.",
    "If everything is going well and the future looks full of opportunity, you have the world at your feet.",
    "When the world is your oyster, you are getting everything you want from life.",
    "If you worm information out of somebody, you persuade them to tell you something they wanted to keep from you.",
    "A worm's eye view of something is the view from below, either physically or socially.",
    "If something's worse for wear, it has been used for a long time and, consequently, isn't in very good condition. A person who's worse for wear is drunk or high on drugs and looking rough.",
    "This idiomatic expression is used as a way of telling someone not to worry so much about their problems.",
    "If something is worth a shot, it is worth trying as there is some chance of success.",
    "Someone who is worth their salt deserves good things especially respect.",
    "If someone wraps themselves in the flag, they pretend to be doing something for patriotic reasons or out of loyalty, but their real motives are selfish. ('Drape yourself in the flag' is an alternative form of this idiom)",
    "(USA) If someone puts or throws a wrench, or monkey wrench, in the works, they ruin a plan. In British English, 'spanner' is used instead of 'wrench'.",
    "If something is writ large, it is emphasized or highlighted.",
    "If you write your own ticket or story, you control the terms and conditions for something and have them exactly the way you want.",
    "If the writing's on the wall for something, it is doomed to fail.",
    "If someone has done something wrong or secret, but cannot hide it in their expression, it is written all over their face.",
    "If something is written in stone, it is permanent and cannot be changed.",
    "If someone has got the wrong end of the stick, they have misunderstood what someone has said to them.",
    "If you start something on the wrong foot, you start badly.",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 5.0,
        backgroundColor: Colors.indigoAccent,
        title: Text(
          'W',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            fontSize: 26.0,
          ),
        ),
        centerTitle: true,
      ),
      backgroundColor: Colors.white,
      body: SafeArea(
        child: ListView.builder(
          itemCount: _name.length,
          itemBuilder: (context, index) {
            return ContentScreen(
              text: _name[index],
              text2: _nameDescription[index],
            );
          },
        ),
      ),
    );
  }
}
